import re
import csv

# Input text
data = """
[1] Md. Motaleb Hossen Manik, Fabliha Haque, Md. Ahsan Habib, Md. Zabirul Islam, Tanim Ahmed, and M.M.A. Hashem, ”Bangla Sentiment Analysis: Exploring A New Rule-Based Approach”, Elsevier Heliyon Journal, Vol. xx, No. xx, pp. xx-xx (Uner Review) (2024)
[2] Abrar Hasan and M.M.A. Hashem, “A Lightweight Cryptographic Framework Based on Hybrid
Cellular Automata for IoT Applications”, IEEE Access, Vol. xx, No. xx, pp.xx-xx (Accepted with Revisions) (2024).
[3] Abdul Aziz, Md.Asaf-uddowla Golap, and M.M.A. Hashem ”A Fuzzy Logic Based Student Learning Assessment System for Outcome Based Education,” IEEE Transactions on Education, Vol. xx, No.
xx, pp.xx-xx, (2024)[Accepted with Revisions] Pub List of Prof.M.M.A. Hashem, KUET 
[4] S. M. Taslim Uddin Raju, Safin Ahmed Dipto, Md Imran Hossain, Md. Abu Shahid Chowdhury, Fabliha Haque, Ayesha Tun Nashrah, Araf Nishan, Md Mahamudul Hasan Khan, and M.M.A. Hashem, “DNN-BP: A Novel Framework for Cuffless Blood Pressure Measurement from Optimal PPG Features Using Deep Learning Model”, Journal of Medical & Biological Engineering & Computing. https://doi.org/10.1007/s11517-024-03157-1 (2024)
[5] Nowshin Tasnim, Iftekher Toufique Imam, and M.M.A. Hashem, “A Novel Multi-Module Approach to Predict Crime Based on Multivariate Spatio-Temporal Data Using Attention and Sequential Fusion Model”, IEEE Access, Vol. 10, pp.48009-48030, DOI: 10.1109/ACCESS.2022.3171843, (2022) [6] Sunanda Das, Awal Ahmed Fime, Nazmul Siddique, and M.M.A Hashem,”Estimation of Road Boundary for Intelligent Vehicles Based on DeepLabV3+ Architecture”, IEEE Access,Vol: 9, pp 121060-121075, DOI:10.1109/ACCESS.2021.3107353, (2021)
[7] Md. Badiuzzaman Shuvo, Rifat Ahommed, Sakib Reza, and M.M.A Hashem, “CNL-UNet: A Novel Lightweight Deep Learning Architecture for Multimodal Biomedical Image Segmentation with False Output Suppression”, Jounal of Biomedical Signal Processing and Control(Elsevier), Vol:70, 102959 [https://doi.org/10.1016/j.bspc.2021.102959], (2021)
[8] Md Kamrul Hasan, Md Hasanul Aziz, Md Ishrak Islam Zarif, Mahmudul Hasan, M.M.A. Hashem,Shion Guha, Richard Love, Sheikh Ahamed, ”Noninvasive Hemoglobin Level Prediction in a Mobile Phone Environment: State of the Art Review and Recommendations”, JMIR mHealth and uHealth, Vol:9, No: 4, e16806 [DOI: https://doi.org/10.2196/preprints.16806](2021)
[9] Md. Asaf-uddowla Golap, S. M. Taslim Uddin Raju, Md. Rezwanul Haque, and M.M.A Hashem, “Hemoglobin and Glucose Level Estimation from PPG Characteristics Features of Fingertip Video Using MGGP-Based Model”, Jounal of Biomedical Signal Processing and Control(Elsevier), Vol. 67,102478 [https://doi.org/10.1016/j.bspc.2021.102478], (2021)
[10] Md. Rezwanul Haque, S. M. Taslim Uddin Raju, Md. Asaf-uddowla Golap, and M.M.A Hashem,”A Novel Technique for Non-Invasive Measurement of Human Blood Component Levels from Fingertip Video Using DNN Based Models”, IEEE Access, Vol.: 9, pp.:19025-19042, DOI:10.1109/ACCESS.2021.3054236 (2021)
[11] Md Kamrul Hasan, Md Hasanul Aziz, Md Ishrak Islam Zarif, Mahmudul Hasan, M.M.A. Hashem,Shion Guha, Richard Love, Sheikh Ahamed, ”HeLP ME: Recommendations for Non-invasive Hemoglobin Level Prediction in Mobile-phone Environment”, JMIR mHealth and uHealth,[DOI: https://doi.org/10.2196/preprints.16806], (2019)
[12] Mahmudul Hasan, Md. Milon Islam, Md Ishrak Islam Zarif and M.M.A. Hashem, “Attack and Anomaly Detection in IoT Sensors in IoT Sites Using Machine Learning Approaches”, Journal of Internet of Things: Engineering Cyber Physical Human Systems (Elseiver), Vol. 07, pp. XX-XX,
[doi: https://doi.org/10.1016/j.iot.2019.100059], (2019).
[13] Kawser Wazed Nafi, Tonny Shekha kar, Amjad Hossain and M.M.A. Hashem, “A New Trustedand Secured Cloud Computing Based E-Commerce Model”, Journal of Communications (AcademyPublishers), Vol.XX, No. XX, pp. XX-XX, [doi:10.4304/jnw.4.10.931-940] (2013).
[14] Kawser Wazed Nafi, Tonny Shekha Kar, Amjad Hossain and M.M.A. Hashem, “An Advanced Certain Trust Model Using Fuzzy Logic and Probabilistic Logic theory”, International Journal of Advanced Computer Science and Applications (IJACSA), Vol. 3, No. 12, pp. 164-173, [doi: 10.14569/IJACSA.2012.031226] (2012).
[15] Kawser Wazed Nafi, Tonny Shekha Kar, Sayed Anisul Hoque, M.M.A. Hashem, “A Newer User Authentication, File encryption and Distributed Server Based Cloud Computing Security Architecture”, International Journal of Advanced Computer Science and Applications (IJACSA), Vol. 3, No. 10, pp. 181-186, [doi: 10.14569/IJACSA.2012.031029] (2012).
[16] Moslema Jahan, M.M.A. Hashem and Gazi Abdullah Shahriar, “Distributed Evolutionary Computation: A New Technique for Solving Large Number of Equations,” International Journal of Parallel and Distributed Systems (IJPDS), Vol. 2, No.6, pp.31-49, [DOI: 10.5121/ijdps.2011.2604] (2011).
[17] A.R.M. Jalal Uddin Jamali, M. Arif Hossain and M.M.A. Hashem, “Crossover- A Redundant Operator for Solving System of Linear Equations by Uniform Adaptive Hybrid Evolutionary Algorithms,” Journal of Engineering Science, Vol. 2, No. 2, pp. 125-134, [ISSN: 2075-4914](2011).
[18] Tanay Dey, M.M.A. Hashem, Subroto Kumar Mondal, ”On Performance Analysis of AMBR Protocol in Mobile Ad Hoc Networks”, IIUM Engineering Journal, Vol 11, No.2, pp.240-254, [ISSN: 1511-788X] (2010).
[19] A.R.M. Jalal Uddin Jamali, M.M.A. Hashem, M. Mahfuz Hasan and Md. Bazlar Rahman,“Solving Linear Equations by Classical Jacobi-SR Based Hybrid Evolutionary Algorithm with Uniform Adaptation Technique,” Journal of Engineering Science, Vol. 1, No. 2, pp. 11-24, [ISSN: 2075-4914](2010).
[20] Md. Amjad Hossain, Md. Kawser Hossain, and M.M.A. Hashem, “A Generalized Hybrid RealCoded Quantum Evolutionary Algorithm Based on Particle Swarm Theory with Arithmetic Crossover,” International Journal of Computers Science and Information Technology (IJCSIT), Vol. 2, No. 4, pp.172-187, [DOI: 10.5121/ijcsit.2010.2415] (2010).
[21] Presila Israt, Namvi Chakma, and M.M.A. Hashem, “A Fuzzy Logic-Based Adaptive Handoff Management Protocol for Next-Generation Wireless Systems,” Journal of Networks (Academy Publishers), Vol. 4, No. 10, pp. 931-940, [doi:10.4304/jnw.4.10.931-940](2009).
[22] Hussain Mohammed, M.M.A. Hashem, and Palash Gupta, ”An Efficient Packet Scheduling Algorithm for 4G IP-Based Mobile Networks”, IIUM Engineering Journal, Vol 10, No.1, pp. 31-48, [ISSN: 1511-788X](2009).
[23] M.B. Islam, M.M.B. Azadi, M.A. Rahman, and M.M.A. Hashem, ”Modified Syntactic Method to Recognize Bengali Handwritten Characters”, IEEE Transactions on Instrumentation and Measurement, Vol 56, No. 6, pp. 2623-2632,[doi: 10.1109/TIM.2007.907955] (2007).
[24] A.R.M. Jalal Uddin Jamali, Md. Bazlar Rahman, and M.M.A. Hashem, “Solving Linear Equations by Classical Jacobi-SR Based Hybrid Evolutionary Algorithm with Time-Variant Adaptation Technique,” Ganit: Journal of Bangladesh Mathematical Society, Vol. 24, pp. 67-79, (2005).
[25] A.R.M. Jalal Uddin Jamali, M.M.A. Hashem, and Md. Bazlar Rahman, “An Approach to Solve Linear Equations Using a Time-Variant Adaptation Based Hybrid Evolutionary Algorithm,” Jahangirnagar University Journal of Science, Vol. 27, pp. 277-289, (2004).
[26] M.M.A. Hashem, K. Watanabe and K. Izumi, “Evolutionary Collision Free Optimal Trajectory Planning for Mobile Robots,” Journal of Robotics and Mechatronics, Vol. 11, No. 2, pp. 153-164, (1999).
[27] K. Izumi, K. Watanabe and M.M.A. Hashem, ”Evolutionary Strategy Using Statistical Information and Its Application to Mobile Robot Control,” Journal of Advanced Computational Intelligence, Special Issue on Advanced Computational Intelligence in Control Theory and Applications, Vol. 3, No. 2, pp. 75-81, (1999).
[28] M.M.A. Hashem, K. Watanabe and K. Izumi, ”Stable-Optimum Gain Tuning for Designing Mobile Robot Controllers Using Incest Prevented Evolution,” Journal of Advanced Computational Intelligence, Vol. 2, No. 5, pp. 164-175, (1998).
[29] M.M.A. Hashem, K. Watanabe and K. Izumi, ”A New Evolution Strategy and Its Application to Solving Optimal Control Problems,” JSME International Journal, Series C, Vol. 41, No. 3, pp. 406-412, (1998).
[30] B.C. Ghosh and M.M.A. Hashem, “Microprocessor-Based Precision Speed Measurement,” Journal of Electrical Engineering (IEB), Vol. EE, No. I and II pp. 9-14, (1997).
[31] B.C. Ghosh, M.M.A. Hashem and S.N. Bhadra, “On-line Rotor Resistance Identification of a Vector Controlled Induction Motor Drive,” Journal of the IEB (Electrical Engineering Division), Vol.EE, No. I and II, pp. 37-49, (1995).
[1] Md. Sakhawat Hossain, and M.M.A. Hasehm “An Improved Dependent Task Offloading in Device-Edge-Cloud using Favorite Predecessor Task,” Procs. of the 2nd International Conference on Information and Communication Technology (ICICT 2024), pp.xx-xx, Dhaka, Bangladesh, October 21-22, (2024).
[2] Subah Nawar, Taslima Akter Joty, and M.M.A. Hasehm “A Lightweight Deep Learning Architecture for Efficient Multimodal Medical Image Segmentation Using Attention Mechanism,” Procs. of the 3rd International Conference on Computing Advancements (ICCA 2024), pp.xx-xx, Dhaka, Bangladesh, October 17-18, (2024).
[3] Asnuva Tanvin, Sazia Rahman, and M.M.A. Hasehm “A Generalized Additive Decomposition Based Deep Neural Network Architecture for Time Series Forecasting Problems,” Procs. of the IEEE 2023 6th International Conference on Electrical Information and Communication Technology (EICT 2023), pp.xx-xx, Khulna, Bangladesh, December 7-9, (2023).
[4] Shourin Paul, Md. Asiful Islam Miah, Sunanda Das, and M.M.A. Hashem “Chest-InfNet: A Deep Learning Architecture for Lung Diseases Detection and Infected Region Localization from Chest X-Ray Images,” Procs. of the International Conference on Big Data, IoT and Machine Learning (BIM 2023), pp.XX-XX, Dhaka, Bangladesh, September 06-08, (2023).
[5] S. M. Taslim Uddin Raju and M.M.A. Hashem “Real-Time Hemoglobin Measurement Using Smartphone Video and Artificial Neural Network,” Procs. of the IEEE 2022 4th International Conference on Electrical, Computer Telecommunication Engineering (ICECTE 2022), pp.xx-xx, Rajshahi, Bangladesh, December 29-31, (2022).
[6] Md. Motaleb Hossen Manik, Fabliha Haque, M.M.A. Hashem, Md. Ahsan Habib, Md. Zabirul Islam, and Tanim Ahmed “A Hybrid Framework for Sentiment Analysis from Bangla Texts,” Procs. of the IEEE 2022 25th International Conference on Computer Information Technology (ICCIT 2022), pp.XX-XX, Cox’s Bazar, Bangladesh, December 17-19, (2022).
[7] S. M. Taslim Uddin Raju and M.M.A. Hashem “DNN Based Blood Glucose Level Estimation Using PPG Characteristic Features of Smartphone Videos,” Procs. of the IEEE 2022 25th International Conference on Computer Information Technology (ICCIT 2022), pp.XX-XX, Cox’s Bazar, Bangladesh, December 17-19, (2022).
[8] Towsif Ahamed Labib, Md. Nazrul Islam, S. M. Taslim Uddin Raju and M.M.A. Hashem Blood Donor Arrival Forecasting and Analysis of Donor Behavioral Pattern,” Procs. of the IEEE 2022 25th International Conference on Computer Information Technology (ICCIT 2022), pp.XX-XX, Cox’s Bazar, Bangladesh, December 17-19, (2022).
[9] Zahra Ferdous, Saadman Sakib, and M.M.A. Hashem, “Fall Guardian: An Intelligent Fall Detection and Monitoring System for Elderly,” Procs. of the IEEE 2021 5th International Conference on Electrical Information and Communication Technology (EICT 2021), pp.xx-xx, Khulna, Bangladesh, December 17-19, (2021).
[10] Kristy Saha, Md. Mushfiqur Rahman Fakir, and M.M.A. Hashem, “An Unsupervised SelfOrganizing Map Assisted Deep Autoencoder Gaussian Mixture Model for IoT Anomaly Detection,” Procs. of the IEEE 2021 5th International Conference on Electrical Information and Communication Technology (EICT 2021), pp.xx-xx, Khulna, Bangladesh, December 17-19, (2021).
[11] Md Afnan Ul Haque, Ashiqur Rahman, and M.M.A. Hashem, “Sentiment Analysis in Low- esource Bangla Text Using Active Learning,” Procs. of the IEEE 2021 5th International Conference onElectrical Information and Communication Technology (EICT 2021), pp.xx-xx, Khulna, Bangladesh, December 17-19, (2021).
[12] Md. Nazmus Shakib, Md. Shamim, Md Nazirul Hasan Shawon, Most. Kaniz Fatema Isha, M.M.A. Hashem, and M.A.S. Kamal, “An Adaptive System for Detecting Driving Abnormality of Individual Drivers Using Gaussian Mixture Model,” Procs. of the 2021 IEEE 5th International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT 2021), pp.xx-xx, Dhaka, Bangladesh, November 18-20, (2021).[Won BEST PAPER AWARD (1st Prize)]
[13] Rifat Ahommed, Md. Badiuzzaman Shuvo, and M.M.A. Hashem, “Analysis of CNL-UNet for Efficient Biomedical Image Segmentation,” Procs. of the 2021 IEEE 5th International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT 2021), pp.xx-xx, Dhaka, Bangladesh, November 18-20, (2021).
[14] Abdul Aziz and M.M.A. Hashem, “Fuzzy Logic Based Assessment of Students Learning Outcome in Implementing Outcome Based Education,” Procs. of the International Conference on Big Data, IoT and Machine Learning (BIM 2021) , pp.745-759, Cox’s Bazar, Bangladesh, September 23-25, (2021).
[15] Most. Kaniz Fatema Isha, Md Nazirul Hasan Shawon, Md. Shamim, Md. Nazmus Shakib, M.M.A. Hashem, and M.A.S. Kamal, “A DNN Based Driving Scheme for Anticipative Car Following Using
Road-Speed Profile,” Procs. of the 2021 IEEE 32nd Intelligent Vehicles Symposium (IV 21) , pp.496-501, Nagoya, Japan, July 11-17, (2021).
[16] Anik Pramanik, Amlan Sarker, Zabirul Islam, and M.M.A. Hashem, “Public Sector Corruption Analysis with Modified K-means Algorithm Using Perception Data,” Procs. of the 2020 IEEE 11th International Conference on Electrical and Computer Engineering (ICECE 2020), pp.197-200, Dhaka, Bangladesh, December 17-19, (2020).
[17] Sakib Reza, Ohida Binte Amin, and M.M.A. Hashem, “TransResUNet: Improving U-Net Architecture for Robust Lungs Segmentation in Chest X-rays,” Procs. of the 2020 IEEE Region 10 Symposium (TENSYMP 2020), pp.XX-XX, Dhaka, Bangladesh, June 5-7, (2020).
[18] Raihanul Islam Refat, Md. Abdul Hannan, and M.M.A. Hashem, “A Secure IoT Data Communication and Sharing Framework Based on Permissioned Blockchain,” Procs. of the 2020 IEEE Region 10 Symposium (TENSYMP 2020), pp.XX-XX, Dhaka, Bangladesh, June 5-7, (2020).
[19] Md. Fazle Rasul, Nahin Kumar Dey and M.M.A. Hashem, “A Comparative Study of Neural Network Architectures for Lesion Segmentation and Melanoma Detection,” Procs. of the 2020 IEEE Region 10 Symposium (TENSYMP 2020), pp.XX-XX, Dhaka, Bangladesh, June 5-7, (2020).
[20] Fabliha Haque, Md. Motaleb Hossen Manik, and M.M.A. Hashem, “Opinion Mining from Bangla and Phonetic Bangla Reviews Using Vectorization Methods,” Procs. of the IEEE 2019 4th International Conference on Electrical Information and Communication Technology (EICT 2019), pp.xx-xx, Khulna, Bangladesh, December 20-22, (2019).
[21] Sakib Reza, Ohida Binte Amin, and M.M.A. Hashem, “Basic to Compound: A Novel Transfer Learning Approach for Bengali Handwritten Character Recognition,” Procs. of the IEEE 2nd International Conference on Bangla Speech and Language Processing (ICBSLP 2019), pp.XX-XX, Sylhet, Bangladesh, September 27-28, (2019).
[22] Sakib Reza, Ohida Binte Amin, and M.M.A. Hashem, “A Novel Feature Extraction and Selection Technique for Chest X-ray Image View Classification,” Procs. of the IEEE 2019 5th International Conference on Advances in Electrical Engineering (ICAEE 2019), pp. XX-XX, Dhaka, Bangladesh, September 26-28, (2019).
[23] Md. Asaf-uddowla Golap and M.M.A. Hashem, “Non-Invasive Hemoglobin Concentration Measurement Using MGGP-Based Model,” Procs. of the IEEE 2019 5th International Conference on Advances in Electrical Engineering (ICAEE 2019), pp. XX-XX, Dhaka, Bangladesh, September 26-28, (2019).
 [24] Dola Das, Nawshin Tabassum, Mahmudul Hasan and M.M.A. Hashem, “Deep Neural Network Based Continuous BloodPressure Estimation with Data Mining Techniques,” Procs. of the IEEE 2019 5th International Conference on Advances in Electrical Engineering (ICAEE 2019), pp. XX-XX, Dhaka, Bangladesh, September 26-28, (2019).
[25] Tusher Chandra Mondol, Hasib Iqbal, and M.M.A. Hashem, “Deep CNN-Based Ensemble CADx Model for Musculoskeletal Abnormality Detection from Radiographs,” Procs. of the IEEE 2019 5th International Conference on Advances in Electrical Engineering (ICAEE 2019), pp. XX-XX, Dhaka, Bangladesh, September 26-28, (2019).
[26] Abdul Aziz, Md. Asaf-uddowla Golap, and M.M.A. Hashem, “Student’s Academic Performance Evaluation Method Using Fuzzy Logic System,” Procs. of the IEEE 2019 1st International Conference on Advances in Science, Engineering and Robotics Technology (ICASERT 2019), pp. XX-XX,
Dhaka, Bangladesh, May 3-5, (2019).
[27] Monika Gope and M.M.A. Hashem, “Knowledge Extraction from Bangla Documents Using NLP: A Case Study,” Procs. of the IEEE 2019 International Conference on Electrical, Computer and Communication Engineering (ECCE 2019), pp.XX-XX, Cox’s Bazar, Bangladesh, February 7-9, (2019).
[28] Prodip Kumer Das, Mohammad Badiul Islam; Guido Governatori, M.M.A. Hashem, and M.M.A. Hashem, “Database Independent Analysis of Adverse Events Using Rule-Based Systems,” Procs. of the IEEE 2019 International Conference on Electrical, Computer and Communication Engineering (ECCE 2019), pp.XX-XX, Cox’s Bazar, Bangladesh, February 7-9, (2019).
[29] Mehbuba Zerin Khan and M.M.A. Hashem, “A Comparison between HTML5 and OpenGL in Rendering Fractal,” Procs. of the IEEE 2019 International Conference on Electrical, Computer and Communication Engineering (ECCE 2019), pp.XX-XX, Cox’s Bazar, Bangladesh, February 7-9, (2019).
[30] Tajul Islam and M.M.A. Hashem, “Task Scheduling in Big Data Management in Fog Infrastructure,” rocs. of the IEEE 2018 21st International Conference on Computer Information Technology (ICCIT 2018), pp.XX-XX, Dhaka, Bangladesh, December 21-23, (2018).
[31] Torikul Islam, Jannatul Ferdush and M.M.A. Hashem, “Secured Cloud Computing Outsourcing: A Case Study of Constrained Linear Least Square Problem,” Procs. of the 2018 IEEE 5th International Conference on Networking, Systems and Security (NSysS 2018), pp.141-145, Dhaka, Bangladesh,December 18-20, 2018).
[32] Monika Gope and M.M.A. Hashem, “Knowledge Extraction from Bangla Documents: A Case Study,” Procs. of the IEEE International Conference on Bangla Speech and Language Processing (ICBSLP 2018), pp.1-6, Sylhet, Bangladesh, September 21-22, (2018).
[33] Tajul Islam and M.M.A. Hashem, “A Big Data Management Strategy Using Fog Computing,” Procs. of the 2018 IEEE International Conference on Innovations in Engineering, Technology andSciences (ICIETS 2018), pp.XX-XX, Mysore, India, September 20-21, (2018).
[34] Jannatul Ferdush and M.M.A. Hashem, “A New Secured Cloud Computing Service: A Case Study of Large-Scale Linear Regression,” Procs. of the IEEE 4th International Conference on Electrical Engineering and Information & Communication Technology (iCEEiCT 2018), pp.XX-XX, Dhaka, Bangladesh, September 13-15, (2018).
[35] Tajul Islam and M.M.A. Hashem, “A Big Data Management System for Providing Real Time Services Using Fog Infrastructure,” Procs. of the 2018 IEEE Symposium on Computer Applications & Industrial Electronics (ISCAIE 2018), pp.85-89, Penang, Malaysia, April 28-29, (2018).
[36] Jannatul Ferdush and M.M.A. Hashem, “Secured Cloud Computing Service: A Case Study of Large Scale Lyapunov Equation,” Procs. of the IEEE 2017 International Conference on Electrical, Computer and Communication Engineering (ECCE 2017), pp.339-343, Cox’s Bazar, Bangladesh, February 16-18, (2017).[37] Jannatul Ferdush, Tasnim Mehzabin and M.M.A. Hashem, “Securely Outsourcing of Large Scale Linear Fractional Programming Problem to Public Cloud”, Procs. of the IEEE 2016 5th International Conference on Informatics, Electronics and Vision (ICIEV 2016), pp.373-378, Dhaka, Bangladesh, May 13-14, (2016).
[38] Md. Kamrul Hasan, Md. Milon Islam and M.M.A. Hashem, “Mathematical Model Development to Detect Breast Cancer Using Multigene Genetic Programming”, Procs. of the IEEE 2016 5th International Conference on Informatics, Electronics and Vision (ICIEV 2016), pp.574-579, Dhaka, Bangladesh, May 13- 4, (2016).
[39] Md. Abdul Awal, Jakaria Rabbi, Sk. Imran Hossain, and M.M.A. Hashem, “A Hybrid Approach to Plan Itinerary for Tourists”, Procs. of the IEEE 2016 5th International Conference on Informatics, Electronics and Vision (ICIEV 2016), pp.219-223, Dhaka, Bangladesh, May 13-14, (2016).
[40] Md. Abdul Awal, Jakaria Rabbi, Sk. Imran Hossain, and M.M.A. Hashem, “Using linear regression to forecast future trends in crime of Bangladesh”, Procs. of the IEEE 2016 5th International Conference on Informatics, Electronics and Vision (ICIEV 2016), pp.xx-xx, Dhaka, Bangladesh, May 13-14, (2016).
[41] Jarin Firose Moon, Shamminuj Aktar and M.M.A. Hashem, “Securely Outsourcing Large Scale Eigen Value Problem to Public Cloud,” Procs. of the IEEE 2015 18th International Conference on Computer Information Technology (ICCIT 2015), pp.490-4494, Dhaka, Bangladesh, December 21-23, (2015).
[42] Md. Siddiqur Rahman Tanveer, M.M.A. Hashem and Md. Kowsar Hossain, “Android Assistant EyeMate for Blind and Blind Tracker,” Procs. of the IEEE 2015 18th International Conference on Computer Information Technology (ICCIT 2015), pp.266-271, Dhaka, Bangladesh, December 21-23, (2015).
[43] Sikder Tahsin Al-Amin, Mahade Hasan, and M.M.A. Hashem, “A Modified Fuzzy Relational Clustering Approach for Sentence-Level Text,” Procs. of the IEEE 2015 2nd International Conference on Electrical Information and Communication Technology (EICT 2015), pp.566-570, Khulna, Bangladesh, December 21- 3, (2015).
[44] Sudipta Singha Roy, Tamjid Haque Sarker, and M.M.A. Hashem, “A Novel Trust Measurement System for Cloud-based Marketplace,” Procs. of the IEEE 2015 2nd International Conference on Electrical Information and Communication Technology (EICT 2015), pp.49-54, Khulna, Bangladesh, December 21- 3, (2015).
[45] Kawser Wazed Nafi, Tonny Shekha Kar, Amjad Hossain and M.M.A. Hashem, “A New Trusted and E-Commerce Architecture for Cloud Computing,” Procs. of the IEEE 2013 International Conference on Informatics, Electronics and Vision (ICIEV 2013), pp.1-6, Dhaka, Bangladesh, May 17-18, (2013).
[46] Kawser Wazed Nafi, Tonny Shekha Kar, Amjad Hossain and M.M.A. Hashem, “A Fuzzy Logic Based Certain Trust Model for E-Commerce,” Procs. of the IEEE 2013 International Conference on Informatics, Electronics and Vision (ICIEV 2013), pp.1-6, Dhaka, Bangladesh, May 17-18, (2013).
[47] Mohammad Ashekur Rahman, Atanu Barai, Md. Asadul Islam and M.M.A. Hashem, “Development of a Device for Remote Monitoring of Heart Rate and Body Temperature”, Procs. of the IEEE 2012 15th International Conference on Computer Information Technology (ICCIT 2012), pp.411-416, Chittagong, Bangladesh, December 22-24, (2012).
[48] Kawser Wazed Nafi, Tonny Shekha Kar, Amjad Hossain and M.M.A. Hashem, “A Fuzzy and Probabilistic Logic Based Representational Model of Certain Trust Model,” Procs. of the IEEE 2012 International Conference on Informatics, Electronics and Vision (ICIEV 2012), pp.1000-1005, Dhaka, Bangladesh, May 18-19, (2012).
[49] Md. Kawser Hossain, Md. Amjad Hossain, M.M.A. Hashem, Md. Mohsin Ali “Quantum Evolutionary Algorithm Based on Particle Swarm Theory in Multiobjective Problems,” Procs. of theIEEE 2010 13th International Conference on Computer & Information Technology (ICCIT 2010),
pp.21-26, Dhaka, Bangladesh, December 23-25, (2011).
[50] M.M.A. Hashem, Rushdi Shams, Md. Abdul Kader, and Md. Abu Sayed, “Design and Development of a Heart Rate Measuring Device using Fingertip,” Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE10), pp. 197-201, Kuala Lumpur, Malaysia, May 11-13, (2010).
[51] Rushdi Shams, M.M.A. Hashem, Afrina Hossain, Suraiya Rumana Akter, and Monika Gope, “Corpus-based Web Document Summarization using Statistical and Linguistic Approach ,” Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE10), pp. 115-120, Kuala Lumpur, Malaysia, May 11-13, (2010).
[52] Md. Asadul Islam, G. M. Mashrur-E-Elahi, and M.M.A. Hashem, “A New Distributed Evolutionary Computation Technique for Multi-Objective Optimization,” Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE10), pp. 31-36, Kuala Lumpur, Malaysia, May 11-13, (2010).
[53] Md. Amjad Hossain, Md. Kawser Hossain, and M.M.A. Hashem, “A Hybrid Real-Coded Quantum Evolutionary Algorithm Based on Particle Swarm Theory,” Procs. of the IEEE 2009 12th International Conference on Computer & Information Technology (ICCIT 2009), pp.13-18, Dhaka, Bangladesh, December 21-23, (2009).
[54] Moslema Jahan, M.M.A. Hashem and Gazi Abdullah Shahriar, “A New Distributed Evolutionary Computation Technique for Solving Large Number of Equations,” Procs. of the IEEE 2008 11th International Conference on Computer & Information Technology (ICCIT 2008), pp.347-352, Khulna,
Bangladesh, December 25-27, (2008).
[55] Presila Israt, Namvi Chakma, and M.M.A. Hashem, “A Fuzzy Logic-Based Adaptive Handoff Management Protocol for Next-Generation Wireless Systems,” Procs. of the IEEE 2008 11th International Conference on Computer & Information Technology (ICCIT 2008), pp. 288-293, Khulna, Bangladesh, December 25-27, (2008) .
[56] Md. Raihan Masud, M.M.A. Hashem, and Md. Abul Khaer, ”Normalization Approach for Metric Based Software Design Quality Measurement”, Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE08), Vol. I, pp. 138-142, Kuala Lumpur, Malaysia, May 13-15, (2008).
[57] Md. Abul Khaer, M.M.A. Hashem, and Md. Raihan Masud, ”On Use of Design Patterns in Empirical Assessment of Software Design Quality”, Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE08), Vol. I, pp. 133-137, Kuala Lumpur, Malaysia, May 13-15, (2008).
[58] Palash Gupta, Hussain Mohammed, and M.M.A. Hashem, ”An Efficient Packet Scheduling Algorithm for 4G IP-Based Mobile Networks”, Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE08), Vol. I, pp.123-127, Kuala Lumpur, Malaysia, May 13-15, (2008).
[59] Tanay Dey, M.M.A. Hashem, and Subrota Kumar Mondal, ”On Performance Analysis of AMBR Protocol in Mobile Ad Hoc Networks”, Procs. of the IEEE International Conference on Computer and Communication Engineering (ICCCE08), Vol. I, pp. 128-132, Kuala Lumpur, Malaysia, May 13-15, (2008).
[60] M.M. Hafizur Rahman and M.M.A. Hashem, “On Intelligent Learning System”, Procs. of the International Conference on Engineering Professional Ethics and Education (ICEPEE ’08), pp. 314-316, Kuala Lumpur, Malaysia, May 13-15, (2008).
[61] Tanay Dey, Subrota Kumar Mondal and M.M.A. Hashem, ”Performance Enhancement of Ad Hoc Networks with Adaptive Monitor Based Routing,”, Procs. of the 2008 IEEE Radio and Wireless Symposium (RWS 2008), pp.263-266, Orlando, Florida, USA, January 22-24, (2008).
[62] Nafisa Afrin Chowdhury, Murshida Khatun and M.M.A. Hashem, ”On Integrating Fuzzy Knowledge Using a Novel Evolutionary Algorithm,” Procs. of the IEEE 10th International Conference on Computer & Information Technology (ICCIT 2007), pp. 38-43, Dhaka, Bangladesh, December 27-29, (2007).
[63] Md. Abul Khaer, Raihan Masud and M.M.A. Hashem, ”An Empirical Analysis of Software Systems for Measurement of Design Quality Level Based on Design Patterns,” Procs. of the IEEE 10th International Conference on Computer & Information Technology (ICCIT 2007), pp. 430-435, Dhaka, Bangladesh, December 27-29, (2007).
[64] Raihan Masud, Md. Abul Khaer and M.M.A. Hashem, ”Rank-Based Quality Measurement of Software Systems in Standardized Source Code,” Procs. of the IEEE 10th International Conference on Computer & Information Technology (ICCIT 2007), pp. 424-429, Dhaka, Bangladesh, December 27-29, (2007).
[65] Palash Gupta, Hussain Mohammed and M.M.A. Hashem, ”An Efficient Packet Scheduling Algorithm for Downlink Queue to Provide Lossless Handoff and QoS in 4G Mobile Networks,” Procs. of the IEEE 10th International Conference on Computer & Information Technology (ICCIT 2007), pp. 464-469, Dhaka, Bangladesh, December 27-29, (2007).
[66] Palash Gupta, Hussain Mohammed and M.M.A. Hashem, ”Characterization of Downlink Transmit Power Control during Soft Handover in WCDMA Systems,” Procs. of the 9th International Conference on Computer & Information Technology (ICCIT 2006), pp. 448-452, Dhaka, Bangladesh, December 21-23, (2006).
[67] M. Nazrul Islam, Pintu Chandra Shill, Md. Firoz Mridha, D. M. Sariful Islam, and M.M.A. Hashem, ”Generating Weighted Fuzzy Rules for Estimating Null Values Using an Evolutionary Algorithm,” Procs. of the IEEE 4th International Conference on Electrical & Computer Engineering (ICECE’06), pp. 324-327, Dhaka, Bangladesh, December 19-21, (2006).
[68] Isnain Siddique, Rushdi Shams, and M.M.A. Hashem, “Performance Enhancement of Ad Hoc Networks with Janitor Based Routing,” Procs. of the International Conference on Computer & Communication Engineering (ICCCE’06), Vol. I, pp. 368-373, Kuala Lumpur, Malaysia, May 9-11, (2006).
[69] Md. Mamun Ali Sarker, Md. Ashraf Hossain Khan and M.M.A. Hashem, “Guidelines to the Problem of Location Management and Database Architecture for the Next Generation Mobile Networks,” Procs. of the International Conference on Computer & Communication Engineering (ICCCE’06), Vol. II, pp. 761-766, Kuala Lumpur, Malaysia, May 9-11, (2006).
[70] Md. Nazrul Islam, M.M.A. Hashem and A. M. Moshiur Rahman, “A Probabilistic Algorithm for Reducing Broadcast Redundancy in Ad Hoc Wireless Networks,” Procs. of the 8th International Conference on Computer & Information Technology (ICCIT 2005), pp. 752-757, Dhaka, Bangladesh, December 28-30, (2005).
[71] K..M. Motahar Hossain, Zahir Raihan, and M.M.A. Hashem, “On Appropriate Selection of Fuzzy Aggregation Operators in Medical Decision Support System,” Procs. of the 8th International Conference on Computer & Information Technology (ICCIT 2005), pp. 563-568, Dhaka, Bangladesh, December 28-30, (2005).
[72] A. R. M. Jalal Uddin Jamali, Mohammad Arif Hossain, G.M. Moniruzzaman and M.M.A. Hashem, ”For Solving Linear Equations Recombination is a Needless Operation in Time-Variant Adaptive Hybrid Algorithms,” Procs. of the 8th International Conference on Computer & Information Technology (ICCIT 2005), pp. 23-28, Dhaka, Bangladesh, December 28-30, (2005).
[73] Mohammad Badiul Islam, Mollah Masum Billah Azadi, Md. Abdur Rahman, and M.M.A. Hashem, “Bengali Handwritten Character Recognition using Modified Syntactic Method,” Procs. of the 2nd National Conference on Computer Processing of Bangla (NCCPB-2005), pp. 264-275, Independent
University, Bangladesh, Dhaka, Bangladesh, February, (2005).
"""

# Regex pattern to extract authors and titles
pattern = r"\[\d+\]\s([^,]+(?:,\s[^,]+)*),\s[\u201c\u201d\"](.*?)[\u201c\u201d\"]"

# Extract matches
matches = re.findall(pattern, data)

# Prepare data for CSV
csv_data = [(authors.strip(), title.strip()) for authors, title in matches]

# Output file
output_file = "KUET_author_list_2.csv"

# Write to CSV
with open(output_file, mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["Authors", "Title"])
    writer.writerows(csv_data)

print(f"Data extracted and saved to {output_file}.")