import re
import csv

# Provided text
text = """
Nusrat Sultana, Rumana Yasmin, Bijon Mallik, Mohammad Shorif Uddin, "ONUBAD: A comprehensive dataset for automated conversion of Bangla regional dialects into standard Bengali dialect," Data in Brief (Elsevier), Vol. 58, January 2025.  https://doi.org/10.1016/j.dib.2025.111276  (WoS, Scopus, Q2)
Kanija Muntarina, Rafid Mostafiz, Sumaita Binte Shorif, Mohammad Shorif Uddin, "Deep learning-based edge detection for random natural images," Neuroscience Informatics (Elsevier), December 2024,   https://doi.org/10.1016/j.neuri.2024.100183  
Fahmida Khanom, Shuvo Biswas, Mohammad Shorif Uddin, Rafid Mostafiz, "XEMLPD: an explainable ensemble machine learning approach for Parkinson disease diagnosis with optimized features," International Journal of Speech Technology (Springer), October 2024, https://doi.org/10.1007/s10772-024-10152-2  (Scopus, Q1)
Ohiduzzaman, Mahmudul Hasan, Shiming Zhang, Mohammad Nurul Huda, Mohammad Shorif Uddin, "Spectral analysis of bone‑conducted speech using modified linear prediction," International Journal of Speech Technology (Springer), October 2024, https://doi.org/10.1007/s10772-024-10151-3  (Scopus, Q1)
Ohiduzzaman, Mahmudul Hasan, Shiming Zhang, Mohammad Nurul Huda, Mohammad Shorif Uddin, "Ill-condition enhancement for BC speech using RMC method," International Journal of Speech Technology (Springer), October 2024, https://doi.org/10.1007/s10772-024-10159-9  (Scopus, Q1)
Shayla Sharmin, Mohammad Riadur Rashid, Tania Khatun, Md Zahid Hasan, Mohammad Shorif Uddin,  Marzia,"A dataset of color fundus images for the detection and classification of eye diseases," Data in Brief (Elsevier) , Vol. 57, 2024, https://doi.org/10.1016/j.dib.2024.110979 (WoS, Scopus, Q2)
Md. Masum Billah, Azmery Sultana, Rakin Sad Aftab, Mir Maruf Ahmed, Mohammad Shorif Uddin, "Leaf disease detection using convolutional neural networks: a proposed model using tomato plant leaves," Neural Computing and Applications (Springer), August 2024, https://doi.org/10.1007/s00521-024-10283-2 (WoS, Scopus, Q1) 
Shuvo Biswas, Rafid Mostafiz, Mohammad Shorif Uddin, Bikash Kumar Paul, "XAI-FusionNet: Diabetic foot ulcer detection based on multi-scale feature fusion with explainable artificial intelligence," Heliyon (Elsevier), May 2024. https://doi.org/10.1016/j.heliyon.2024.e31228, (WoS, Scopus, Q1)  
Md. Abdul Based, Elias Ur Rahman, Mohammad Shorif Uddin, “Development of an Electronic Voting System using Blockchain Technology and Deep Hybrid Learning,” WSEAS Transactions on Computers, vol. 23, pp. 194-203, August 2024. https://www.doi.org/10.37394/23205.2024.23.18  (Scopus)
Aanmar Abdou Salam, Md. Abdul Based, Mohamed Islam Houssam, Mohammad Shorif Uddin. “Mitigating Malware Threats on Emerging Technology: A Machine Learning Approach,” WSEAS Transactions on Information Science and Applications, vol. 21, pp. 282-290, May 2024. https://www.doi.org/10.37394/23209.2024.21.27 (Scopus, Q4)
Sk. Fahmida Islam, Nayan Chakrabarty, Mohammad Shorif Uddin, "Citrus leaf disease detection through deep learning approach," Bulletin of Electrical Engineering and Informatics, Vol. 13, No. 4, pp. 2643-2649, June 2024. https://doi.org/10.11591/eei.v13i4.4521    (Scopus, Q3)
Mohammad Shorif Uddin, Ohidujjaman, Mahmudul Hasan and Tetsuya Shimamura, “Audio Watermarking: A Comprehensive Review” International Journal of Advanced Computer Science and Applications (SAI Organization), Vol. 15, No. 5, pp. 1410-1418,  May 2024. https://dx.doi.org/10.14569/IJACSA.2024.01505141, (WOS, Scopus, Q3)
Md. Masudul Islam, Galib Muhammad Shahriar Himel, Mohammad Shorif Uddin, Md. Golam Moazzam, "A visual dataset for recognition of rice varieties," Data in Brief (Elsevier), 2024. https://doi.org/10.1016/j.dib.2024.110442. (WoS, Scopus, Q2) 
Mahbuba Begum, Sumaita Binte Shorif, Mohammad Shorif Uddin, Jannatul Ferdush, Tony Jan, Alistair Barros, Md Whaiduzzaman, "Image Watermarking Using Discrete Wavelet Transform and Singular Value Decomposition for Enhanced Imperceptibility and Robustness," Algorithms (MDPI), 17(1), 32, January 2024, https://doi.org/10.3390/a17010032 (WoS, Scopus, Q2)
Tania Khatun, Md. Asraful Sharker Nirob, Prayma Bishshash, Morium Akter, Mohammad Shorif Uddin, "A comprehensive dragon fruit image dataset for detecting the maturity and quality grading of dragon fruit," Data in Brief (Elsevier), Vol. 52, January 2024, https://doi.org/10.1016/j.dib.2023.109936  (WoS, Scopus, Q2)
Muhammad Kamal Hossen and Mohammad Shorif Uddin, "Attention monitoring of students during online classes using XGBoost classifier," Computers and Education: Artificial Intelligence (Elsevier), December 2023, https://doi.org/10.1016/j.caeai.2023.100191 (Scopus, Q1)
Muhammad Kamal Hossen and Mohammad Shorif Uddin, "A dataset for assessing real-time attention levels of the students during online classes," Data in Brief (Elsevier), Vol. 51, December 2023, https://doi.org/10.1016/j.dib.2023.109771 (WoS, Scopus, Q2)
Tania Khatun, Abdur Razzak, Md. Shofiul Islam, Mohammad Shorif Uddin, "An extensive real-world in field tomato image dataset involving maturity classification and recognition of fresh and defect tomatoes," Data in Brief (Elsevier), Vol. 51, December 2023, https://doi.org/10.1016/j.dib.2023.109688  (WoS, Scopus, Q2)
Kanija Muntarina, Rafid Mostafiz, Fahmida Khanom, Sumaita Binte Shorif, Mohammad Shorif Uddin, "MultiResEdge: A Deep Learning-Based Edge Detection Approach," Intelligent Systems with Applications (Elsevier), Vol. 20, November 2023, https://doi.org/10.1016/j.iswa.2023.200274  (WoS, Scopus, Q1)
Nusrat Sultana, Sumaita Binte Shorif, Morium Akter, Mohammad Shorif Uddin, "A dataset for successful recognition of cucumber diseases," Data in Brief (Elsevier), vol. 49, August 2023, https://doi.org/10.1016/j.dib.2023.109320 (WoS, Scopus, Q2)
Shinthi Tasnim Himi, Natasha Tanzila Monalisa, Md Whaiduzzaman, Alistair Barros, Mohammad Shorif Uddin, "MedAi: A Smartwatch-Based Application Framework for Common Diseases Prediction using Machine Learning," IEEE Access (IEEE), vol. 11, pp. 12342-12359, 2023,  https://doi.org/10.1109/ACCESS.2023.3236002  (WoS, Scopus, Q1)
Mostafiz Ahammed, Md. Al Mamun, Mohammad Shorif Uddin, "A machine learning approach for skin disease detection and classification using image segmentation," Healthcare Analytics (Elsevier), November 2022, https://doi.org/10.1016/j.health.2022.100122  (Scopus)
Nusrat Sultana, Musfika Jahan, Mohammad Shorif Uddin, "An extensive dataset for successful recognition of fresh and rotten fruits," Data in Brief (Elsevier), Vol 44, October 2022, https://doi.org/10.1016/j.dib.2022.108552  (WoS, Scopus, Q2)
Md. Al Mamun, Md. Solaiman Kabir, Morium Akter, Mohammad Shorif Uddin, "Recognition of human skin diseases using inception-V3 with transfer learning," International Journal of Information Technology, (Springer), August 2022, https://doi.org/10.1007/s41870-022-01050-4  (Scopus, Q2) 
M. A. A. Siddique, Jannatul Ferdouse, Md. Tarek Habib, Md. Jueal Mia, Mohammad Shorif Uddin, “Convolutional Neural Network Modeling for Eye Disease Recognition”, International Journal of Online and Biomedical Engineering (iJOE), vol. 18, no. 09, pp. 115–130, September 2022, https://doi.org/10.3991/ijoe.v18i09.29847 (WoS, Scopus, Q2)
Umme Sara, Aditya Rajbongshi, Rashiduzzaman Shakil, Bonna Akter, Mohammad Shorif Uddin, "VegNet: An organized dataset of cauliflower disease for a sustainable agro-based automation system," Data in Brief (Elsevier), vol. 43, August 2022, https://doi.org/10.1016/j.dib.2022.108422 (WoS, Scopus, Q2)
Md. Sabab Zulfiker, Nasrin Kabir, Al Amin Biswas, Sunjare Zulfiker, Mohammad Shorif Uddin, "Analyzing the public sentiment on COVID-19 vaccination in social media: Bangladesh context," Array (Elsevier), June 2022, https://doi.org/10.1016/j.array.2022.100204  (Scopus, Q1)
Rafid Mostafiz, Mohammad Shorif Uddin, Khandaker Mohammad Mohi Uddin, Mohammad Motiur Rahman, "COVID-19 along with Other Chest Infections Diagnosis Using Faster R-CNN and Generative Adversarial Network," ACM Transactions on Spatial Algorithms and Systems (ACM), June 2022, https://doi.org/10.1145/3520125 (WoS, Scopus, Q2)
Umme Sara, Aditya Rajbongshi, Rashiduzzaman Shakil, Bonna Akter, Sadia Sazzad, Mohammad Shorif Uddin, "An extensive sunflower dataset representation for successful identification and classification of sunflower diseases," Data in Brief (Elsevier), vol. 42, June 2022 https://doi.org/10.1016/j.dib.2022.108043  (WoS, Scopus, Q2)
Rafid Mostafiz, Mohammad Shorif Uddin, Iffat Jabin, Muhammad Minoar Hossain, Mohammad Motiur Rahman, "Automatic Brain Tumor Detection from MRI using Curvelet Transform and Neural Features," International Journal of Ambient Computing and Intelligence (IGI Global), 13(1), March 2022 https://doi.org/10.4018/IJACI.293163   (WoS, Scopus, Q3)
Fauzia Yasmeen and Mohammad Shorif Uddin, "An efficient image steganography approach based on QR factorization and singular value decomposition in non-subsampled contourlet transform domain," Security and Privacy (Wiley), March 2022 https://doi.org/10.1002/spy2.229  (WoS)
Fauzia Yasmeen and Mohammad Shorif Uddin, "A Novel Watermarking Scheme Based on DWT-SVD," Security and Privacy (Wiley), February 2022 https://doi.org/10.1002/spy2.216  (WoS)
Mohammad Meraj Khan, Mohammad Shorif Uddin, Mohammad Zavid Parvez, Lutfur Nahar, Jia Uddin, "A Deep Convolution Neural Network-Based SE-ResNext Model for Bangla Handwritten Basic to Compound Character Recognition," Journal of Hunan University Natural Sciences, vol. 48, no. 12, December 2021 (WoS, Scopus, Q2)
Mahbuba Begum and Mohammad Shorif Uddin, "Towards the development of an effective image watermarking system," Security and Privacy (Wiley), November 2021 https://doi.org/10.1002/spy2.196  (WoS)
Md. Zahid Hasan, Mohammad Shorif Uddin, Mohammad Shahidul Islam, "An expert system for selecting optimal cloud-service provider," International Journal of Information Technology, (Springer), October 2021  https://doi.org/10.1007/s41870-021-00822-8 (Scopus, Q2)
Md. Al Mamun, Mohammad Shorif Uddin, "A Survey on a Skin Disease Detection System," International Journal of Healthcare Information Systems and Informatics (IGI Global), Vol. 16(4), No. 35, 2021 https://doi.org/10.4018/IJHISI.20211001.oa35 (WoS, Scopus, Q3)
Tarek Habib, Md. Jueal Mia, Mohammad Shorif Uddin, Faruk Ahmed,"An Explorative Analysis on the Machine-Vision-Based Disease Recognition of Three Available Fruits of Bangladesh," Vietnam Journal of Computer Science, (World Scientific/Springer), September 2021 https://doi.org/10.1142/S2196888822500087  (WoS, Scopus Q3)
Rafid Mostafiz, Khandaker Mohammad Mohi Uddin, Mohammad Shorif Uddin, Farhana Binte Hasan, Mohammad Motiur Rahman, "Diagnosis of diabetes: A machine learning paradigm using optimized features," Network Biology, vol. 11, no. 3, pp. 222-240, September 2021 (WoS)
Mahbuba Begum, Jannatul Ferdush, Mohammad Shorif Uddin, "Hybrid Robust Watermarking System Based on Discrete Cosine Transform, Discrete Wavelet Transform, and Singular Value Decomposition," Journal of King Saud University - Computer and Information Sciences, (Elsevier), July 2021 https://doi.org/10.1016/j.jksuci.2021.07.012   (WoS, Scopus, Q1)
Sk. Fahmida Islam, Morium Akter, Mohammad Shorif Uddin, "Design and implementation of an internet of things based low-cost smart weather prediction system," International Journal of Information Technology, (Springer)  July 2021 https://doi.org/10.1007/s41870-021-00732-9 (Scopus, Q2)
Md. Asadur Rahman, Anika Anjum, Md. Mahmudul Haque Milu, Farzana Khanam, Mohammad Shorif Uddin, Md. Nurunnabi Mollah, "Emotion recognition from EEG-based relative power spectral topography using convolutional neural network," Array, (Elsevier), 11, 100072, June 2021 https://doi.org/10.1016/j.array.2021.100072   (Scopus, Q1)
Jannatul Ferdush, Mahbuba Begum, Mohammad Shorif Uddin, "Chaotic Lightweight Cryptosystem for Image Encryption," Advances in Multimedia, Vol. 2021, Article ID 5527295 (Hindawi), May 2021 https://doi.org/10.1155/2021/5527295   (WoS, Scopus, Q3) 
Md. Sabab Zulfiker, Nasrin Kabir, Al Amin Biswas, Tahmina Nazneen, Mohammad Shorif Uddin, "An In-Depth Analysis of Machine Learning Approaches to Predict Depression," Current Research in Behavioral Sciences, (Elsevier), vol. 2, no. 100044, May 2021 https://doi.org/10.1016/j.crbeha.2021.100044  (Scopus, Q2)
Mahbuba Begum, Mohammad Shorif Uddin, "Implementation of Secured and Robust DFT-Based Image Watermark Through Hybridization with Decomposition Algorithm," SN Computer Science, (Springer), vol. 2, no. 221  April 2021 https://doi.org/10.1007/s42979-021-00608-6  (Scopus, Q2)
Kanija Muntarina, Sumaita Binte Shorif, Mohammad Shorif Uddin,  "Notes on edge detection approaches," Evolving Systems,  (Springer), March 2021 https://doi.org/10.1007/s12530-021-09371-8   (WoS, Scopus, Q2)
Mohammad Meraj Khan, Mohammad Shorif Uddin, Mohammad Zavid Parvez, Lutfur Nahar, "A Squeeze and Excitation ResNeXt-Based Deep Learning Model for Bangla Handwritten Compound Character Recognition," Journal of King Saud University - Computer and Information Sciences, (Elsevier), Vol. 34, pp. 3356-3364, 2022. https://doi.org/10.1016/j.jksuci.2021.01.021  (WoS, Scopus, Q1)
Fauzia Yasmeen and Mohammad Shorif Uddin, "An Efficient Watermarking Approach Based on LL and HH Edges of DWT–SVD," SN Computer Science, (Springer), vol. 2, no. 82, February 2021 https://doi.org/10.1007/s42979-021-00478-y   (Scopus, Q2)
Rafid Mostafiz, Mohammad Shorif Uddin, Nur-A. Alam, Md. Mahmodul Hasan, Mohammad Motiur Rahman, "MRI-based brain tumor detection using the fusion of histogram oriented gradients and neural features," Evolutionary Intelligence (Springer), January 2021 https://doi.org/10.1007/s12065-020-00550-1  (WoS, Scopus, Q2)
Rafid Mostafiz, Mohammad Shorif Uddin, Nur-A. Alam, Md. Mahfuz Reza, Mohammad Motiur Rahman, "Covid-19 Detection in Chest X-ray Through Random Forest Classifier using a Hybridization of Deep CNN and DWT Optimized Features," Journal of King Saud University - Computer and Information Sciences (Elsevier), December 2020. https://doi.org/10.1016/j.jksuci.2020.12.010 (WoS, Scopus, Q1)
Mohammad Reduanul Haque, Rubaiya Hafiz, Alauddin Al Azad, Yeasir Adnan, Sharmin Akter Mishu, Amina Khatun, Mohammad Shorif Uddin, "Crime Detection and Criminal Recognition to Intervene in Interpersonal Violence Using Deep Convolutional Neural Network With Transfer Learning," International Journal of Ambient Computing and Intelligence (IGI Global), 12(4), March 2021 https://doi.org/10.4018/IJACI.20211001.oa1 (WoS, Scopus, Q3)
Rubaiya Hafiz, Mohammad Reduanul Haque, Aniruddha Rakshit, Mohammad Shorif Uddin, "Image-Based Soft Drink Type Classification  and  Dietary  Assessment  System  Using  Deep  Convolutional  Neural  Network  with  Transfer Learning," Journal  of  King  Saud  University  -  Computer  and  Information  Sciences (Elsevier), Vol. 34, pp. 1775-1784, 2022. https://doi.org/10.1016/j.jksuci.2020.08.015  (WoS, Scopus, Q1)
Mahbuba Begum and Mohammad Shorif Uddin, "Analysis of Digital Image Watermarking Techniques through Hybrid Methods," Advances in Multimedia, (Hindawi), Vol. 2020, Article ID 7912690, https://doi.org/10.1155/2020/7912690 (WoS, Scopus, Q3)
Sushil K Paul,  S. Bouakaz, C M Rahman, Mohammad Shorif Uddin, "Component-based face recognition using statistical pattern matching analysis," Pattern Analysis and Applicatins, vol. 23, July 2020, (Springer), https://doi.org/10.1007/s10044-020-00895-4, WoS, Scopus, Q2)
Marjia Sultana, Tasniya Ahmed, Partha Chakraborti, Mahmuda Khatun, Rakib Hasan Riyad, Mohammad Shorif Uddin, "Object Detection using Template and HOG Feature Matching," International Journal of Advanced Computer Science and Applications, (SAI Organization), Vol. 11, No. 7, pp. 233-238, July 2020, https://dx.doi.org/10.14569/IJACSA.2020.0110730 (WoS, Scopus, Q3)
Md. Asadur Rahman, Farzana Khanam, Mohiuddin Ahmad, Mohammad Shorif Uddin, "Multiclass EEG signal classification utilizing Rényi min-entropy-based feature selection from wavelet packet transformation," Brain Informatics, Vol.  7:7, June 2020, (Springer), https://doi.org/10.1186/s40708-020-00108-y, Scopus, Q1)
Md. Zahid Hasan, Shakhawat Hossain, Mohammad Shorif Uddin, Mohammad Shahidul Islam, "A Generic Feature Extraction Approach for Dealing with Multiple Attribute Decision Analysis Problems under Risk and Uncertainty," Engineering, Technology & Applied Science Research, Vol. 10, No. 3, pp. 5775-5783, 2020, https://doi.org/10.48084/etasr.3537  (WoS)
R. Mostafiz, M. M. Rahman, Mohammad Shorif Uddin, "Gastrointestinal polyp classification through empirical mode decomposition and neural features," SN Applied Sciences Vol.  2, No. 1143, 2020 (Springer), https://doi.org/10.1007/s42452-020-2944-4 (WoS, Scopus, Q2)
Tarek Habib, Md. Jueal Mia, Mohammad Shorif Uddin, Faruk Ahmed, "An In-Depth Exploration of Automated Jackfruit Disease Recognition," Journal of King Saud University - Computer and Information Sciences, (Elsevier), vol. 34, pp. 1200-1209, 2022. https://doi.org/10.1016/j.jksuci.2020.04.018, (WoS, Scopus, Q1)
Mahbuba Begum and Mohammad Shorif Uddin, "Digital Image Watermarking Techniques: A Review," Information, Vol. 11, No. 110, 2020, (MDPI). https://doi.org/10.3390/info11020110 (WoS, Scopus, Q2)
Moushumi Zaman Bonny, Mohammad Shorif Uddin, "A Technique for Panorama-Creation using Multiple Images," International Journal of Advanced Computer Science and Applications, (SAI Organization), Vol. 11, No. 2, pp. 741-746, Feb. 2020. https://dx.doi.org/10.14569/IJACSA.2020.0110293 (WoS, Scopus, Q3) 
Md. Zahid Hasan, Shakhawat Hossain, Mohammad Shorif Uddin, Mohammad Shahidul Islam, "A Generic Approach for Weight Assignment to the Decision Making Parameters," International Journal of Advanced Computer Science and Applications (SAI Organization), Vol. 10, No. 11, pp. 512-519, Nov. 2019, https://dx.doi.org/10.14569/IJACSA.2019.0101170  (WoS, Scopus, Q3) 
Md. Asadur Rahman, Mohammad Shorif Uddin, Mohiuddin Ahmad, "Modeling and classification of voluntary and imagery movements for brain–computer interface from fNIR and EEG signals through convolutional neural network," Health Information Science and Systems (Springer), Vol. 7, No. 22, 2019, https://doi.org/10.1007/s13755-019-0081-5 (WoS, Scopus)
Md. Tarek Habib, Anup Majumder, A.Z.M. Jakaria, Morium Akter, Mohammad Shorif Uddin, Farruk Ahmed, “Machine vision-based papaya disease recognition,” Journal of King Saud University – Computer and Information Sciences 32 (2020) 300–309 (Elsevier), https://doi.org/10.1016/j.jksuci.2018.06.006  (WoS, Scopus, Q1) 
Masashi Yamaguchi, Hiroyuki Yamada, Kimitaka Higuchi, Yuta Yamamoto, Shigeo Arai, Kazuyoshi Murata, Yuko Mori, Hiromitsu Furukawa, M Shorif Uddin, and Hiroji Chibana, "High-voltage electron microscopy tomography and structome analysis of unique spiral bacteria from the deep sea," Microscopy (Oxford University Press), Vol. 65, pp. 1-7, (2016), https://doi.org/10.1093/jmicro/dfw016  (WoS, Scopus, Q2)
M. Motiur Rahman, Mithun Kumar PK, Mohammad Shorif Uddin, "Optimum Threshold Parameter Estimation of Bidimensional Empirical Mode Decomposition Using Fisher Discriminant Analysis for Speckle Noise Reduction," International Arab Journal of Information Technology, 12(5), 456-464, (2015) (WoS, Scopus, Q3)
Motiur Rahman, Mithun Kumar PK, Mohammad Shorif Uddin, "Optimum Threshold Parameter Estimation of Wavelet Coefficients using Fisher Discriminant Analysis for Speckle Noise Reduction," International Arab Journal of Information Technology, 11(6), 573-581 (2014) (WoS, Scopus, Q3)
Mohammad Shorif Uddin, Hwee Kuan Lee, Stephan Preibisch, Pavel Tomancak, "Restoration of uneven illumination in light sheet microscopy images," Microscopy and Microanalysis (Cambridge University Press), vol. 17, no. 4, pp. 607-613, (2011), https://doi.org/10.1017/S1431927611000262 (WoS, Scopus, Q2) 
Hwee Kuan Lee, Mohammad Shorif Uddin, S. Sankaran, S. Hariharan, Sohail Ahmed, “A field theoretical restoration method for images degraded by non-uniform light attenuation: An application for light microscopy,” Optics Express (Optical Society of America), vol. 17, no. 14, pp. 11294-11308, (2009), https://doi.org/10.1364/OE.17.011294 (WoS, Scopus, Q1)
Mohammad Shorif Uddin and T. Shioyama, "Detection of pedestrian crossing using bipolarity feature - an image- based technique," IEEE Transactions on Intelligent Transportation Systems, Vol. 6, No. 4, pp. 439-445, (2005), https://doi.org/10.1109/TITS.2005.858787 (WoS, Scopus, Q1)
Mohammad Shorif Uddin and T. Shioyama, "An image processing approach for the measurement of pedestrian crossing length using vector geometry," IEICE Transactions on Information and Systems, Vol. E88-D, No. 7, pp. 1546-1552, (2005), https://doi.org/10.1093/ietisy/e88-d.7.1546 (WoS, Scopus, Q3)
T. Shioyama and Mohammad Shorif Uddin, "Detection of pedestrian crossings with projective invariants from image data," Measurement Science and Technology (Institute of Physics, UK), Vol. 15, No. 12, pp. 2400-2405, (2004), https://doi.org/10.1088/0957-0233/15/12/008  (WoS, Scopus, Q2)
Mohammad Shorif Uddin, H. Inaba, Y. Itakura, Y. Yoshida, M. Kasahara, "Large motion estimation by gradient technique - application to debris flow velocity field," Physics and Chemistry of the Earth (Elsevier), Vol. 26, No. 9, pp. 633-638, (2001), https://doi.org/10.1016/S1464-1917(01)00060-5 (WoS, Scopus, Q2)
Mohammad Shorif Uddin, H. Inaba, Y. Itakura, Y. Yoshida, M. Kasahara, "Adaptive computer-based spatial filtering method for more accurate estimation of the surface velocity of debris flow," Applied Optics: Information Processing (Optical Society of America), Vol. 38, No. 32, pp. 6714-6721, (1999), https://doi.org/10.1364/ao.38.006714  (WoS, Scopus, Q2)
Mohammad Shorif Uddin, H. Inaba, Y. Itakura, M. Kasahara, "Estimation of the surface velocity of debris flow with computer-based spatial filtering," Applied Optics: Information Processing (Optical Society of America), Vol. 37, No. 26, pp. 6234-6239, (1998), https://doi.org/10.1364/ao.37.006234 (WoS, Scopus, Q2) 
Md. Abdur Rashid, Mohammad Shorif Uddin, “Legal, regulatory, and policy framework hypothesis testing in a proposed e-procurement implementation assessment model framework”, GSC Advanced Research and Reviews, Vol. 19, No. 2, pp. 219–225, May 2024. https://doi.org/10.30574/gscarr.2024.19.2.0185
Md. Abdur Rashid, Mohammad Shorif Uddin, “Cost and Time Efficiency Analysis of Manual and e-Procurement Systems in Roads and Highways Department: Tender Advertising Issue Perspective”, British Journal of Multidisciplinary and Advanced Studies, Vol. 5(1), pp. 1-7, January 2024, https://doi.org/10.37745/bjmas.2022.0387
Md. Abdur Rashid and Mohammad Shorif Uddin, "Process Improvement Hypothesis Testing in an e-Procurement Implementation Assessment Model Framework: A Case Study of Bangladesh’s Roads and Highways Division," British Journal of Multidisciplinary and Advanced Studies, vol. 4, no. 6, pp. 1–7, November 2023. https://doi.org/10.37745/bjmas.2022.0354 
Md. Abdur Rashid and Mohammad Shorif Uddin,  "Hypothesis Test on Boosting Competition in an eProcurement Implementation Assessment Model Framework: A Case Study on the Roads and Highways Division in Bangladesh," International Journal of Research in Engineering and Science (IJRES), Vol. 11(10), pp. 406–410, October 2023.
Md. Abdur Rashid and Mohammad Shorif Uddin,  "Efficiency Hypothesis Testing in an e-Procurement Implementation Assessment Model Framework: A Case Study of Bangladesh's Roads and Highways Division," World Journal of Advanced Research and Reviews, Vol. 20(1), pp. 79–85, October 2023. https://doi.org/10.30574/wjarr.2023.20.1.1852
Morium Akter, M. Abu Baker, Mohammad Shorif Uddin, "Smart Home Security System," Transactions on Engineering and Computing Sciences (TECS), vol. 11, no. 4, pp. 11–18, July 2023. https://doi.org/10.14738/tecs.114.14975
Md. Abdur Rashid and Mohammad Shorif Uddin,  "Comparing the Efficiency of Manual and Electronic Tender Document Preparation: Cost and Time Context," Intelligent Information Management, Vol. 14, No. 6, pp. 195-201, Nov 2022 https://doi.org/10.4236/iim.2022.146013 
Md. Abdur Rashid and Mohammad Shorif Uddin, "Time and Cost Efficiency Analysis of Manual and e-Procurement Systems in Roads and Highways Department: TEC Meeting Arrangement Perspective," European Journal of Computer Science and Information Technology, Vol.10, No.5, pp.32-40, 2022.
Md. Abdur Rashid and Mohammad Shorif Uddin,  "Tender Dropping Efficiency in the Roads and Highways Department of Bangladesh: A Cost and Time Context Comparison of Manual and E-procurement," Journal of Procurement & Supply Chain, Vol. 6, No. 1, pp. 29 - 36, 2022. https://doi.org/10.53819/81018102t4041
Md. Abdur Rashid and Mohammad Shorif Uddin, "Comparing the Cost and Time of Tender Opening Committee Report Preparation for Manual and E-Procurement Tenders in the Roads and Highways Department of Bangladesh," Open Journal of Applied Sciences, vol. 12, No. 3, pp. 336-345, March 2022. https://doi.org/10.4236/ojapps.2022.123024
Md. Abdur Rashid and Mohammad Shorif Uddin, "Analysis of a Conceptual Model and Assessment of the e-Procurement System in Bangladesh," Journal of Computer and Communications, vol. 9, no. 11, pp. 64-76, November 2021. https://doi.org/10.4236/jcc.2021.911005
Md. Al Mamun, Mohammad Shorif Uddin, "Hybrid Methodologies for Segmentation and Classification of Skin Diseases: A Study," Journal of Computer and Communications, vol. 9, no. 4, pp. 67-84, April 2021. https://doi.org/10.4236/jcc.2021.94005
Sk. Fahmida Islam, Md. Iqramul Hasan, Morium Akter, Mohammad Shorif Uddin, "Implementation and Analysis of an IoT-Based Home Automation Framework," Journal of Computer and Communications, vol. 9, no. 3, pp. 143-157, March 2021. https://doi.org/10.4236/jcc.2021.93011
Mahbuba Begum, Mohammad Shorif Uddin, "Multiple Image Watermarking with Discrete Cosine Transform," Journal of Computer and Communications, vol. 9, no. 3, pp. 88-94, March 2021. https://doi.org/10.4236/jcc.2021.93006 
Md. Mafiul Hasan Matin, Amina Khatun, Md. Golam Moazzam, Mohammad Shorif Uddin, "An Efficient Disease Detection Technique of Rice Leaf Using AlexNet," Journal of Computer and Communications, vol. 8, no. 12, pp. 49-57, December 2020. https://doi.org/10.4236/jcc.2020.812005
Moushumi Zaman Bonny, Mohammad Shorif Uddin, "A Hybrid-Binarization Approach for Degraded Document Enhancement," Journal of Computer and Communications, vol. 8, no. 12, pp. 1-11, December 2020. https://doi.org/10.4236/jcc.2020.812001 
Amina Khatun, Mohammad Reduanul Haque, Rabeya Basri, Mohammad Shorif Uddin, "Single Image Dehazing: An Analysis on Generative Adversarial Network," Journal of Computer and Communications, Vol. 8, pp.127-137, April 2020. https://doi.org/10.4236/jcc.2020.84010
Tasnim Ahmed, Mst. Shahnaj Parvin, M. Reduanul Haque, Mohammad Shorif Uddin, “Lung Cancer Detection Using CT Image Based on 3D Convolutional Neural Network,” Journal of Computer and Communications, Vol. 8, pp. 35-42, March 2020. https://doi.org/10.4236/jcc.2020.83004 
Saikat Goswami, Mohammad Shorif Uddin, Maisha Rowshon Islam, "Implementation of Active Learning for ICT Education in Schools," International Journal of Innovative Science and Research Technology, vol. 5, no. 9, pp. 455-459, September 2020.
Md. Tariqulhasan Fazle Rabbi,  S. M. Tanjilur Rahman,  Prokash Biswash,  Jinsul Kim,  Alamin Sheikh,  Aloke Kumar Saha,  Mohammad Shorif Uddin, "Handwritten Signature Verification Using CNN with Data Augmentation," Journal of Contents Computing (Digital Contents Society), Vol.1, No.1, pp. 25-37, Dec. 2019. https://dx.doi.org/10.9728/jcc.2019.12.1.1.25
Md. Abdur Rashid and Mohammad Shorif Uddin, "Factors Influencing Public Sector e-Procurement System in Bangladesh: From a Critical Literature Review to a Conceptual Framework," IOSR Journal of Engineering (IOSRJEN), vol. 09, no. 11, 2019, pp. 19-27, Nov. 2019.
Mohammad Reduanul Haque, Shifat Jaman, Md Golam Saklayen, Md. Mohsin Khondoker, Abu Bakkar Siddik, Umme Sara, Mohammad Shorif Uddin, “Towards the development of an energy-efficient smart home through IoT,” International Journal of Advanced Technology and Engineering Exploration, Vol 6(58), pp. 208-216, Sept. 2019, http://dx.doi.org/10.19101/IJATEE.2019.650052  
Md. Al Mamun, Morium Akter, Mohammad Shorif Uddin, "A Survey on Matching of Shoeprint with Reference Footwear in Forensic Study," Journal of Computer and Communications, Vol. 7, pp. 1-5, September 2019, https://doi.org/10.4236/jcc.2019.79002
Md. Golam Moazzam, M. Reduanul Haque, Mohammad Shorif Uddin, “Image-Based Vehicle Speed Estimation,” Journal of Computer and Communications, Vol. 7, pp. 1-5, May 2019, https://doi.org/10.4236/jcc.2019.76001
Md. Golam Moazzam, M. Reduanul Haque, Mohammad Shorif Uddin, "Image-Based Vehicle Recognition using Neural Network," International Journal of Computer Sciences and Engineering, Vol.7, No. 5, pp.948-954, May 2019, https://doi.org/10.26438/ijcse/v7i5.948954 
Umme Sara, Morium Akter, Mohammad Shorif Uddin, “Image quality assessment through FSIM, SSIM, MSE and PSNR- A comparative study,” Journal of Computer and Communications, Vol. 7, pp. 8-18, March 2019, https://doi.org/10.4236/jcc.2019.73002
Aditi Sarker, Morium Akter, Mohammad Shorif Uddin, “Simulation of hazy image and validation of haze removal technique,” Journal of Computer and Communications, Vol. 7, No. 2, pp. 62-72, (February 2019), https://doi.org/10.4236/jcc.2019.72005 
Morium Akter, Liton Jude Rozario, Mohammad Shorif Uddin, “Gait Recognition for Security and Surveillance System- A Review,” International Journal of Computer Science and Information Security, Vol. 16, No. 6, pp. 143-149, (June 2018).
Moushumi Zaman Bonny and Mohammad Shorif Uddin, “Image Stitching Algorithm: An Optimization between Correlation-Based and Feature-Based Method,” International Journal of Computer Science and Information Security, Vol. 16, No. 6, pp. 150-157, (June 2018).
Amatul Bushra Akhi, Farzana Akter, Tania Khatun, M Shorif Uddin, “Recognition and Classification of Fast Food Images,” Global Journal of Computer Science and Technology: Graphics and Vision, vol. 18, No. 1, (2018).
Md. Golam Moazzam, Tanzila Rahman, Mohammad Shorif Uddin, “Effective Techniques for Reduction of Impulse, Gaussian and Speckle Noises,” International Journal of Computer Science and Information Security, Vol. 14, No. 7, pp. 589-604, (July 2016).
Sushil Kumar Paul, Mohammad Shorif Uddin, Saida Bouakaz, “Component Based Face Recognition using Feature Matching through Hu Moment Invariants,” International Journal of Computer Science and Information Security, Vol. 14, No. 6, pp. 589-604, (June 2016).
Liton J. Rozario, Tanzila Rahman, Mohammad Shorif Uddin “Segmentation of the Region of Defects in Fruits and Vegetables,” International Journal of Computer Science and Information Security, Vol. 14, No. 5, pp. 399-406, (May 2016).
Dewan Md. Mostafezur Rahman, Abu Sayed Md. Mostafizur Rahaman, Md. Imdadul Islam, Mohammad Shorif Uddin and Md. Akram Hossain, "Traffic Modeling of Mobile Cellular Network Using Combination of Limited and Unlimited User Groups," International Journal of Computer Science and Information Security, Vol. 14, No. 10, pp. 40-46, October 2016.
Dewan Md Mostafezur Rahman, Md Imdadul Islam, Abu Sayed Md Mostafizur Rahaman, Mohammad Shorif Uddin, Md. Akram Hossain, "Resource Management of Mobile Communication System," International Journal of Advanced Engineering Research and Science vol. 3, no. 8,  pp. 72-76, August 2016. 
Liton Jude Rozario, Mohammad Reduanul Haque, Md. Ziarul Islam, Mohammad Shorif Uddin, "Vehicle Classification Using Gabor Filter and Support Vector Machine," Artificial Intelligence and Applications, Vol. 2, No. 1, pp. 1-7, (Feb. 2015).
Tanzila Rahman, Liton J. Rozario, Mohammad Shorif Uddin “An Efficient Approach for Removal of Impulse Noise from Highly Corrupted Images,” SOP Transactions on Signal Processing, Vol. 2, No. 1, pp. 28-35, (Jan. 2015).
Mohammad Shorif Uddin, Akkas Ali, M. Motiur Rahman, Mithun Kumar, Gauhar Arefin, "Speckle Noise Reduction fromUltrasound Images using Principal Component Analysis in Nonlinear Diffusion Domain," Jahangirnagar University Journal of Science, Vol. 37, No. 1, pp. 105-115, (2014).
Sushil Kumar Paul, Mohammad Shorif Uddin, Saida Bouakaz, “Face Recognition using Weighted Facial Feature Values of Eyes, Nostrils and Mouth Areas,” Journal of Computer Science and Software Applications, Vol. 1, No. 2, pp. 78-97, (Dec. 2014).
Morium Akter, Mohammad Shorif Uddin, Md. Atiqul Islam, “A Mobile-Based System for Management of Hypertension with Diabetes,” Journal of Computer Science and Software Applications, Vol. 1, No. 2, pp. 98-107, (Dec. 2014).
Mahbuba Begum, Md. Golam Moazzam, Mohammad Shorif Uddin, "Quantitative Analysis on Robustness of FLD and PCA-based Face Recognition Algorithms" International Journal of Computer Applications, Vol. 99, No. 19, pp. 10-14, (Aug. 2014).
Liton Jude Rozario, Mohammad Reduanul Haque, Md. Ziarul Islam, Mohammad Shorif Uddin, "Quantitative Analysis of PCA, ICA, LDA and SVM in Face Recognition," International Journal of Computer, Information, Systems and Control Engineering Vol.8 No.9, pp. 1448-1451, (Sep. 2014).
Morium Akter and Mohammad Shorif Uddin, "A Review on Automated Diagnosis of Diabetic Retinopathy" International Journal of Aadvanced Computer Technology, Vol. 3, No. 10, pp. 1161-1166, (Oct. 2014).
Morium Akter and Mohammad Shorif Uddin, "Morphology-Based Exudates Detection in Diabetic Retinopathy" Advances in Biomedical Science and Engineering, Vol. 1, No. 1, pp. 43-53, (Sept. 2014).
Sonia Corraya and Mohammad Shorif Uddin, "Global Contrast Enhancement for Effective Medical Image Segmentation" ULAB Journal of Science and Engineering, ISSN: 2079-4398, vol. 4, pp. 17-22, (Nov. 2013).
Debashish Das, Mohammad Shorif Uddin, "Data mining and neural network techniques in stock market prediction: A Methodological review," International Journal of Artificial Intelligence & Applications, 4{1}, pp. 117-127, (Jan. 2013).
M. Motiur Rahman, Mithun Kumar PK, Abdul Aziz, M. G. Arefin, Mohammad Shorif Uddin, “Adaptive anisotropic diffusion filter for speckle noise reduction for ultrasound image,” Int. J. Convergence Computing, (Inderscience Publisher’s) Vol. 1, No.1, pp 50-59, (2013).
Mostofa Kamal Nasir, Mohammad Shorif Uddin, "Hand Written Bangla Numerals Recognition for Automated Postal System," IOSR Journal of Computer Engineering, vol. 8, no. 6, pp. 43-48, January 2013.
Mahbuba Ferdous, Mahmuda Ferdous, Mohammad Shorif Uddin, "Invisible Watermarking Technique for Copyright Protection," Journal of Imaging and Vision Research, ISSN: 2306-5613, Vol. 1, No. 2, pp. 2-6, (2012).
Sushil Kumar Paul, Mohammad Shorif Uddin, Saida Bouakaz, "Extraction of Facial Feature Points from CDF using Otsu Thresholding," Journal of Imaging and Vision Research, ISSN: 2306-5613, Vol. 1, No. 2, pp. 7-13, (2012).
Madeena Sultana, Sabrina Sharmin, Farhana Sabrina, Mohammad Shorif Uddin, "An Improved Approach for Localization of Text Regions from Complex Document Images," ULAB Journal of Science and Engineering, ISSN: 2079-4398, vol. 3, pp. 24-29, (2012).
Mohammad Shorif Uddin, Tanzila Rahman, Umme Sayma Busra, and Madeena Sultana, "Automated Extraction of Text from Images using Morphology Based Approach," International Journal of Electronics & Informatics, Vol. 1, No. 1, pp. 14-19, (2012).
Sushil Kumar Paul, Mohammad Shorif Uddin, Saida Bouakaz, "Extraction of Facial Feature Points Using Cumulative Histogram," IJCSI International Journal of Computer Science Issues, Vol. 9, Issue 1, No 3, pp. 44-51, (2012).
M. Motiur Rahman, Abdul Aziz, Mithun Kumar PK, M. A. Naim Uddin Rajiv, Mohammad Shorif Uddin, "An Optimized Speckle Noise Reduction Filter for Ultrasound Images using Anisotropic Diffusion Technique," International Journal of Imaging and Robotics, Vol. 8, No. 2, pp. 55-60, (2012).
M. Motiur Rahman, M. Azim, Mina, Mohammad Shorif Uddin, "Speckle Noise Reduction in Ultrasound Images by Wavelet Thresholding based on Subband Mean Difference," International Journal of Tomography and Statistics, Vol. 20, No. 2, pp. 91-97, (2012).
Madeena Sultana, Moushumi Zaman Bonny, Mohammad Shorif Uddin, "Video Text Extraction using Discrete Wavelet Transform," Jahangirnagar University Journal of Electronics and Computer Science, Vol. 13, pp. 5-10, (2012).
Mohammad Shorif Uddin, Madeena Sultana, Md. Ziarul Islam, "Fast Holographic Image Reconstruction using Graphics Processing Unit," ULAB Journal of Science and Engineering, ISSN: 2079-4398, vol. 2, pp.35-41, (2011).
M.N. Haque, Mohammad Shorif Uddin, "Accelerating Fast Fourier Transformation for Image Processing using Graphics Processing Unit," Journal of Emerging Trends in Computing and Information Sciences, ISSN 2079-8407, vol. 2, no. 8, pp. 367–375, (2011).
Mehnaz Tabassum and Mohammad Shorif Uddin, "Extraction of ROI in Geographical Map Image," Journal of Emerging Trends in Computing and Information Sciences (ISSN 2079-8407), vol. 2, No. 5, pp. 237-242, (2011).
M. Mosaddik Hasan, M. Motiur Rahman, Mohammad Shorif Uddin, "Extraction of 3D Heart Shape using CT Image," International Journal of Computing Technology, Vol. II, No. 1, (2011).
Mohammad Shorif Uddin and Morium Akter, “Development of a Knowledge-Based Diagnosis and Management System for Diabetes Mellitus through Web,” ULAB Journal of Science and Engineering, ISSN: 2079-4398, vol. 1, pp.37-41, (2010).
M. Motiur Rahman, Mohammad Shorif Uddin, M. Mosaddik Hasan, “3D Segmentation and Visualization of Left Coronary Arteries of Heart Using CT Images,” IJCA Special Issue on Computer Aided Soft Computing Techniques for Imaging and Biomedical Applications, pp. 88-92, (2010).
M. Motiur Rahman, Mohammad Shorif Uddin, M. Mosaddik Hasan, Ahmed Kamal “Effects of Different Structuring Elements in 3D Segmentation of Left-Coronary Arteries using CT Images," Essence Donetsk National University: Natural Sciences Journal, pp. 285-288, (2010).
M. Shahidul Islam, M. S. Islam, Mohammad Shorif Uddin,"Analysis of Odd Order Distortion in MachZehnder Modulator for CATV System," ULAB Journal of Science and Engineering, vol. 1, pp. 11-14, November 2010.
S. Ratna, M. A. Haqu, Mohammad Shorif Uddin, "Robust face recognition system in application to access control and payroll management," Journal of Dhaka International University, vol. 1, no. 1, pp. 154-160, (2009).
M. M. H. Chowdhury, Mohammad Shorif Uddin, M. A. Bhuiyan, "Fuzzy filtering supported stereo correspondence estimation for 3D scene reconstruction," Jahangirnagar University Journal of Science, vol. 32, no. 2, pp. 25-41, (2009).
M. Faisal Al Ameen and Mohammad Shorif Uddin, "An educational toolkit for artificial neural network," Journal of Electronics and Computer Science (Jahangirnagar University), vol. 8, pp. 11-17, (2007).
N. K. Siddika, M. Faisal Al Ameen, Mohammad Shorif Uddin, "An improved memory management-based flexible human health monitoring system," Journal of Electronics and Computer Science (Jahangirnagar University), vol.8, pp. 31-35, (2007).
Mohammad Shorif Uddin and T. Shioyama, "Towards an image-based road crossing system for the visually impaired," Memoirs of the Faculty of Engineering and Design, Kyoto Institute of Technology, Vol. 54, pp. 15-30, (2006).
Mohammad Shorif Uddin, "Fast estimation of stereo correspondence using window-based techniques," AIUB Journal of Science and Engineering, Vol. 1, No. 2, pp. 64-73, (2003).
Mohammad Shorif Uddin, H. Inaba, Y. Yoshida, Y. Itakura, M. Kasahara, "Velocity field estimation of debris flow by image sequence processing," Memoirs of the Faculty of Engineering and Design, Kyoto Institute of Technology, Vol. 49, pp. 79-91, (2000).
Md. Abdul Based, Rahat Kabir, A.B.M. Toufique-Ul Islam, Mohammad Shorif Uddin, “Development of an E-Voting Scheme through a Blockchain-Enabled Approach with Deep Hybrid Learning for Biometric Authentication,” IEEE 9th International Conference for Convergence in Technology (I2CT), Pune, India, 5-7 April 2024,  (IEEE Xplore), pp. 1-6, https://doi.org/10.1109/I2CT61223.2024.10543350
Md Abdul Based, Rahat Kabir, A.B.M. Toufique-Ul Islam, Mohammad Shorif Uddin, "Secure Transmission of Ballots Using Blind Signature for Electronic Voting," IEEE International Conference on Information Technology, Electronics and Intelligent Communication Systems (ICITEICS 2024 ), Bangalore, India, 28-29 June 2024,  (IEEE Xplore), pp. 1-6, https://doi.org/10.1109/ICITEICS61368.2024.10625521
Kamelia Zaman Moon, Umma Salma, Mohammad Shorif Uddin, "BERT-Based Personalized Course Recommendation System from Online Learning Platform," 6th International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT-2024), Dhaka, Bangladesh, 2-4 May 2024, (IEEE Xplore), pp. 980-985.  https://doi.org/10.1109/ICEEICT62016.2024.10534490
Fauzia Yasmeen, Mahbuba Begum, Mohammad Shorif Uddin, "A Hybrid Watermarking Technique Based on LH-HL Subbands of DWT and SVD," Proceedings of International Conference on Machine Intelligence and Emerging Technologies (MIET 2022), 23-25 September 2022, Noakhali, Bangladesh, (LNICST, Vol. 490,  Springer), pp. 1-14, https://doi.org/10.1007/978-3-031-34619-4_40
Natasha Tanzila Monalisa, Shinthi Tasnim Himi, Kohinur Parvin and Mohammad Shorif Uddin, "Shanketik: Revolutionizing Communication for the Deaf and Mute - A Reinforcement Learning-Enhanced Bangla AAC Application," International Conference on Computer and Information Technology (ICCIT 2023), Cox's Bazar, Bangladesh, 13-15 December 2023, (IEEE Xplore), pp. 1-5,  https://doi.org/10.1109/ICCIT60459.2023.10441410
Mahbuba Begum, Mohammad Shorif Uddin, "Notes on Image Watermarking and Steganography," Proceedings of International Conference on Information and Communication Technology for Development (ICICTD 2022), 29-30 July 2022, Khulna, Bangladesh, (Data-driven Studies on Data-Driven and Industrial Computing, Springer), pp. 1-14, https://doi.org/10.1007/978-981-19-7528-8_1
A. Raihan, M. Z. H. Monju, M. M. Hasan, M. T. Habib, M. I. Jabiullah, Mohammad Shorif Uddin, "CNN Modeling for Recognizing Local Fish," International Conference on Computer and Information Technology (ICCIT 2021) 18-20 December 2021, Dhaka, Bangladesh, (IEEE Xplore), https://doi.org/10.1109/ICCIT54785.2021.9689898 
Sumaita Binte Shorif, Sadia Afrin, Anup Majumder, Mohammad Shorif Uddin, "Computer Vision-Based Algorithms on Zebra Crossing Navigation," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2021), 23-24 October 2021, New Delhi, India, (Algorithms for Intelligent Systems, Springer), pp. 319-328. https://doi.org/10.1007/978-981-19-0332-8_23
Kaniz Fatema, Md. Awlad Hossen Rony, Kazi Mumtahina Puspita, Md. Zahid Hasan, Mohammad Shorif Uddin, "Deep Learning-Based Lentil Leaf Disease Classification," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2021), 23-24 October 2021, New Delhi, India, (Algorithms for Intelligent Systems, Springer), pp. 427-443. https://doi.org/10.1007/978-981-19-0332-8_32
Md. Biplob Hosen, Nusrat Jahan Farin, Mehrin Anannya, Khadija Islam, Mohammad Shorif Uddin, "Service Quality Analysis for Ride-sharing Services: PATHAO," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2021), 23-24 October 2021, New Delhi, India, (Algorithms for Intelligent Systems, Springer), pp. 597-611. https://doi.org/10.1007/978-981-19-0332-8_44
Shakhawat Hossain, Md Zahid Hasan, Muhammed J. A. Patwary, Mohammad Shorif Uddin, "An Expert System to Determine Systemic Lupus Erythematosus under Uncertainty," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2020), 20-21 November 2020, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 130-143. https://doi.org/10.1007/978-981-16-0586-4_10
Md Zahid Hasan, Shakhawat Hossain, Mohammad Shorif Uddin, Md. Mehadi Hassan, Martina Chakma, "A Genetic Algorithm Based Optimal Train Route Selection Model," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2020), 20-21 November 2020, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 495-507. https://doi.org/10.1007/978-981-16-0586-4_40
Md Zahid Hasan, Shakhawat Hossain, K. M. Zubair Hasan, Mohammad Shorif Uddin, Md. Ehteshamul Alam, "Fuzzy Rule-based KNN for Rainfall Prediction: A case Study in Bangladesh," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2020), 20-21 November 2020, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 509-524. https://doi.org/10.1007/978-981-16-0586-4_41
Mohammad Reduanul Haque, Rubaiya Hafiz, Mohammad Zahidul Islam, Amina Khatun, Morium Akter, Mohammad Shorif Uddin, "Handwritten Indic Digit Recognition using Deep Hybrid Capsule Network," Proc. of International Joint Conference on Advances in Computational Intelligence (IJCACI 2020), 20-21 November 2020, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 539-547. https://doi.org/10.1007/978-981-16-0586-4_43
Mohammad Reduanul Haque, Md. Gausul Azam, Sarwar Mahmud Milon, Md. Shaheen Hossain, Md. Al-Amin Molla, Mohammad Shorif Uddin, "Quantitative Analysis of Deep CNNs for Multilingual Handwritten Digit Recognition," Proceedings of International Conference on Trends in Computational and Cognitive Engineering, 17-18 December 2020, Dhaka, Bangladesh (Advances in Intelligent Systems and Computing, Springer), vol. 1309, https://doi.org/10.1007/978-981-33-4673-4_2
Md. Al Mamun, Mohammad Shorif Uddin, "A Comparative Study Among Segmentation Techniques for Skin Disease Detection Systems," Proceedings of International Conference on Trends in Computational and Cognitive Engineering, 17-18 December 2020, Dhaka, Bangladesh (Advances in Intelligent Systems and Computing, Springer), vol 1309, https://doi.org/10.1007/978-981-33-4673-4_14
Rabeya Basri, M. Reduanul Haque, Morium Akter, Mohammad Shorif Uddin, "Bangla Handwritten Digit Recognition Using Deep Convolutional Neural Network," International Conference Computing Advancements (ICCA 2020), ACM, January 10-12, 2020, Dhaka, Bangladesh (ACM Digital Library). https://doi.org/10.1145/3377049.3377077
Moushumi Zaman Bonny and M. Shorif Uddin, "Degraded Document Enhancement through Binarization Techniques," International Conference on Sustainable Technologies for Industry 4.0 (STI 2019, 24-25 December 2019, Dhaka, Bangladesh), (IEEE Xplore), https://doi.org/10.1109/STI47673.2019.9068099
Morium Akter,  Jannatul Ferdous, Mahmuda Najnin Eva, Sumaita Binte Shorif, Sk. Fahmida Islam and M. Shorif Uddin, "Vehicle Detection and Its Speed Measurement," Proc. of International Conference on Advances in Energy Management (ICAEM 2019), 20-21 December 2019, Jodhpur, India, (Algorithms for Intelligent Systems, Springer), https://doi.org/10.1007/978-981-15-8820-4_9
Md. Zahid Hasan, Shakhawat Hossain, M. Shorif Uddin and M. Shahidul Islam, “Sources and Impact of Uncertainty on Rule-Based Decision Making Approaches,” Proc. of International Joint Conference on Computational Intelligence (IJCCI 2019), 25-26 October 2019, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 299-308, https://doi.org/10.1007/978-981-15-3607-6_24
Md. Zahid Hasan, Shakhawat Hossain, M. Shorif Uddin and M. Shahidul Islam, “An Optimized Pruning Technique for Handling Uncertainty in Decision Making Process,” Proc. of International Joint Conference on Computational Intelligence (IJCCI 2019), 25-26 October 2019, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 467-475, https://doi.org/10.1007/978-981-15-3607-6_37
Md. Tarek Habib, Md. Robel Mia, Md. Jueal Mia, M. Shorif Uddin and Farruk Ahmed, “A Computer Vision Approach for Jackfruit Disease Recognition,” Proc. of International Joint Conference on Computational Intelligence (IJCCI 2019), 25-26 October 2019, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 343-353, https://doi.org/10.1007/978-981-15-3607-6_28
Md. Sabab Zulfiker, Nasrin Kabir, Hafsa Moontari Ali,  M. Reduanul Haque, Morium Akter and M. Shorif Uddin, “Sentiment Analysis Based on Users' Emotional Reactions about Ride-sharing Services on Facebook and Twitter,” Proc. of International Joint Conference on Computational Intelligence (IJCCI 2019), 25-26 October 2019, Dhaka, Bangladesh, (Algorithms for Intelligent Systems, Springer), pp. 397-408, https://doi.org/10.1007/978-981-15-3607-6_32
Nusrat Jahan Farin, Morium Akter, Mohammad Shorif Uddin, "Data Mining Techniques for Predicting User Interest in Facebook Pages: A Comparison," International Conference on Advances in Science, Engineering and Robotics Technology (ICASERT 2019), May 3-5, 2019, Dhaka, Bangladesh (IEEE Xplore), https://doi.org/10.1109/ICASERT.2019.8934618
Md. Tarek Habib, Anup Majumder, Rabindra Nath Nandi, Farruk Ahmed, M. Shorif Uddin, "A Comparative Study of Classifiers in the Context of Papaya Disease Recognition," Proc. of International Joint Conference on Computational Intelligence (IJCCI 2018), 14-15 December 2018, Dhaka, Bangladesh, pp. 417-429, (Algorithms for Intelligent Systems, Springer), https://doi.org/10.1007/978-981-13-7564-4_36
M Shorif Uddin, Bishal Gautam, Aditi Sarker, Morium Akter, M Reduanul Haque, “Image-Based Automated Haze Removal Using Dark Channel Prior,” IEEE Region 10 Humanitarian Technology Conference (R10-HTC), 21-23 December 2017, Dhaka, Bangladesh, pp.412-415, (IEEE Xplore), https://doi.org/10.1109/R10-HTC.2017.8288987
Marjia Sultana, Afrin Haider, M. Shorif Uddin, “Analysis of data mining techniques for heart disease prediction,” International Conference on Electrical Engineering and Information Communication Technology (ICEEICT), 22-24 September 2016, Dhaka, Bangladesh, pp. 1-5, (IEEE Xplore), https://doi.org/10.1109/CEEICT.2016.7873142
Sayed Md. Fahim Fahad and M. Shorif Uddin, “Cloud-based solution for improvement of response time of MySQL RDBMS,” International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.7-10, (IEEE Xplore), https://doi.org/10.1109/IWCI.2016.7860329
Md. Tarek Habib; Shaon B. Shuvo; M. Shorif Uddin; Farruk Ahmed, “Automated textile defect classification by Bayesian classifier based on statistical features,”International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.101-105, (IEEE Xplore), https://doi.org/10.1109/IWCI.2016.7860347
Narayan R. Chakraborty; M. Taifur Rahman; Md. Ekhlasur Rahman; M. Shorif Uddin, “Generation and verification of digital signature with two factor authentication,” International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.131-135, (IEEE Explore), https://doi.org/10.1109/IWCI.2016.7860353
Rubaiya Hafiz; Saiful Islam; Roksana Khanom; Mohammad Shorif Uddin, “Image based drinks identification for dietary assessment,” International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.192-197, (IEEE Xplore), https://doi.org/10.1109/IWCI.2016.7860364
Moushumi Zaman Bonny and M. Shorif Uddin, “Feature-based image stitching algorithms,” International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.198-203, (IEEE Xplore), https://doi.org/10.1109/IWCI.2016.7860365
Nusrat J. Farin; Md. Nur A. A. Rimon; Sifat Momen; M. Shorif Uddin; Nafees Mansoor, “A framework for dynamic vehicle pooling and ride-sharing system,” International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.204-208, (IEEE Xplore), https://doi.org/10.1109/IWCI.2016.7860366
M. Reduanul Haque; Md. Golam Moazzam; Saiful Islam; Rony Das; M. Shorif Uddin, “Vehicle speed determination from video streams using image processing” International Workshop on Computational Intelligence (IWCI), 12-13 December 2016, Dhaka, Bangladesh, pp.252-255, (IEEE Xplore), https://doi.org/10.1109/IWCI.2016.7860375
Taimur Islam, Ataur Rahman Bappy,Tanzila Rahman, and Mohammad Shorif Uddin, “Filtering Political Sentiment in Social Media from Textual Information,” International Conference on Informatics, Electronics and Vision (ICIEV 2016), 13-14 May 2016, Dhaka, Bangladesh, (IEEE Xplore), https://doi.org/10.1109/ICIEV.2016.7760084
Mohammad Shorif Uddin, Pronaya Prosun Das, Md. Shamim Ahmed Roney, “Image-Based Approach for the Detection of Counterfeit Banknotes of Bangladesh,” International Conference on Informatics, Electronics and Vision (ICIEV 2016), 13-14 May 2016, Dhaka, Bangladesh, (IEEE Xplore), https://doi.org/10.1109/ICIEV.2016.7760162
Tanzila Rahman, M. Reduanul Haque, Liton J. Rozario and M. Shorif Uddin, “Gaussian Noise Reduction in Digital Images Using a Modified Fuzzy Filter,” Proceedings of International Conference on Computer and Information Technology (ICCIT 2014), Dhaka, Bangladesh, 22-23 December 2014, (IEEE Xplore), https://doi.org/10.1109/ICCITechn.2014.7073143
Morium Akter, M. Shorif Uddin and Mahmudul Hasan Khan, “Morphology-based exudates detection from color fundus images in diabetic retinopathy,” International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT 2014), 10-12 April 2014, Dhaka, Bangladesh, (IEEE Xorple), https://doi.org/10.1109/ICEEICT.2014.6919124
Tanzila Rahman and M. Shorif Uddin, “Removal of High Density Impulse Noise from Color Images Using an Adaptive Fuzzy Filter,” International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT 2014), 10-12 April 2014, Dhaka, Bangladesh, (IEEE Xplore), https://doi.org/10.1109/ICEEICT.2014.6919165
Sushil Kumar Paul, M. Shorif Uddin, Saida Bouakaz, "Face Recognition using Eyes, Nostrils and Mouth Features," 16th Int'l Conf. Computer and Information Technology, 8-10 March 2014, Khulna, Bangladesh, pp. 117-120, (IEEE Xplore), https://doi.org/10.1109/ICCITechn.2014.6997378
Madeena Sultana, M. Shorif Uddin, Farhana Sabrina, "High Density Impulse Denoising by a Novel Adaptive Fuzzy Filter," IEEE/OSA International Conference on Informatics, Electronics & Vision, (May 17-18, 2013, Dhaka, Bangladesh), (IEEE Xplore), https://doi.org/10.1109/ICIEV.2013.6572536
Tanzila Rahman and M. Shorif Uddin, "Speckle Noise Reduction and Segmentation of Kidney Regions From Ultrasound Image,"  IEEE/OSA International Conference on Informatics, Electronics & Vision, (May 17-18, 2013, Dhaka, Bangladesh), (IEEE Xplore), https://doi.org/10.1109/ICIEV.2013.6572601
M. Motiur Rahman, Mithun Kumar PK, B. Borucki, K. S. Nowinski, M. Shorif Uddin, "Speckle noise reduction of Ultrasound images Using Extra-Energy Reduction function," IEEE/OSA International Conference on Informatics, Electronics & Vision, (May 17-18, 2013, Dhaka, Bangladesh), (IEEE Xplore), https://doi.org/10.1109/ICIEV.2013.6572554
M. Motiur Rahman, Mithun Kumar PK, Gauhar Arefin, M. Shorif Uddin, "Speckle Noise Reduction from Ultrasound Images Principal Component Analysis with Bit Plane Slicing and Nonlineear Diffusion Method," Proceedings of International Conference on Computer and Information Technology (ICCIT 2012), Chittagong, Bangladesh, 22-24 December 2012, (IEEE Xplore), https://doi.org/10.1109/ICCITechn.2012.6509760
M. Shorif Uddin, Madeena Sultana, Tanzila Rahman, and Umme Sayma Busra, "Extraction of Texts from a Scene Image using Morphology Based Approach," IEEE/OSA International Conference on Informatics, Electronics & Vision, (May 18-19, 2012, Dhaka, Bangladesh), pp. 876-880, (IEEE Xplore), https://doi.org/10.1109/ICIEV.2012.6317406 
Racy Gomes, M. Shorif Uddin, Sazzad Hossain, "Vision-Based Recognition of Identity Card in Mobile Platform," IEEE/OSA International Conference on Informatics, Electronics & Vision, (May 18-19, 2012, Dhaka, Bangladesh), pp. 128-132, (IEEE Xplore), https://doi.org/10.1109/ICIEV.2012.6317497
Sushil Kumar Paul, M. Shorif Uddin, Saida Bouakaz, "Extraction of Facial Feature Points Using Cumulative Distribution Function by Varying Single Threshold Group," IEEE/OSA International Conference on Informatics, Electronics & Vision, (May 18-19, 2012, Dhaka, Bangladesh), pp. 806-811, (IEEE Xplore), https://doi.org/10.1109/ICIEV.2012.6317366 
Sushil Kumar Paul, Saida Bouakaz, M. Shorif Uddin, "Automatic Adaptive Facial Feature Extraction Using CDF Analysis," International Conference on Digital Information and Communication Technology and its Applications, (DICTAP 2011, Dijon, France, June 21-23), Communications in Computer and Information Science (CCIS), vol. 166, pp. 327-338, 2011, (Springer), https://doi.org/10.1007/978-3-642-21984-9_28
M.N. Haque, M.S. Uddin, M. Abdullah-Al-Wadud, Y. Chung, "Fast Reconstruction Technique for Medical Images using Graphics Processing Unit", International Conference on Signal Processing, Image Processing and Pattern Recognition (SIP 2011, Dec 8-10, 2011, Jeju Island, Korea), Communications in Computer and Information Science (CCIS), vol. 260, pp. 300-309, 2011, (Springer), https://doi.org/10.1007/978-3-642-27183-0_32
Madeena Sultana, M. Shorif Uddin, Nurul Muntasir Mamun, Maaruf Ali, "A GPU Based Efficient Trademark Retrieval Technique using a Weighted Combination of Multiple Image Features," First Global Conference on Communication, Science & Information Engineering (CCSIE 2011), London, UK, 25-27 July, 2011. 
Madeena Sultana and M. Shorif Uddin, “Trademark recognition using a weighted combination of different image features,” 3rd International Conference on Machine Vision (ICMV 2010, 28-30 December, 2010, Hong Kong), Published in International Journal of Computer Theory and Engineering vol. 4, no. 6, pp. 1035-1038, 2012 https://doi.org/10.7763/IJCTE.2012.V4.633
Rezwan Akhter, M. Hasanuzzaman Bhuiyan, M. Shorif Uddin, “Extraction of Words from the National ID Cards for Automated Recognition,” International Conference on Graphic and Image Processing (ICGIP 2010, Dec. 4 - 5, 2010, Manila, Philippines), Proceedings of the SPIE, Volume 8285, id. 828521 (2011), (SPIE) 
https://doi.org/10.1117/12.913478
Morium Akter, M. Shorif Uddin, Aminul Haque, "Diagnosis and Management of Diabetes Mellitus through a Knowledge-Based System," Proc. of International Conference on Biomedical Engineering (ICBME 2008), Singapore, 3-6 December 2008 (Springer), pp. 1000-1003, https://doi.org/10.1007/978-3-540-92841-6_247 
Morium Akter, M. Shorif Uddin, Aminul Haque, "Design of an Expert System for the Management of Hypertension in Patients with Diabetes Mellitus," Proc. of  International Conference on Electronics, Computer and Communication (ICECC 2008), pp. 524-527, Rajshahi, Bangladesh, 27-29 June 2008.
Nafisa Khundker, M. A. Arif, M. Shorif Uddin, "Development of a Bangla handwritten postal code recognition system using artificial neural network," Proc. of BES National Conference on Electronics, Information and Telecommunication, pp. 147, (Rajshahi University, Rajshahi, Bangladesh, 29-30 June, 2007).
Nusrat Jahan, Rofiqun Nahar, M. Shorif Uddin, "Web camera based face recognition system for personnel management," Proc. of BES National Conference on Electronics, Information and Telecommunication, pp. 149,(Rajshahi University, Rajshahi, Bangladesh, 29-30 June, 2007).
M. Shorif Uddin and T. Shioyama, "Detection of pedestrian crossing and measurement of crossing length - an image-based navigational aid for blind people," Proc. of IEEE International Conference on Intelligent Transportation Systems (ITSC 2005), pp. 578-583, Vienna, Austria, 13-16 September 2005, (IEEE Xplore), https://doi.org/10.1109/ITSC.2005.1520112 
M. Shorif Uddin and T. Shioyama, "Robust zebra-crossing detection using bipolarity and projective invariant," International Symposium on Signal Processing and its Applications (ISSPA 2005), pp. 571-574, Sydney, Australia, 28-31 August 2005, (IEEE Xplore), https://doi.org/10.1109/ISSPA.2005.1581002
M. Shorif Uddin and T. Shioyama, "Bipolarity- and projective invariant-based zebra-crossing detection for the visually impaired," Proc. of IEEE Workshop on Computer Vision Applications for the Visually Impaired (in conjunction with CVPR 2005), San Diego, USA, 20 June 2005, (IEEE Xplore), https://doi.org/10.1109/CVPR.2005.423
M. Shorif Uddin and T. Shioyama, "Measurement of the length of pedestrian crossings - a navigational aid for blind people," Proc. of IEEE International Conference on Intelligent Transportation Systems (ITSC 2004), pp. 690-695, Washington, USA, 3-6 October 2004, (IEEE Xplore), https://doi.org/10.1109/ITSC.2004.1398985
M. Shorif Uddin and T. Shioyama, "Measurement of the length of pedestrian crossings from image data,"Proceedings of SPIE, Vol. 5578, pp. 498-508, Ottawa, Canada, 27-29 September 2004, (SPIE) https://doi.org/10.1117/12.567168
M. Shorif Uddin and T. Shioyama, "Measurement of the length of pedestrian crossings through image processing," Proc. of International Conference on Computer Vision and Graphics (ICCVG 2004), pp. 51-56, Warsaw, Poland, 22-24 September 2004, (Springer), https://doi.org/10.1007/1-4020-4179-9_9 
T. Shioyama, M. Shorif Uddin, Y. Kawai, "Vehicle detection using Gabor filters and affine moment invariants from image data," Proc. of International Conference on Computer Vision and Graphics (ICCVG 2004), pp. 197-202, Warsaw, Poland, 22-24 September 2004, (Springer), https://doi.org/10.1007/1-4020-4179-9_28 
M. Shorif Uddin and T. Shioyama, "Measurement of pedestrian crossing length using vector geometry - an image based technique," Proc. of IEEE International Midwest Symposium on Circuits and Systems (MWSCAS 2004), Vol. I, pp. 229-232, Hiroshima, Japan 25-28 July 2004, (IEEE Xplore), https://doi.org/10.1109/MWSCAS.2004.1353968 
M. Shorif Uddin, Y. Yoshida, T. Shioyama, "Computer vision-based air bubble detection in gas pipe joints, "Proceedings of International Conference on Computer and Information Technology (ICCIT 2003), pp.401-404, Dhaka, Bangladesh, 19-21 December 2003. 
M. Shorif Uddin, T. T. Son, S. Mita, "Fast implementation of window-based methods for stereo correspondence," Proceedings of SPIE, Vol. 5203, pp. 590-598, San Diego, USA, 2-6 August 2003, (SPIE) https://doi.org/10.1117/12.501456 
M. Shorif Uddin, H. Inaba, Y. Yoshida, Y. Itakura, "Debris flow velocity estimation: a comparison between gradient-based method and cross-correlation method," Proceedings of SPIE, Vol. 4667, pp. 130-138, San Jose, CA, USA, 20-24 January 2002, (SPIE) https://doi.org/10.1117/12.467974 
M. Shorif Uddin, H. Inaba, Y. Yoshida, Y. Itakura, "Debris Flow Velocity Estimation by Cross-Correlation Method," Proceedings of International Conference on Computer and Information Technology (ICCIT 2001), pp. 1-5, Dhaka, Bangladesh, 28-29 December 2001.
M. Shorif Uddin, H. Inaba, Y. Yoshida, Y. Itakura, "Notes on gradient-based methods for estimation of large motion in image sequences," Proceedings of the IEEE International Conference on Electrical and Computer Engineering (ICECE 2001), pp. 74-77, Dhaka, Bangladesh, 5-6 January 2001, (IEEE Xplore).
M. Shorif Uddin, H. Inaba, Y. Yoshida, Y. Itakura, "Notes on debris flow image model," SPIE Northeast Regional Meeting on Optoelectronics, Photonics, and Imaging, pp. 68-69, Rochester, New York, USA, 10-11 April 2001.
M. Shorif Uddin, H. Inaba, Y. Itakura, Y. Yoshida, M. Kasahara, "Large motion estimation by gradient technique - application to debris flow velocity," Proc. 25th General Assembly of the European Geophysical Society, Nice, France, 25-29 April, 2000.
M. Shorif Uddin, H. Inaba, Y. Itakura, M. Kasahara, "Notes on adaptive approach of computer-based spatial filtering, Proceedings of the 1998 International Symposium on Noise Reduction for Imaging and Communication Systems, S. Fujimura, M. Yamada, M. Sekine eds. pp. 209-214, Tokyo, Japan, 10-12 November 1998.
H. Inaba, M. Shorif Uddin, Y. Itakura, M. Kasahara, "Surface velocity vector field measurement of debris flow based on spatio temporal derivative space method," in Proceedings of First nternational Conference on Debris Flow Hazards Mitigation, Cheng-lung Chen ed. pp. 757-766, San Fransisco, USA, 7-9 August 1997.
M. Shorif Uddin, M. Honda, H. Azabu, H. Inaba, Y. Itakura, M. K
"""

# Regular expression to extract authors and titles
pattern = r"(.+?),\s*\"(.+?)\""

matches = re.findall(pattern, text)

# Save to CSV
with open('research_authors_titles_ju2.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Authors', 'Title'])  # Header row
    for match in matches:
        writer.writerow(match)

print("Data saved to research_authors_titles.csv")
