import csv

# Provided text
text = """
1	ADBNet: An Attention-Guided Deep Broad Convolutional Neural Network for the Classification of Breast Cancer Histopathology Images	Musfequa Rahman, Kaushik Deb, Pranab Kumar Dhar, Tetsuya Shimamura	IEEE Access	2024
2	XAI-Driven Lightweight Multiscale ConvLSTM Architecture for Video Violence Detection	Md Al-Mamun Provath, Kaushik Deb, Kang Hyun Jo	33rd International Symposium on Industrial Electronics (ISIE), Page:1-6	2024
3	An Enhanced Feature-Based Hybrid Approach for Adversarial PDF Malware Detection	GM Sakhawat Hossain, Kaushik Deb, Iqbal H Sarker	6th International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT), Page:101-106	2024
4	Removing Rain from Single Image Using Atrous U-Net and GAN	Ayesha Banu, Sabiha Anan, Kaushik Deb	6th International Conference on Electrical Engineering and Information & Communication Technology (ICEEICT), Page:1298-1303	2024
5	A hybrid deep learning framework for daily living human activity recognition with cluster-based video summarization	S Hossain, K Deb, S Sakib, IH Sarker	Multimedia Tools and Applications, Springer, Page 1-54	2024
6	PDF Malware Detection: Towards Machine Learning Modeling with Explainability Analysis	GM Sakhawat Hossain, Kaushik Deb, Helge Janicke, Iqbal H Sarker	IEEE Access	2024
7	Estimation from Human Facial Expression Using Deep Neural Network	Md Ashiqur Rahman, Shuhena Salam Aonty, Kaushik Deb	Intelligent Computing and Optimization: Proceedings of the 6th International Conference on Intelligent Computing and Optimization 2023 (ICO2023), Volume:729 page: 252, Publisher: Springer Nature	2023
8	Classification of Lung and Colon Cancer Histopathological Images Using Global Context Attention Based Convolutional Neural Network	Md Al-Mamun Provath, Kaushik Deb, Pranab Kumar Dhar, Tetsuya Shimamura	IEEE Access	2023
9	Improved YOLOv5-Based Real-Time Road Pavement Damage Detection in Road Infrastructure Management	Abdullah As Sami, Saadman Sakib, Kaushik Deb, Iqbal H Sarker	Algorithms, Volume: 16, Issue: 9, Pages: 452, Publisher: MDPI	2023
10	Attention-Based Human Age Estimation from Face Images to Enhance Public Security	Md Ashiqur Rahman, Shuhena Salam Aonty, Kaushik Deb, Iqbal H Sarker	Data, Volume: 8, Issue: 10, Pages: 145, Publisher: MDPI	2023
11	Outdoor Trash Detection in Natural Environment Using a Deep Learning Model	Dhrubajyoti Das, Kaushik Deb, Taufique Sayeed, Pranab Kumar Dhar, Tetsuya Shimamura	IEEE Access	2023
12	Human Pose Estimation Using Parallel Architecture	huhena Salam Aonty, Kaushik Deb, Dhrubajyoti Das, Kang-Hyun Jo	2023 International Workshop on Intelligent Systems (IWIS), Pages: 1-6, Publisher: IEEE	2023
13	Daily Living Human Activity Recognition Using Deep Neural Networks	Md Shihab Hossain, Kaushik Deb, Syed Md Minhaz Hossain, Kang-Hyun Jo	2023 International Workshop on Intelligent Systems (IWIS), Pages: 1-6, Publisher: IEEE	2023
14	Classification of Lung and Colon Cancer Using Deep Learning Method	Md Al-Mamun Provath, Kaushik Deb, Kang-Hyun Jo	International Workshop on Frontiers of Computer Vision, Pages:135-148, Publisher: Springer Nature Singapore	2023
15	Classifying Breast Cancer Using Deep Convolutional Neural Network Method	Musfequa Rahman, Kaushik Deb, Kang-Hyun Jo	International Workshop on Frontiers of Computer Vision, Pages:135-148, Publisher: Springer Nature Singapore	2023
16	A comprehensive study on atlas-based classification of autism spectrum disorder using functional connectivity features from resting-state functional magnetic resonance imaging	Faria Zarin Subah, Kaushik Deb	Neural Engineering Techniques for Autism Spectrum Disorder, Volume 2,Pages: 269-296, Publisher: Academic Press	2023
17	Person Recognition Based on Deep Gait: A Survey	Md Khaliluzzaman, Ashraf Uddin, Kaushik Deb, Md Junayed Hasan	Sensors, Volume:23,Issue:10,Pages: 4875, Publisher:MDPI	2023
18	A Transfer Learning Approach to Recognize Pedestrian Attributes	Saadman Sakib, Anik Sen, Kaushik Deb	Applied Intelligence for Industry 4.0, Pages: 145-161, Publisher: Chapman and Hall/CRC	2023
19	Flood Region Detection Based on K-Means Algorithm and Color Probability	Promiti Chakraborty, Sabiha Anan, Kaushik Deb	Computer Vision and Image Analysis for Industry 4.0, Pages: 164-180, Publisher: Chapman and Hall/CRC	2023
20	Multi-Person Pose Estimation using Group-Based Convolutional Neural Network Model	Shuhena Salam Aonty, Kaushik Deb, Moumita Sen Sarma, Pranab Kumar Dhar, Tetsuya Shimamura	IEEE Access	2023
21	Shadow processing with color model adjustment and texture analysis	Md. Azhar Uddin, Tahmina Khanam, Muhammad Ibrahim Khan, Kaushik Deb and Kang-Hyun Jo	The International Workshop on Intelligent Systems, Ulsan, Republic of Kore, August 17-19	2022
22	Road Damage Detection and Classification using Deep Neural Network	Md Mahadi Hasan, Saadman Sakib, Kaushik Deb	4th International Conference on Electrical, Computer & Telecommunication Engineering (ICECTE)	2022
23	Jointly Learning Structure for Human Pose Estimation using Convolutional Neural Networks	Shuhena Salam Aonty, Moumita Sen Sarma, Kaushik Deb	4th International Conference on Electrical, Computer & Telecommunication Engineering (ICECTE)	2022
24	Masked Face Inpainting Using Generative Adversarial Network Based Architecture	Maisha Maimuna, Syed Md Minhaz Hossain, Kaushik Deb	5th International Conference on Intelligent Computing and Optimization 2022 (ICO2022)	2022
25	Trash Image Classification Using Transfer Learning Based Deep Neural Network	Dhrubajyoti Das, Anik Sen, Syed Md Minhaz Hossain, Kaushik Deb	5th International Conference on Intelligent Computing and Optimization 2022 (ICO2022)	2022
26	Detecting Spam SMS Using Self Attention Mechanism	Syed Md Minhaz Hossain, Anik Sen, Kaushik Deb	5th International Conference on Intelligent Computing and Optimization 2022 (ICO2022)	2022
27	Fine-Grained Soccer Actions Classification Using Deep Neural Network	Anik Sen, Syed Md Minhaz Hossain, Mohammad Ashraf Russo, Kaushik Deb, Kang-Hyun Jo	15th International Conference on Human System Interaction (HSI)	2022
28	Emotion Recognition from Speech Using Deep Learning	MD Muhyminul Haque, Kaushik Deb	Proceedings of International Joint Conference on Advances in Computational Intelligence: IJCACI 2021	2022
29	Emergency Vehicle Detection Using Deep Convolutional Neural Network	Samiul Haque, Shayla Sharmin, Kaushik Deb	Page:535-547, Proceedings of International Joint Conference on Advances in Computational Intelligence: IJCACI 2021	2022
30	Categorization of actions in soccer videos using a combination of transfer learning and Gated Recurrent Unit	Anik Sen, Kaushik Deb	ICT Express	2022
31	Tomato leaf disease recognition using depthwise separable convolution	Syed Md Minhaz Hossain, Khaleque Md Aashiq Kamal, Anik Sen, Kaushik Deb	Intelligent Computing & Optimization: Proceedings of the 4th International Conference on Intelligent Computing and Optimization 2021 (ICO2021)	2022
32	Human Fall Classification from Indoor Videos Using Modified Transfer Learning Model	Arifa Sultana, Kaushik Deb	Proceedings of the International Conference on Big Data, IoT, and Machine Learning: BIM 2021	2022
33	A Framework for Pedestrian Attribute Recognition Using Deep Learning	Saadman Sakib, Kaushik Deb, Pranab Kumar Dhar, Oh-Jin Kwon	Applied Sciences	2022
34	Plant Leaf Disease Recognition Using Histogram Based Gradient Boosting Classifier	Syed Mohammad Minhaz Hosain, Kaushik Deb	In: Vasant P., Zelinka I., Weber GW. (eds) Intelligent Computing and Optimization. Advances in Intelligent Systems and Computing, vol 1324. Springer, Cham. https://doi.org/10.1007/978-3-030-68154-8_47	2021
35	A Framework for Traffic Sign Detection Based on Fuzzy Image Processing and Hu Features	Zainul Abedin, Kaushik Deb	In: Vasant P., Zelinka I., Weber GW. (eds) Intelligent Computing and Optimization. Advances in Intelligent Systems and Computing, vol 1324. Springer, Cham., 2021 https://doi.org/10.1007/978-3-030-68154-8_30	2021
36	Categorization of actions in soccer videos using a combination of transfer learning and Gated Recurrent Unit	Anik Sen, Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	ICT Express, Vol-, No. , . Published by ELSEVIER, 2021. https://doi.org/10.1016/j.icte.2021.03.004	2021
37	Door Detection Based on Geometrical Features and Harris Corner	Md. Akber Hossain, Sabiha Anan, and Kaushik Deb	Turkish Journal of Computer and Mathematics Education, Vol-12, No. 3, pp. 3250 - 3257, Turkey	2021
38	CricShotClassify: An Approach to Classifying Batting Shots from Cricket Videos Using a Convolutional Neural Network and Gated Recurrent Unit	Anik Sen, Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	Sensors, Vol-21, No. 8, 2846. Published by MDPI, Switzerland, 2021. https://doi.org/10.3390/s21082846	2021
39	Plant Leaf Disease Recognition Using Depth-Wise Separable Convolution-Based Models	Syed Mohammad Minhaz Hosain, Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	Symmetry, Vol-13, No. 3, 511. Published by MDPI, Switzerland, 2021. https://doi.org/10.3390/sym13030511	2021
40	Classification of Indoor Human Fall Events Using Deep Learning	Arifa Sultana, Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	Entropy, Vol-23, No. 3, 328. Published by MDPI, Switzerland, 2021. https://doi.org/10.3390/e23030328	2021
41	Image Defogging Framework Using Segmentation and the Dark Channel Prior	Sabiha Anan, Mohammad Ibrahim Khan, Mir Md. Saki Kowsar, Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	Entropy, Vol-23, No. 3, 285. Published by MDPI, Switzerland, 2021. https://doi.org/10.3390/e23030285	2021
42	A Deep Learning Approach to Predict Autism Spectrum Disorder Using Multisite Resting-State fMRI	Faria Zarin Subah, and Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	Applied Sciences, Vol-11, No. 8, 3636. Published by MDPI, Switzerland, 2021. https://doi.org/10.3390/app11083636	2021
43	Traditional Bangladeshi Sports Video Classification Using Deep Learning Method	Moumita Sen Sarma, and Kaushik Deb, Pranab Kumar Dhar, and Takeshi Koshiba	Applied Sciences, Vol-11, No. 5, 2149. Published by MDPI, Switzerland, 2021. https://doi.org/10.3390/app11052149	2021
44	Traditional Bangladeshi Sports Video Classification using Transfer Learning Approach and Long Short Term Memory	Moumita Sen Sarma, and Kaushik Deb	BCS Journal of Computer and Information Technology, Vol-02, pp. 77-86, ISSN:2664-4592(Print) 2664-4606(Online), Bangladesh Computer Society.	2020
45	Blind Image Watermarking in Canonical and Cepstrum Domains Based on 4-Connected t-o’clock Scrambling	Farhana Shirin Chowdhury, Pranab Kumar Dhar , Kaushik Deb, and Takeshi Koshiba	Symmetry, 12(2), 266 EISSN 2073-8994, Published by MDPI, Switzerland	2020
46	Door Detection Based on Haar Cascade Classifier and Visual Features Extraction	Ahsan Sadee Tanim, Sharmistha Chanda Tista and Kaushik Deb	BCS Journal of Computer and Information Technology, Vol-01,2019, ISSN:2664-4592(Print) 2664-4606(Online), Bangladesh Computer Society, Bangladesh	2019
47	Human Detection Based on HOG-LBP for Monitoring Sterile Zone	Farjana Bintay Kamal, Sangita Mitra, Tahmina Khanam, Uzzal K. Acharjee, Dipankar Das, Kaushik Deb	In Proceedings of the IEEE International Conference on Electrical, Computer & Communication Engineering (ECCE 2019), Coxs Bazar, Bangladesh, Feb. 07-09	2019
48	Illegally Parked Vehicle Detection Based on Haar-Cascade Classifier	Aapan Mutsuddy, Kaushik Deb, Tahmina Khanam, and Kang-Hyun Jo	Journal of Lecture Notes in Computer Science, ISSN: 0302-9743, Part II, Vol. 11644, pp. 602-614, Springer, Germany, 2019	2019
49	A comparative study on handwritten Bangla character recognition	Md. Atiqul islam rizvi, Kaushik Deb, Md. Ibrahim Khan, Mir Md. Saki Kowsar, Tahmina Khanam	Turkish Journal of Electrical Engineering & Computer Sciences, ISSN: 1300-0632, Vol. 27, pp. 3195-3207, Scientific and Technological Research Council of Turkey, 2019	2019
50	Human Detection Utilizing Adaptive Background Mixture Models and Improved Histogram of Oriented Gradients	S. A. Chowdhury, M. M. S. Kowsar, and K. Deb	ICT Express, ISSN: 2405-9595, Vol. 4, Issue 4, pp. 216-220, Elsevier, December 2018	2018
51	Stairways Detection Based on Approach Evaluation and Vertical Vanishing Point	Md. Khaliluzzaman and Kaushik Deb	International Journal of Computational Vision and Robotics (IJCVR), ISSN Print: 1752-9131, Vol. 8, No. 2, pp. 168-189 , Inderscience Publications, 2018	2018
52	Baggage Recognition in Occluded Environment using Boosting Technique	Tahmina Khanam and Kaushik Deb	KSII Transactions on Internet and Information Systems, vol. 11, no. 11, pp. 5436-5458, November 2017	2017
53	Detection and Tracking of Humans Based on Improved Histogram of Oriented Gradients and Kalman Filter	S. A. Chowdhury, K. Deb, P. K. Dhar and M. A. F. M. R. Hasan	Southeast Asian Journal of Sciences, vol. 5, no. 2, pp. 57-72, 2017	2017
54	MetaG: a graph-based metagenomic gene analysis for big DNA data	Linkon Chowdhury, Mohammad Ibrahim Khan, Kaushik Deb, and Sarwar Kamal	Network Modeling Analysis in Health Informatics and Bioinformatics, DOI 10.1007/s13721-016-0132-7, Online ISSN 2192-6670, Vol. 05, pp. 1-16, Springer Vienna, 2016	2016
55	An Empirical Robotic Framework for Initiating Interaction with the Target Human in Multiparty Settings	Md. Moshiul Hoque, Quazi Delwar Hossian, Kaushik Deb, Dipankar Das, Y. Kobayashi, and Y. Kuno	Journal of Circuits, Systems, and Computers, DOI: 10.1142/S0218126615400034, ISSN: 0218-1266 , Vol. 24, No.2, pp. 1540001-25, World Scientific Publishing Company, 2015	2015
56	Cast Shadow Detection and Removal of Moving Objects from Video Based on HSV Color Space	Kaushik Deb, Animash Kar and Ashraful Huq Suny	Smart Computing Review, DOI: 10.6029/smartcr.2014.01.003, Vol. 5, No.1, pp. 38-50, The Korea Academia-Industrial Cooperation Society (KAIS), South Korea, 2015	2015
57	Detecting Anomalous Behavior of Credit Card Transaction using Statistical Approach	Kaushik Deb, Kazi Zakia Sultana and Tahmina Khanam	The Chittagong University Journal of Science, Vol-37,pp.-62-75,2015	2015
58	Shadow Detection and Removal Based on YCbCr Color Space	Kaushik Deb and Ashraful Huq Suny	Smart Computing Review, DOI: 10.6029/smartcr.2014.01.003, Vol. 4, No.1, pp. 23-33, The Korea Academia-Industrial Cooperation Society (KAIS), South Korea, 2014	2014
59	A Motion Region Detection and Tracking Method	Kaushik Deb, Sayem Mohammad Imtiaz, and Priyam Biswas	Smart Computing Review, DOI: 10.6029/smartcr.2014.01.008, Vol. 4, No.1, pp.79-90, The Korea Academia-Industrial Cooperation Society (KAIS), South Korea, 2014	2014
60	DCT and DWT Based Robust Audio Watermarking Scheme for Copyright Protection	Kaushik Deb, Md. Ashikur Rahaman, Kazi Zakia Sultana, Md. Iqbal Hasan Sarker, and Ui-Pil Chong	Journal of theInstitute of Signal Processing and Systems, ISSN: 1229-9480, Vol. 15, No. 1, pp. 1-8, The Korea Institute of Signal Processing and Systems (KISPS), South Korea, 2014.	2014
61	Vehicle License Plate Detection and Tilt Correction Based on HSI Color Model and SUSAN Corner Detector	Muhammad Kamal Hossen and Kaushik Deb	Smart Computing Review, DOI: 10.6029/smartcr.2014.01.003, Vol. 4, No.5, pp. 371-388, The Korea Academia-Industrial Cooperation Society (KAIS), South Korea, 2014.	2014
62	Design A Robotic Head to Attract Human Attention by Considering Viewing Situations	Md. Moshiul Hoque, Y. Kobayashi, Y. Kuno, and Kaushik Deb	Computer Science & Engineering Research Journal (CSERJ), ISSN: 1990-4010, Vol. 8, pp. 11-21, Bangladesh, 2013	2013
63	Kaushik Deb, Md. Sajib Al-Seraj, and Ui-Pil Chong	A Low Frequency Band Watermarking with Weighted Correction in the Combined Cosine and Wavelet Transform Domain	Journal of the Institute of Signal Processing and Systems, ISSN: 1229-9480, Vol. 14, No. 1, pp. 13-20, The Korea Institute of Signal Processing and Systems (KISPS), South Korea, 2013.	2013
64	Neural Network-Based English Alphanumeric Character Recognition	Md. Fazlul Kader and Kaushik Deb	International Journal of Computer Science, Engineering and Applications (IJCSEA) Vol.2, No.4, pp. 119-128, 2012	2012
65	A New Audio Watermarking Method Based on Discrete Cosine Transform with a Gray Image	Muhammad Ibrahim Khan, Md. Iqbal Hasan Sarker, Kaushik Deb, and Md. Hasan Farhad	International Journal of Computer Science & Information Technology (IJCSIT), ISSN: 0975-3826, Vol. 4, No. 4, pp. 01-10, 2012.	2012
66	Automated Road Line Detection for Intelligent Vehicle	Anik Saha, Dipanjan Das Roy, Tauhidul Alam and Kaushik Deb	Global Journal of Computer Science and Technology, ISSN: 0975-4172, Vol. 12, Issue 6, pp. 01-05, Global Journals Inc., 2012	2012
67	Two-Handed Sign Language Recognition for Bangla Character Using Normalized Cross Correlation	Kaushik Deb, Muhammad Ibrahim Khan, Helena Parvin Mony and Sujan Chowdhury	Global Journal of Computer Science and Technology, ISSN: 0975-4172, Vol. 12, Issue 3, pp. 01-06, Global Journals Inc., 2012	2012
68	Lossless Image Compression Technique Based on Snack Ordering	Kaushik Deb, Tauhidul Alam, Md. Mahammud Ali and Kang-Hyun Jo	Computer Science & Engineering Research Journal, ISSN: 1990-4010, Vol. 7, pp. 30-36, Bangladesh, 2012	2012
69	Md. Iqbal Hasan Sarker, Muhammad Ibrahim Khan, Kaushik Deb, and Md. Faisal Faruque	FFT based Audio Watermarking Method with a Gray Image for Copyright Protection	International Journal of Advanced Science & Technology (IJAST), ISSN: 2005-4238, Vol. 47, pp. 65-76, 2012	2012
70	Automatic Vehicle Identification by Plate Recognition for Intelligent Transportation Systems'	Kaushik Deb, My Ha Le, Byung-Seok Woo and Kang-Hyun Jo	Journal of Lecture Notes in Artificial Intelligence, ISSN: 0302-9743, Part II, Vol. 6704, pp. 163-172, Springer, Germany, 2011	2011
71	Vehicle License Plate Detection Method Based on HDR Image Generation from Multiple Computers	Kaushik Deb and Kang-Hyun Jo	Computer Science & Engineering Research Journal, ISSN: 1990-4010, Vol. 6, pp. 27-34, Bangladesh, 2011.	2011
72	Vehicle License Plate Tilt correction Based on the Straight Line Fitting Method and Minimizing Variance of Coordinates of Projection Points	Kaushik Deb, Andrey Vavilin, Jung-Won Kim, and Kang-Hyun Jo	International Journal of Control, Automations and Systems, ISSN: 2005-4092 (Electronic), Vol. 8, No.5, pp. 27-34, Springer, Germany, Oct. 2010.	2010
73	A Modified Spectral Modeling Synthesis Algorithm for Whale Sound	Pranab Kumar Dhar, Mohammed Ibrahim Khan, Kaushik Deb, and Jong-Myon Kim	International Journal of Computer Science and Network Security, ISSN: 1738-7906, pp. 34-41, Vol. 10, No.9, S. Korea, Sep. 2010.	2010
74	Fast HDR Image Generation Technique based on Exposure Blending	Andrey Vavilin, Kaushik Deb, and Kang-Hyun Jo	Journal of Lecture Notes in Artificial Intelligence, ISSN: 0302-9743 print, Part III, Springer, Germany, 2010.	2010
75	A Vehicle License Plate Detection Method for Intelligent Transportation System Applications	Kaushik Deb and Kang-Hyun Jo	Cybernetics and Systems: An International Journal, ISSN: 1087-6553 online, Vol. 40, Issue 8, pp. 689-705, Taylor & Francis, UK, 2009.	2009
76	Vehicle License Plate Detection Algorithm Based on Color Space and Geometrical Properties	Kaushik Deb and Kang-Hyun Jo	Journal of Lecture Notes in Computer Science, ISSN: 0302-9743 print, Vol. 5754, pp. 555-564, Springer, Germany, 2009.	2009
77	Vehicle License Plate Detection Method Based on Sliding Concentric Windows and Histogram	Kaushik Deb, Hyun-Uk Chae, and Kang-Hyun Jo	Journal of Computers, ISSN: 1796-203X, Vol. 4, No. 8, pp. 771-777, Academy Publisher, Finland, 2009.	2009
78	An Efficient Method of Vehicle License Plate Detection Based on HSI Color Model and Histogram	Kaushik Deb, Hee-Chul Lim, Suk-Ju Kang, and Kang-Hyun Jo	Journal of Lecture Notes in Artificial Intelligence, ISSN: 0302-9743 print, Vol. 5579, pp. 66-75, Springer, Germany, 2009.	2009
79	Statistical Characteristics in HSI Color Model and Position Histogram based Vehicle License Plate Detection.	Kaushik Deb, Suk-Ju Kang, and Kang-Hyun Jo	Journal of Intelligent Service Robotics, ISSN: 1861-2776 print, Vol. 2, No. 3, pp. 173-186, Springer, Germany, 2009	2009
80	Geometrical Reorientation of Distorted Road Sign using Projection Transformation for Road Sign Recognition	Hee-Chul Lim, Kaushik Deb, and Kang-Hyun Jo	Journal of Institute of Control, Robotics and Systems, Vol. 15, No., 11, pp. 1088-1095, Korea, 2009.	2009
81	Geometrical Property and Histogram Based Korean Vehicle License Plate Detection	Kaushik Deb and Kang-Hyun Jo	Computer Science & Engineering Research Journal, ISSN: 1990-4010, Vol. 4, pp. 56-62, Bangladesh, 2008.	2008
82	Construction of a simple Robotic Arm and Control by Software	Kaushik Deb and Thomas Chowdhury	Computer Science & Engineering Research Journal, ISSN: 1990-4010, Vol. 3, pp. 31-37, Bangladesh, 2006.	2006
83	Structural Operational Semantics of Inheritance and Object creation in JAVA	M. S. Arefin, M. M. Hoque, M.T. Islam, and Kaushik Deb	Computer Science & Engineering Research Journal, ISSN: 1990-4010, Vol. 2, pp. 29-35, Bangladesh, 2005.	2005
84	Human Detection Based on HOG-LBP for Monitoring Sterile Zone	Farjana Bintay Kamal, Sangita Mitra, Tahmina Khanam, Uzzal K. Acharjee, Dipankar Das and Kaushik Deb	In Proceedings of the 2nd International Conference on Electrical, Computer & Communication Engineering (ECCE 2019), Cox's Bazar, Bangladesh, Feb. 7-9, 2019	2019
85	Geometrical Feature Based Stairways Detection and Recognition using Depth Sensor	Md. Khaliluzzaman Kaushik Deb	In Proceedings of the 44th Annual Conference of the IEEE Industrial Electronics Society(IECON 2018), Washington D.C., Oct. 21-23, 2018.	2018
86	Bangladeshi Road Sign Recognition Based on DtBs Vector and Artificial Neural Network	Soumen Chakraborty, Mohammed Nasir Uddin and Kaushik Deb	In Proceedings of the International Conference on Electrical, Computer & Communication Engineering (ECCE 2017), Cox's Bazar, Bangladesh, Feb. 16-18, 2017.	2017
87	Baggage Detection and Classification using Human Body Parameter & Boosting Technique	Tahmina Khanam, Kaushik Deb and Kang-Hyun Jo	In Proceedings of the 10thIEEE International Conference on Human System Interactions, pp. 54-59, University of Ulsan, Ulsan, Republic of Korea, July 17-19, 2017.	2017
88	Occlusion handling and human detection based on Histogram of Oriented Gradients for automatic video surveillance	S. A. Chowdhury, M. N. Uddin, M. M. S. Kowsar and K. Deb	International Conference on Innovations in Science, Engineering and Technology (ICISET), pp. 1-4, 2016.	2017
89	Digital Electric Meter Reading Recognition Based on Horizontal and Vertical Binary Pattern	Md. Khaliluzzaman and Kaushik Deb	3rd International Conference on Electrical Information and Communication Technology (EICT), IEEE, 2017	2017
90	Zebra-crossing Detection Based on Geometric Feature and Vertical Vanishing Point	Md. Khaliluzzaman and Kaushik Deb	In Proceeding of the IEEE 3rd International Conference on Electrical Engineering and Information & Communication Technology (iCEEiCT 2016), MIST, Dhaka, Bangladesh, September 22-24, 2016.	2016
91	Occlusion handling and human detection based on Histogram of Oriented Gradients for automatic video surveillance	Shaiyan Ameen Chowdhury, M. N. Uddin, M.S. Kowsar and Kaushik Deb	IEEE International Conference on Innovations in Science, Engineering and Technology (ICISET), pp. 1-4, Chittagong, Bangladesh, 2016.	2016
92	Human and Carried Baggage Detection & Classification based on RSD-HOG in Video Frame	Tahmina Khanam and Kaushik Deb	In Proceedings of the 9th International Conference on Electrical & Computer Engineering (ICECE 2016), pp. 415 - 418, BUET, Dhaka, Bangladesh, Dec. 20-22, 2016.	2016
93	Analyzing Image Transmission Quality using Filter and C-QAM	d. Khaliluzzaman, Deepak Kumar Chy., Kaushik Deb	In Proceeding of the 1st International Conference on Advancement of computer Communication & Electrical Technology (ACCET 2016), Murshidabad, INDIA, October 21-22, Taylor & Francis, 2016	2016
94	Support Vector Machine for Overcoming the Problem of Vanishing Point during Stairways Detection	Md. Khaliluzzaman and Kaushik Deb	In Proceeding of the 2nd International Conference on Electrical, Computer & Telecommunication Engineering (ICECTE 2016), RUET, Rajshahi, Bangladesh, December 8-10, IEEE, 2016	2016
95	Analyzing MRI Segmentation Based on Wavelet and BEMD using Fuzzy C-Means Clustering	Md. Khaliluzzaman and Kaushik Deb	In Proceeding of the International Workshop on COMPUTATIONAL Intelligence (IWCI 2016), pp. 15-20, Jahangirnagar University, Dhaka, Bangladesh, December 12-13, IEEE, 2016.	2016
96	Stairways Detection and Distance Estimation Approach Based on Three Connected Point and Triangular Similarity	Md. Khaliluzzaman, Kaushik Deb, and Kang-Hyun Jo	In Proceeding of the 9th IEEE International Conference on Human System Interaction (HSI2016), pp. 330-336, University of Portsmouth, Portsmouth, UK, July 6-8, 2016. (Received Best Paper Award)	2016
97	Stairways Detection and Distance Estimation Approach Based on Three Connected Point and Triangular Similarity	Md. Khaliluzzaman, Kaushik Deb, and Kang-Hyun Jo	In Proceeding of the 9th IEEE International Conference on Human System Interaction (HSI2016), pp. 330-336, University of Portsmouth, Portsmouth, UK, July 6-8, 2016. (Received Best Paper Award)	2016
98	Moving cast shadow detection and removal from Video based on HSV color space	Animash Kar and Kaushik Deb	In Proceedings of the 2nd International Conference on Electrical Engineering & Information Communication Engineering (ICEEICT 2015), Dhaka, Bangladesh, May 21-23, 2015.	2015
99	Bangladeshi road sign detection based on YCbCr color model and DtBs vector	Soumen Chakraborty and Kaushik Deb	In Proceedings of the International Conference on Computer & Information Engineering (ICCIE 2015), pp. 158 - 161, Rajshahi, Bangladesh, Nov. 26-27, 2015.	2015
100	Color Image Watermarking Based on LU Decomposition	Kazi Anika Hossain Naima, Tahmina Khhanm and Kaushik Deb	In Proceedings of the 1st International Conference on Mathematics and Its Applications (ICMA 2015), pp. 47-52, Khulna, Bangladesh, December 23, 2015	2015
101	An Efficient Framework for Detecting Face Region Based on Skin Color Modeling and SVM Classifier	Arpita Chowdhury, Tahmina Khhanm and Kaushik Deb	In Proceedings of the 1st International Conference on Mathematics and Its Applications (ICMA 2015), pp. 42-46, Khulna, Bangladesh, December 23, 2015	2015
102	Video Watermarking Scheme Using Second Level Discrete Wavelet Transformation (DWT) and Fast Fourier Transformation	Md. Rahat Mahmud, Tahmina Khanam and Kaushik Deb	In Proceedings of the 3rd International Conference on Mechanical Engineering and Renewable Energy(ICMERE 2015), Chittagong, Bangladesh, December 26-29, 2015.	2015
103	Detecting Books from Bookshelf of Multiple Cells	Prianka Banik and Kaushik Deb	In Proceedings of the International Conference on Engineering Research, Innovation & Education (ICERIE), pp. 417-421, Sylhet, Bangladesh, Jan. 11-13, 2013.	2013
104	An Intelligent Human-Robot Interaction Framework to Control the Human Attention	Md. Moshiul Hoque, Kaushik Deb, Dipankar Das, Y. Kobayashi, and Y. Kuno	In Proceedings of the 2nd International Conference on Informatics, Electronics & Vision (ICIEV), Dhaka, Bangladesh, May 17-18, 2013.	2013
105	Moment Invariants Based Object Recognition for Different Pose and Appearances in Real Scenes	Swati Nigam, Kaushik Deb, and Ashish Khare	In Proceedings of the 2nd International Conference on Informatics, Electronics & Vision (ICIEV), Dhaka, Bangladesh, May 17-18, 2013.	2013
106	An Efficient Method of Vehicle License Plate Recognition Based on Sliding Concentric Windows and Artificial Neural Network	Kaushik Deb, Md. Ibrahim Khan, Anik Saha, and Kang-Hyun Jo	In Proceeding of the 2nd International Conference on Computer, Communication, Control and Information Technology (C3IT 2012), pp. 42, West Bengal, India, Feb. 25-26, 2012.	2012
107	Designing a Semantic Web Ontology of agricultural domain	Sujan Chowdhury, Kayasar Md. Mahedi, and Kaushik Deb	In Proceedings of the 7th International Forum on Strategic Technology (IFOST), Tomsk, Russia, Sept. 18-21, 2012.	2012
108	A joint DWT-DCT Based Watermarking Technique for Avoiding Unauthorized Replication	Kaushik Deb, Sajib Al-Seraj, Md. Saki Kowser, Iqbal Hasan Sarker	In Proceedings of the 7th International Forum on Strategic Technology (IFOST), Tomsk, Russia, Sept. 18-21, 2012.	2012
109	Bangladeshi Vehicle License Plate Detection Method Based on HSI Color Model and Geometrical Properties	Kaushik Deb, Muhammad Kamal Hossen, Md. Ibrahim Khan, and Md. Rafiqul Alam	In Proceedings of the 7th International Forum on Strategic Technology (IFOST), Tomsk, Russia, Sept. 18-21, 2012.	2012
110	Robotic System for Making Eye Contact Pro-activity with Humans	Md. Moshiul Hoque and Kaushik Deb	In Proceedings of the 7th IEEE International Conference on Electrical & Computer Engineering (ICECE), pp. 125-128, Dhaka, Bangladesh, Dec. 20-22, 2012	2012
111	Combined DWT-DCT Based Digital Watermarking Technique for Copyright Protection	Kaushik Deb, Md. Sajib Al-Seraj, Md. Moshiul Hoque and Md. Iqbal Hasan Sarker	In Proceedings of the 7th IEEE International Conference on Electrical & Computer Engineering (ICECE), pp. 458-461, Dhaka, Bangladesh, Dec. 20-22, 2012.	2012
112	Optical Recognition of Vehicle License Plates	Kaushik Deb, Md. Ibrahim Khan, Md. Rafiqul Alam, and Kang-Hyun Jo	In Proceeding of the 6th IEEE International Forum on Strategic Technology (IEEE IFOST 2011), pp. 743-748 Harbin, China, Aug. 22-24, 2011. (Received Best Paper Award)	2011
113	Bangla Character Recognition by using Artificial Neural Network	Anik Saha and Kaushik Deb	In Proceeding of the International Conference on Mechanical Engineering and Renewable Energy (ICMERE 2011), CUET, Chittagong, Bangladesh, Dec. 22-24, 2011.	2011
114	\'Developing a Bangla Spell Checker With Possible Suggestions by using Longest Common Sub Sequence and Soundex algorithm	Sujan Chowdhury and Kaushik Deb	In Proceeding of the International Conference on Mechanical Engineering and Renewable Energy (ICMERE 2011), CUET, Chittagong, Bangladesh, Dec. 22-24, 2011.	2011
115	Road Sign Detection Method based on Fast HDR Image Generation Technique	Andrey Vavilin, Kaushik Deb, Tae-Ho Kim, and Kang-Hyun Jo	In Proceeding of the 25th IEEE International Conference of Image and Vision Computing New Zealand (IVCNZ 2010), Queenstown, New Zealand, Nov. 08-09, 2010.	2010
116	Recognizing Outdoor Scene Objects Using Texture Features and Probabilistic Appearance Model	My-Ha Le, Kaushik-Deb, and Kang-Hyun Jo	In Proceeding of the 10th International Conference on Control Automation and Systems (ICCAS 2010), pp. 1440-1444, Kintex, Gyeonggi-do, Korea, Oct. 27-30, 2010.	2010
117	Vehicle License Plate Tilt Correction Based on the Straight Line Fitting Method	Kaushik-Deb, Andrey Vavilin, Jung-Won Kim, and Kang-Hyun Jo	In proceeding of the 17th ITS (Intelligent Transportation Systems) World Congress, Busan, Korea, Oct. 25-29, 2010. (Received Outstanding Paper Award)	2010
118	A Modified New Reno for performance Enhancement of TCP in Wireless Network	Pranab Kumar Dhar, Kaushik-Deb, and P. M. Mahamudul Hassan	In Proceeding of the 5th IEEE International Forum on Strategic Technology (IEEE IFOST 2010), Ulsan, S. Korea, Oct. 13-15, 2010.	2010
119	An Efficient Algorithm for finding the Control Point of 3rd order Bezier Curve	Md. Ibrahim Khan, Sujon Chowdhury, Alok Kumar Chowdhury, and Kaushik-Deb	In Proceeding of the 5th IEEE International Forum on Strategic Technology (IEEE IFOST 2010), Ulsan, S. Korea, Oct. 13-15, 2010.	2010
120	Projection and Least Square Fitting with Perpendicular Offsets based Vehicle License Plate Tilt Correction	Kaushik-Deb, Andrey Vavilin, Jung-Won Kim, and Kang-Hyun Jo	In Proceeding of the IEEE SICE (The Society of Instrument and Control Engineers) 2010, Taipei, Taiwan, Aug. 18-21, 2010.	2010
121	An Efficient Method for Correcting Vehicle License Plate Tilt	Kaushik-Deb, Andrey Vavilin, and Kang-Hyun Jo	In Proceeding of the IEEE International Conference on Granular Computing (IEEE GrC 2010), Silicon Valley, Aug. 14-16, 2010.	2010
122	License Plate Detection Method Based on HDR Image Generation from Multiple Cameras	Andy Vavilin, Kaushik Deb and Kang-Hyun Jo	In Proceeding of the Image Processing and Image Understanding (IPIU 2010), JeJu, Korea, Jan. 27-29, 2010.	2010
123	Korean Vehicle License Plate Detection Based on Statistical and Geometrical Properties in HSI Color Space	Kaushik Deb, Suk-Ju Kang, and Kang-Hyun Jo	In proceeding of the 15th Japan-Korea Joint workshop on frontiers of Computer Vision (FCV 2009), pp. 18-23, Andong, Korea, Feb. 5-7, 2009.	2009
124	Vehicle License Plate Extraction Based on Color and Geometrical Features	Kaushik-Deb, Hee-Chul Lim and Kang-Hyun Jo	In Proceeding of the IEEE International Symposium on Industrial Electronics (ISIE 2009), pp.1650-1655, Seoul, Korea, Jul. 5-8, 2009.	2009
125	A Hybrid Vehicle License Plate Detection Method Based on HSI Color Model and Histogram	Kaushik Deb, Kang, Suk-Ju, Kang-Hyun Jo	In proceeding of the IEEE International conf. on Ubiquitous Robots and Ambient Intelligence (URAI 2008), pp. 262-267, Seoul, Korea, 2008.	2008
126	Korean Vehicle License Plate Extraction Based on HSI Color Model and Histogram	Kaushik Deb, Heechul Lim, Kang-Hyun Jo	In proceeding of the Annual conference on Korean Society of Automotive Engineers (KSAE 2008), pp. 132, Daejeon, Korea, 2008.	2008
127	HSI Color based Vehicle License Plate Detection	Kaushik Deb and Kang-Hyun Jo	In proceeding of the IEEE International Conference on Control, Automation and Systems (ICCAS 2008), pp.687-691,Seoul, Korea, 2008.	2008
128	Parallelogram and Histogram based Vehicle License Plate Detection	Kaushik Deb, Hyun-Uk Chae, and Kang-Hyun Jo	In proceeding of the IEEE International Conf. on Smart Manufacturing Application (ICSMA 2008), pp 349-353, Gyeonggi-do, Korea 2008.	2008
129	Korean Vehicle License Plate Detection Based on Geometrical and Colour Properties	Kaushik Deb and Kang-Hyun Jo	In proceeding of the 14th Korea-Japan Joint Workshop on Frontiers of Computer Vision (FCV 2008), pp.118-123, Beppu, Oita, Japan 2008.	2008
130	A Localized Queuing Based Router-Centric Approach to Congestion Avoidance and Recovery for Connectionless datagram Service	M.A.H. Bhuiyan and Kaushik Deb	In proceeding of the IEEE First International Conf. on Next-Generation Wireless Systems (ICNEWS 2006), pp 335-339, Dhaka, Bangladesh 2006.	2006
131	Information System for Medical Firm	Kaushik Deb and V. L. Tokarev	In proceeding of the International Scientific and Technical Conference of the Young Scientist and Experts â€˜XXVI Gagarinâ€™s Lectureâ€™, Vol. 19, pp. 507-510, Moscow, Russia, 2000.	2000
132	Verbs in Russian Terminology of Computer Facilities and Computer Science	Kaushik Deb	In proceeding of the 7th Interuniversity Student Readings on Socially-Humanitarian Problems, The Science and the Society, Vol. 7, pp. 121-122, Tula, Russia, 1998.	1998
133	Door Detection Based on Geometrical Features and Harris Corner	Md. Akber Hossain, Sabiha Anan, and Kaushik Deb	International Conference on Analytical and Interdisciplinary Research (ICAIR-2021), Sangam University, India, February 05-06 (Received Best Paper Award)	2021
	Enhancing image caption generation through context-aware attention mechanism	Ahatesham Bhuiyana, Eftekhar Hossain, Mohammed Moshiul Hoque, and M. Ali Akber Dewan	Enhancing image caption generation through context-aware attention mechanism, vol. 10, Issues: 17, Heliyon, Elsevier, https://doi.org/10.1016/j.heliyon.2024.e36272 (2024).	2024
2	AraCovTexFinder: Leveraging the transformer-based language model for Arabic COVID-19 text identification	M. R. Hossain, M. M. Hoque, N. Siddique, M. A. A. Dewan	AraCovTexFinder: Leveraging the transformer-based language model for Arabic COVID-19 text identification, Engineering Applications of Artificial Intelligence, Vol. 133, Part A, 2024,107987, ISSN 0952-1976, https://doi.org/10.1016/j.engappai.2024.107987 (2024).	2024
3	An Empirical Framework for Detecting Speaking Modes Using Ensemble Classifier", in Multimedia Tools and Applications	[3] S. Afroze, R. Hossain, M. M. Hoque, and A. A. Dewan	An Empirical Framework for Detecting Speaking Modes Using Ensemble Classifier", in Multimedia Tools and Applications (2023), Vol. 83, No. 1, PP. 2349-2382, Springer. https://doi.org/10.1007/s11042-023-15254-8.	2023
4	"TEmoX: Classification of Textual Emotion Using Ensemble of Transformers," in IEEE Access	A. Das, M. M. Hoque, O. Sharif, M. A. A. Dewan and N. Siddique	"TEmoX: Classification of Textual Emotion Using Ensemble of Transformers," in IEEE Access, vol. 11, pp. 109803-109818, 2023, doi: 10.1109/ACCESS.2023.3319455	2023
5	Leveraging the meta-embedding for text classification in a resource-constrained language	M. R. Hossain, M. M. Hoque, N. Siddique	Leveraging the meta-embedding for text classification in a resource-constrained language, Engineering Applications of Artificial Intelligence, vol. 124, 2023, 106586, https://doi.org/10.1016/j.engappai.2023.106586., Elsevier.	2023
6	CovTiNet: Covid text identification network using attention-based positional embedding feature fusion	M. R. Hossain, M. M. Hoque, N. N. Siddique and I. H. Sarker	CovTiNet: Covid text identification network using attention-based positional embedding feature fusion, J. of Neural Computing & Applications (2023), Springer, https://doi.org/10.1007/s00521-023-08442-y NCAA, March 2023,	2023
7	LCDEiT: A Linear Complexity Data-Efficient Image Transformer for MRI Brain Tumor Classification	G. J Ferdous, K. A Sathi, M. A Hossain, M. M. Hoque, M. A. A. Dewan	LCDEiT: A Linear Complexity Data-Efficient Image Transformer for MRI Brain Tumor Classification, IEEE Access, vol. 11, pp. 20337-20350, 2023, doi: 10.1109/ACCESS.2023.3244228. Feb 2023.	2023
8	DeepFocus: A visual focus of attention detection framework using deep learning in multi-object scenarios	S. Afroze, R. Hossain, and M. M. Hoque	DeepFocus: A visual focus of attention detection framework using deep learning in multi-object scenarios, J. Computer and Information Sciences, Vol. 34, Issue 10, Part B, 2022, pp. 10109-10124, ISSN 1319-1578, https://doi.org/10.1016/j.jksuci.2022.10.009, Nov. 2022, Elsevier.	2022
9	Identification of Multilingual Offense and Troll from Social Media Memes Using Weighted Ensemble of Multimodal Features	E. Hossain, O. Sharif, M. M. Hoque, M. A. A. Dewan, N. Siddique, M. A. Hossain	Identification of Multilingual Offense and Troll from Social Media Memes Using Weighted Ensemble of Multimodal Features, J. Computer and Information Sciences, Vol. 34, Issue 9, pp. 6605-6623, ISSN 1319-1578, https://doi.org/10.1016/j.jksuci.2022.06.010, Oct 2022, Elsevier.	2022
10	A Deep Attentive Multimodal Learning Approach for Disaster Identification from Social Media Posts	E. Hossain, M. M. Hoque, E. Hoque and M. S. Islam	“A Deep Attentive Multimodal Learning Approach for Disaster Identification from Social Media Posts,” in IEEE Access, vol. 10, pp. 46538-46551, 2022, doi: 10.1109/ACCESS.2022.3170897.	2022
11	A source-driven probabilistic forwarding and caching strategy in NDN and SDN-based NDN	S. M. A. Iqbal, Asaduzzaman, M. M. Hoque	A source-driven probabilistic forwarding and caching strategy in NDN and SDN-based NDN, Vol. 35, No. 6, 22 January 2022, International Journal of Communication Systems, Willey.	2022
12	A source-driven reinforcement learning-based Data reply strategy to reduce communication overhead in Named Data Networks (NDN)	Iqbal, S.M.A., Asaduzzaman & Hoque, M.M.	A source-driven reinforcement learning-based Data reply strategy to reduce communication overhead in Named Data Networks (NDN). Cluster Comput 25, 647–673 (2022). https://doi.org/10.1007/s10586-021-03443-9, Springer.	2022
13	BEmoC: A Corpus for Identifying Emotion in Bengali Texts	Iqbal, M.A., Das, A., Sharif, O. M. M. Hoque and Iqbal. H. Sarker	BEmoC: A Corpus for Identifying Emotion in Bengali Texts. SN COMPUT. SCI. 3, 135(2022). https://doi.org/10.1007/s42979-022-01028-w, Springer.	2022
14	Classification of Textual Sentiment Using Ensemble Technique.	Mamun, M.M.R., Sharif, O. & Hoque, M.M.	Classification of Textual Sentiment Using Ensemble Technique. SN COMPUT. SCI. 3, 49 (2022). https://doi.org/10.1007/s42979-021-00922-z, Springer.	2022
15	Multi-class Textual Emotion Categorization using Ensemble of Convolutional and Recurrent Neural Network	Parvin, T., Sharif, O. & Hoque, M.M.	Multi-class Textual Emotion Categorization using Ensemble of Convolutional and Recurrent Neural Network. SN COMPUT. SCI. 3, 62(2022). https://doi.org/10.1007/s42979-021-00913-0, Springer.	2022
16	Tackling Cyber-Aggression: Identification and Fine-Grained Categorization of Aggressive Texts on Social Media using Weighted Ensemble of Transformers	O. Sharif and M. M. Hoque	Tackling Cyber-Aggression: Identification and Fine-Grained Categorization of Aggressive Texts on Social Media using Weighted Ensemble of Transformers” Journal of Neurocomputing, Vol. 490, 14 June 2022, Pages 462-481, Elsevier.	2022
17	Bengali Text Document Categorization based on Very Deep Convolution Neural Network	M. R Hossain, M. M Hoque, N. Siddique	Bengali Text Document Categorization based on Very Deep Convolution Neural Network, Expert Systems with Applications, vol. 184, Dec 2021, 115394, Elsevier.	2021
18	Authorship Classification in a Resource Constraint Language using Convolutional Neural Networks in IEEE Access	M, R. Hossain, M. M. Hoque, M. A. A. Dewan, N. Siddique, N. Islam and I. H. Sarker	Authorship Classification in a Resource Constraint Language using Convolutional Neural Networks in IEEE Access, vol. 9, pp. 100319-100338, 2021, doi: 10.1109/ACCESS.2021.3095967, IEEE.	2021
19	BEmoC: A Corpus for Identifying Emotion in Bengali Texts	A. Iqbal, A. Das, O. Sharif, MM Hoque, and I H Sarker	BEmoC: A Corpus for Identifying Emotion in Bengali Texts, SN COMPUT. SCI. 3, 135 (2022).	2022
20	Classification of Textual Sentiment Using Ensemble Technique	M. M. Rahaman, O. Sharif, M. Moshiul Hoque	Classification of Textual Sentiment Using Ensemble Technique, SN COMPUT. SCI. 3, 49 (2022).	2022
21	Multi-class Textual Emotion Categorization using Ensemble of Convolutional and Recurrent Neural Network	T. Parvin, O. Sharif, MM Hoque	Multi-class Textual Emotion Categorization using Ensemble of Convolutional and Recurrent Neural Network, SN COMPUT. SCI. 3, 62 (2022).	2022
22	A source-driven reinforcement learning-based Data reply strategy to reduce communication overhead in Named Data Networks (NDN)	S. M. Iqbal, Asaduzzaman, M. M. Hoque	A source-driven reinforcement learning-based Data reply strategy to reduce communication overhead in Named Data Networks (NDN), Cluster Comput 25, 647–673 (2022).	2022
23	Development of Duplex Eye Contact Framework for Human-Robot Inter Communication	S. Sharmin, M. M. Hoque, S. M. R. Islam, M F. Kader and I H. Sarker,	Development of Duplex Eye Contact Framework for Human-Robot Inter Communication, IEEE Access, vol. 9, pp. 54435-54456, 2021, doi: 10.1109/ACCESS.2021.3071129.	2021
24	Active Vision-based Attention Monitoring System for Drivers	L. Alam, M M Hoque, N Siddique	Active Vision-based Attention Monitoring System for Drivers, IEEE Access, pp. 28540-28557, vol. 9, 2021.	2021
25	A Data-Driven Heart Disease Prediction Model Through K-Means Clustering-Based Anomaly Detection	R. C. Ripan, I. H. Sarker, S. M. M. Hossain, M. M. Anwar, R, Nowrozy, M. M. Hoque & M. H. Furhad	A Data-Driven Heart Disease Prediction Model Through K-Means Clustering-Based Anomaly Detection, SN COMPUT. SCI. 2, 112 (2021).	2021
26	Mobile Data Science and Intelligent Apps: Concepts, AI-based Modeling and Research Directions	I. H Sarker and MM Hoque	Mobile Data Science and Intelligent Apps: Concepts, AI-based Modeling and Research Directions, Mobile Network Appl 26, 285–303 (2021).	2021
27	Detecting Suspicious Texts Using Machine Learning Techniques	O Sharif, MM Hoque, ASM Kayes, R Nowrozy, IH Sarker	Detecting Suspicious Texts Using Machine Learning Techniques, Applied Sciences, 10(18), MDPI, 2020.	2020
28	“A Text-Based Chat System Embodied with an Expressive Agent,” Advances in Human-Computer Interaction	L. Alam, and M M Hoque	“A Text-Based Chat System Embodied with an Expressive Agent,” Advances in Human-Computer Interaction, vol. 2017, Article ID 8962762, 14 pages, 2017. doi:10.1155/2017/8962762.	2017
29	Fundamental Frequency Extraction of Noisy Speech Signals	M. A.F.M. R. Hasan, R. Yasmin, D. Das, M. M. Hoque, M. I. Pramanik, and M. S. Rahman	Fundamental Frequency Extraction of Noisy Speech Signals, Rajshahi University Journal of Science & Engineering, Vol. 43, pp. 51-61, 2015.	2015
30	An Empirical Robotic Framework for Initiating Interaction with the Target Human in Multiparty Settings	M. M. Hoque, Q. D. Hossian, K. Deb, D. Das, Y. Kobayashi, and Y. Kuno	An Empirical Robotic Framework for Initiating Interaction with the Target Human in Multiparty Settings, Journal of Circuits, Systems and Computers, Vol. 24, No. 02, 1540003 (2015) [25 pages] DOI: 10.1142/S0218126615400034.	2015
31	Outage Capacity Analysis of a Cooperative Relaying Scheme in Interference Limited Cognitive Radio Networks	M. F. Kader, Assaduzzaman, M. M. Hoque	Outage Capacity Analysis of a Cooperative Relaying Scheme in Interference Limited Cognitive Radio Networks, Wireless Personal Communications, Springer, 2014, doi 10.1007/s11277-014-1976-8.	2014
32	A Proactive Approach of Robotic Framework for Making Eye Contact with Humans	M. M. Hoque, Y. Kobayashi, and Y. Kuno	A Proactive Approach of Robotic Framework for Making Eye Contact with Humans, Advances in Human-Computer Interaction, vol. 2014, Article ID 694046, 19 pages, 2014. doi:10.1155/2014/694046.	2014
33	Effect of Robot’s Gaze Behaviors for Attracting and Controlling Human Attention	M. M. Hoque, T. Onuki, Y. Kobayashi, and Y. Kuno	Effect of Robot’s Gaze Behaviors for Attracting and Controlling Human Attention, Journal of Advanced Robotics, vol. 27, no. 11, pp. 1-17, Taylor & Francis, Japan, July 2013.	2013
34	Hybrid Spectrum Sharing with Cooprative Secondary User Selection in Cognitive Radio Networks	M. F. Kader, Assaduzzaman, M. M. Hoque	Hybrid Spectrum Sharing with Cooprative Secondary User Selection in Cognitive Radio Networks, KSII Transactions on Internet and Information Systems (TIIS), vol. 07, no. 09, pp. 2081-2100, 2013.	2013
35	A Robotic Framework for Controlling Human’s Attention	M. M. Hoque	A Robotic Framework for Controlling Human’s Attention, Paladyn Journal of Behavioral Robotics (JBR), vol. 03, no. 02, pp. 92-101, Springer, UK, 2012.	2012
36	Design a Robotic Head to Attract Human Attention by considering viewing situations	M. M. Hoque, Y. Kobayashi, Y. Kuno, and K. Deb	Design a Robotic Head to Attract Human Attention by considering viewing situations, Computer Science and Engineering Research Journal (CSERJ), vol. 08, pp. 29-38, 2012, Bangladesh.	2012
37	An Efficient Framework for Network Intrusion Detection	M. M. Hoque, A. M. Mahbub	“An Efficient Framework for Network Intrusion Detection”, Georgian Electronic Scientific Journal: Computer Science and Telecommunications, Vol. 24, No. 1, pp. 32-42, January 2010.	2010
38	English to Bangla Statistical Machine Translation using A* Search Algorithm	M. M. Hoque and M. K. Hassan	“English to Bangla Statistical Machine Translation using A* Search Algorithm”, Georgian Electronic Scientific Journal: Computer Science and Telecommunications, Vol. 18, No. 1, pp. 65-78, January 2009.	2009
39	An Empirical Framework for Parsing of Bangla Natural Language Sentences	M. M. Hoque and M. K. Hassan	“An Empirical Framework for Parsing of Bangla Natural Language Sentences”, International Journal of Translation (IJT), Vol. 20, No. 1-2, pp. 147-175, July-August 2008.	2008
40	An Empirical Framework for Translating of Phrasal Verbs of English Sentence into Bangla	M. M. Hoque, M. M. Ahammed and M. M. U. Hasan	An Empirical Framework for Translating of Phrasal Verbs of English Sentence into Bangla, BGC Trust University Journal, vol. 1, pp. 155-167, 2009.	2009
41	Context-free Grammars and Parsing for Simple Sentences of Bangla	M. M. Hoque, M. S. Arefin and M. S. Kowser	“Context-free Grammars and Parsing for Simple Sentences of Bangla” Computer Science and Engineering Research Journal (CSERJ), Vol. 2, PP. 53-60, ISSN: 1990-4010, 2005.	2005
42	Structural Operational Semantics of Inheritance and Object creation in JAVA	M. S. Arefin, M. M. Hoque, M. T. Islam and K. Dev	"Structural Operational Semantics of Inheritance and Object creation in JAVA", Computer Science and Engineering Research Journal (CSERJ), vol. 2, pp. 29-35, ISSN: 1990-4010, 2005.	2005
43	Semantic Analysis and Transfer: An Experience with the Bangla Natural Language Sentences	M. M. Hoque, M. S. Arefin and M. O. Rahman	“Semantic Analysis and Transfer: An Experience with the Bangla Natural Language Sentences”, Computer Science and Engineering Research Journal (CSERJ), vol. 3, pp. 17-23, ISSN: 1990-4010, 2006.	2006
44	A New Model of Digital Signature Using LSB Hiding, RSA and Merkle-Hellman Cryptosystem	A. N. M. R. Karim, M. G. R. Alam and M. M. Hoque	“A New Model of Digital Signature Using LSB Hiding, RSA and Merkle-Hellman Cryptosystem” Computer Science and Engineering Research Journal, vol. 4, pp. 39-44, 2007.	2007
45	An Empirical Framework for Statistical Parsing of Bangla Sentences	M. M. Hoque, M. O. Faruk, M. M. U. Hasan, M. K. Hassan and M. M. U. Karim	“An Empirical Framework for Statistical Parsing of Bangla Sentences”, Computer Science and Engineering Research Journal, vol. 4, pp. 29-38, 2007.	2007
46	Developing an Intelligent agent to support negotiation in an electronic market place	M. S. Arefin, R. Paul, M. M. Hoque and M. A. Sarif	“Developing an Intelligent agent to support negotiation in an electronic market place”, Computer Science and Engineering Research Journal (CSERJ), Vol. 3, PP. 30-37, ISSN: 1990-4010, 2006.	2006
1	Impact Analysis of Facebook in Family Bonding	Md. Sarwar Kamal and Mohammad Shamsul Arefin	Social Network Analysis and Mining (ISSN: 1869-5450), Springer, Vol. 6, issue 1	2016
2	Developing a Framework for Determining Students Excellence and Recommending Field of Study Under Review	Md. Osman Goni, Mohammad Shamsul Arefin, and Mohammad Monirul Islam	Smart Computing Review, South Korea	2015
3	Efficiency of NoSQL Databases under a Moderate Application Load	Mohammad Shamsul Arefin, Khondoker Nazibul Hossain, and Yasuhiko Morimoto	LNCS 8999, Springer, pp. 213-227	2015
4	A Statistical Framework for Detecting Diabetes Types	Linkon Chowdhury and Mohammad Shamsul Arefin	Smart Computing Review (ISSN: 2234-4624), vol. 5, no. 2	2015
5	Recommending Hotels by Social Conditions of Locations	Mohammad Shamsul Arefin, Zhichao Chang, and Yasuhiko Morimoto	Intelligent Systems Reference Library (Springer, ISSN: 1868-4394), pp. 91-106	2015
6	Agent-Based Privacy Aware Feedback System	Mohammad Shamsul Arefin, Rahma Bintey Mufiz Mukta, and Yasuhiko Morimoto	LNCS 8933, Springer, pp. 725-738	2014
7	A Spatial Skyline Query for a Group of Users	Mohammad Shamsul Arefin, Geng Ma, and Yasuhiko Morimoto	Journal of Software (ISSN: 1796-217X, Academy Publisher) vol. 9, no. 11, pp. 2938-2947	2014
8	Privacy Aware Parallel Computation of Skyline Sets Queries from Distributed Databases	Mohammad Shamsul Arefin, and Yasuhiko Morimoto	Computing and Informatics (ISSN:1335-9150), vol. 33, no. 4, pp. 831-856	2014
9	Skyline Query for Selecting Spatial Objects by Utilizing Surrounding Objects	Mohammad Shamsul Arefin, Xu Jinhao, Chen Zhiming, and Yasuhiko Morimoto	Accepted, Journal of Computers, ISSN: 1796-203X	2013
10	BAENPD: A Bilingual Plagiarism Detector	Mohammad Shamsul Arefin, Yasuhiko Morimoto, and Mohammad Amir Sharif	Accepted, Journal of Computers. ISSN: 1796-203X	2013
11	Skyline Query for Selecting Spatial Objects by Utilizing Surrounding Objects	Mohammad Shamsul Arefin, Xu Jinhao, Chen Zhiming, and Yasuhiko Morimoto	Journal of Computers (ISSN: 1796-203X, Academy Publisher), vol.8, no. 7, pp. 1742-1749	2013
12	Skyline Sets Queries for Incomplete Data	Mohammad Shamsul Arefin, and Yasuhiko Morimoto	International Journal of Computer Science & Information Technology (ISSN: 0975 - 3826), vol. 4, no 5, India	2012
13	Agent-based Anonymous Skyline Set Computation in Cloud Databases	Y. Morimoto, M. S. Arefin and M. A. Siddique	Int. J. Computational Science and Engineering, Vol. 7, No. 1, pp. 73-81, 2012. (ISSN: 1742-7193)	2012
14	Management of Multilingual Contents in Web Environment	M. S. Arefin and Y. Morimoto	International Journal of Computing Communication and Networking Research, Vol. 1, Issue-1, pp. 18-37, 2012. (ISSN: 1839-7212)	2012
15	Dispersion Control Characteristics of the Dielectric Cylindrical Waveguide And a Novel Approach of Dispersion Compensation	Nur Mohammad, Md. Asiful Islam, Abdul Khaleque and M. S. Arefin	International Journal of Engineering and Technology	2010
16	Multilingual Data Management in Database Environment	Dr. Abu Sayed Md. Latiful Hoque and Mohammad Shamsul Arefin	Malaysian Journal of Computer Science (ISSN 0127-9084) , Vol. 22, No. 1, pp 44-63	2009
17	Development and Implementation of an Efficient Database Compression Algorithm	M. S. Arefin, C. Sheel and M. M. Islam	Computer Science and Engineering Research Journal (ISSN: 1990-4010), Vol. 5, pp 23-31	2008
18	Semantic Analysis and Transfer: An Experience with the Bangla Natural Language Sentences	M .M. Hoque, M. S. Arefin and M. O. Rahman	Computer Science and Engineering Research Journal (ISSN: 1990-4010), Vol. 3, pp. 17-23	2005
19	Developing an Intelligent Agent to Support Negotiation in an Electronic Market Place	M. S. Arefin, R. Paul, M. M. Hoque and M. A. Sarif	Computer Science and Engineering Research Journal (ISSN: 1990-4010), Vol. 3, pp. 30-37	2005
20	Structural Operational Semantics of Some Important Properties in Java	M. S. Arefin	Asian Journal of Information Technology (ISSN : 1682-3915), vol. 3, issue 6, pp. 448-455	2004
21	Context-free Grammars and Parsing for Simple Sentences of Bangla	M. M. Hoque, M. S. Arefin and M. S. Kowser	Computer Science and Engineering Research Journal (ISSN: 1990-4010), vol. 2, pp. 53-60,2004,Bangladesh	2004
22	Structural Operational Semantics of Inheritance and Object creation in JAVA	M. S. Arefin, M. M. Hoque, M. T. Islam and K. Dev	Computer Science and Engineering Research Journal (ISSN: 1990-4010), vol. 2, pp. 29-35,2004,Bangladesh	2004
23	Structural Operational Semantics of Calling Methods in Java	M. S. Arefin	Asian Journal of Information Technology (ISSN : 1682-3915), vol. 3, issue 11, pp. 1059-1064,2004,Pakistan	2004
24	Designing a 34-Segment Display for Bengali and English Numerical Digits and Characters	M. S. Arefin	Asian Journal of Information Technology (ISSN: 1682-3915), Vol. 4, No. 5, pp. 478-484	2004
25	A Framework to Recommend Appropriate Learning Materials from Stack Overflow Discussions	A. Iqbal,M. S. Arefin,and M. A. A. Dewan	14th International Conference on ITS (LNCS 10858),2018, Canada	2018
1	Wi-Fi Based Real Time Communication for Disaster and Emergencies	Md. Ashiqur Rahman, Asaduzzaman, Md. Shafiul Alam Forhad	International Conference on Innovation in Engineering and Technology (ICIET), 27 - 28 December, 2018, Dhaka, Bangladesh	2019
2	Adaptive forwarding strategies to reduce redundant Interests and Data in named data networks	Shahid Md. Asif Iqbal and Asaduzzaman	Journal of Network and Computer Applications, Vol. 106, pp. 33--47, March 2018 (SCI)	2018
3	Cooperative Relaying to Improve the Spectrum Utilization of Multi-channel CR Networks	Asaduzzaman and Hyung Yun Kong	Journal of Wireless Personal Communication (Springer), Vol. 82, No. 4, pp. 523--531, September 2015 (SCI)	2015
4	Cognitive Radio MAC Protocols: A Survey, Some Research Issues and Challenges	Mahfuzulhoq Chowdhury, Asaduzzaman, and Md. Fazlul Kader	Smart Computing Review, Vol. 5, No.1, pp. 19-29, January 2015 (SCOPUS)	2015
5	Outage Capacity Analysis of a Cooperative Relaying Scheme in Interference Limited Cognitive Radio Networks	Md Fazlul Kader, Asaduzzaman, and Md. Moshiul Hoque	Journal of Wireless Personal Communication (Springer), vol. (2014)79, August, 2014. (SCI)	2014
6	An Opportunistic Two-Transceiver Based MAC Proto- col for Cognitive Radio Networks	Mahfuzulhoq Chowdhury and Asaduzzaman	International Journal of Multimedia and Ubiquitous Engineering ,Vol. 9, N0. 12, pp. 49-60, Dec. 2014 (SCOPUS)	2014
7	Performance Analysis of Local and Cooperative Spectrum Sensing in Cognitive Radio Networks	Mahfuzulhoq Chowdhury, Asaduzzaman, and Md. Fazlul Kader	International Journal of Signal Processing, Image Processing and Pattern Recognition (IJSIP), Vol. 6, No. 6, pp. 397-410, june 2013 (SCOPUS)	2013
8	Hybrid Spectrum Sharing with Cooperative Secondary User Selection in Cognitive Radio Networks	Md Fazlul Kader, Asaduzzaman, and Md. Moshiul Hoque	KSII Transactions on Internet and Information Systems, vol. 7, no. 9, September, 2013 (SCIE)	2013
9	De- sign of an Efficient MAC Protocol for Opportunistic Cognitive Radio Networks	Mahfuzulhoq Chowdhury, Asaduzzaman, Md. Fazlul Kader, and Mohammad Obaidur Rahman	International Journal of Computer Science & Information Technology (IJCSIT) Vol 4, No 5, October 2012 (SCOPUS)	2012
10	Ergodic and outage capacity of interference temperature-limited cognitive radio multi-input multi-output channel	Asaduzzaman and Hyung Yun Kong	IET communications, Vol. 5, Iss. 5, pp. 652–659, 2011 (SCI)	2011
11	Multi-relay cooperative diversity protocol with improved spectral efficiency	Asaduzzaman and Hyung Yun Kong	Journal of Communications and Networking, Vol. 13, Iss. 3, pp. 240–249, 2011 (SCI)	2011
12	Opportunistic Relaying based Spectrum Leasing for Cognitive Radio Networks	Asaduzzaman and Hyung Yun Kong	Journal of Communications and Networking, Vol. 13, Iss. 1, pp. 50–55, 2011 (SCI)	2011
13	Code Combining Cooperative Diversity in Long-haul Trans- mission of Cluster based Wireless Sensor Networks	Asaduzzaman and Hyung Yun Kong	KSII Transactions on Internet and Information Systems, Vol. 5, Iss. 7, pp. 1293–1310 (SCIE)	2011
14	On the outage behavior of interference temperature limited CR-MISO channel	Hyung Yun Kong and Asaduzzaman,	Journal of Communications and Networking, Vol. 13, Iss. 5, pp. 456–462, 2011 (SCI)	2011
15	Energy Efficient Cooperative LEACH Protocol for Wireless Sensor Networks	Asaduzzaman and Hyung Yun Kong	Journal of Communications and Networking, vol. 12, No. 4, pp.358–365, Aug. 2010 (SCI)	2010
16	A Cooperative Transmission Scheme for Cluster Based Wireless Sensor Networks	Asaduzzaman and Hyung Yun Kong	Lecture note on Artificial Intelligence, Volume 5755, pp. 728–737, 2010 (SCIE)	2010
17	Distributed Clustering Algorithm to Explore Cooperative Di- versity in Wireless Sensor Networks	Hyung Yun Kong and Asaduzzaman	IEICE Transactions on Communications, vol. E93-B, no. 5, pp. 1232–1239, May 2010 (SCI)	2010
18	Distributed Cooperative Routing Algorithm forMulti-hopMulti- relay Wireless Networks	Asaduzzaman and Hyung Yun Kong	Transactions on Communications, Vol. E93-B, No.04, pp.1049–1052 , Apr. 2010 (SCI)	2010
19	Performance analysis of code combining based cooperative protocol with amplified-and-forward (AF) relaying	Asaduzzaman and Hyung Yun Kong	IEICE Transactions on Communications, vol. E93-B, no. 2, pp. 2275–2278, Feb. 2010 (SCI)	2010
20	Coded diversity for cooperative MISO based wireless sensor networks	Asaduzzaman and Hyung Yun Kong	IEEE Communications Letters, vol. 13, No. 7, pp. 516–518, July 2009 (SCI)	2009
21	Code Combining Based Cooperative-LEACH Protocol for Wire- less Sensor Networks	Asaduzzaman and Hyung Yun Kong	IEICE Transactions on Communications, vol. E92-B, No. 6, pp. 2275–2278, June 2009 (SCI)	2009
22	Automatic Request for Cooperation (ARC) and Relay Selection for Wireless Networks	Asaduzzaman and Hyung Yun Kong	IEICE Transactions on Communications, vol. E92-B, no. 3, pp. 964–972, March 2009 (SCI)	2009
23	Composite Signaling Coded Cooperation for Fast and Slow Fading	Asaduzzaman and Hyung Yun Kong	IEICE Transactions on Communications, vol. E91-B, no. 9, pp. 3025–3029, Sept. 2008	2008
24	Code Combining in Cooperative Communication,” IEICE Trans- actions on Communications	Asaduzzaman and Hyung Yun Kong	vol. E91-B, no. 3, pp. 805–813, March 2008 (SCI)	2008
25	Performance Analysis of Machine Learning Techniques to Predict Diabetes Mellitus	M. F. Faruque, Asaduzzaman and I. H. Sarker	2019 International Conference on Electrical, Computer and Communi- cation Engineering (ECCE), Cox’sBazar, Bangladesh,	2019
26	Handwritten Bangla Numeral and Basic Character Recogni- tion Using Deep Convolutional Neural Network	S. M. Azizul Hakim and Asaduzzaman	2019 International Conference on Electrical, Com- puter and Communication Engineering (ECCE), Cox’sBazar, Bangladesh	2019
27	Compression of Large-Scale Image Dataset using Principal Component Analysis and K-means Clustering	R. Rayan, M. S. Hossain and Asaduzzaman	2019 International Conference on Electrical, Computer and Communication Engineering (ECCE), Cox’sBazar, Bangladesh	2019
28	A Minimum Spanning Tree Based Routing Protocol For Multi-hop And Multi-channel Cognitive Radio	S. Sultana and Asaduzzaman	2018 Joint 7th International Conference on Informatics, Electronics & Vision (ICIEV) and 2018 2nd International Conference on Imaging, Vision & Pattern Recognition (icIVPR), Kitakyushu, Japan, 2018, pp. 206-211	2018
29	Channel Assignment Augmentation Algorithm to Mitigate Interference for Heterogeneous ”TV White Space” Users	H. Ahmed and Asaduzzaman	2018 Joint 7th International Conference on Informatics, Electronics & Vision (ICIEV) and 2018 2nd International Conference on Imaging, Vision & Pattern Recognition (icIVPR), Kitakyushu, Japan, 2018, pp. 200-20	2018
30	Authentication of Diffie-Hellman Pro- tocol Against Man-in-the-Middle Attack Using Cryptographically Secure CRC	Nazmun Naher , Asaduzzaman and Md. Mokammel Haque	in Proceedings of International Ethical Hacking Conference 2018 (eHaCON 2018), Kolkata, India	2018
31	A distributed algorithm to select channel and relay in multichannel-multirelay CR- networks	Asaduzzaman	in proc. of 2017 International Conference on Networking, Systems and Security (NSysS), Dhaka, Bangladesh	2017
32	Enhancing Wi-Fi security using a hybrid algorithm of blowfish and RC6	Nusrat Jahan Oishi, Arafin Mahamud and Asaduzzaman	2016 International Conference on Networking Systems and Security (NSysS), Dhaka, Bangladesh	2016
33	CPU power consumption reduction in android smartphone	Masuma Akter Rumi, Asaduzzaman and D. M. Hasibul Hasan	2015 3rd International Conference on Green Energy and Technology (ICGET), Dhaka, Bangladesh	2015
34	Outage Capacity Analysis of a Secondary Network in Interference Limited Cognitive Radio Spectrum Sharing System	Md Fazlul Kader, Asaduzzaman, Soo Young Shin	in proc. of 17 th International Conference on Computer and Information Technology (ICCIT), ICCIT’14, Bangladesh; December 2014	2014
35	An Efficient MAC protocol for Cogni- tive Radio Networks	Mahfuzulhoq Chowdhury, Asaduzzaman, Md. Fazlul Kader	in Proc of International Conference on Engineering Research, Innovation and Education(ICERIE), Shahjalal University of Science & Technology,Bangladesh, pp. 322–327, Jan. 2013	2013
36	Cooperative Secondary User Selection as a Relay for the Primary System in Underlay Cognitive Radio Networks	Md Fazlul Kader, Asaduzzaman and M. Chowdhury	in Proc of IEEE 15th Interna- tional Conference on Computer and Information Technology(ICCIT)2012, University of Chittagong, Bangladesh, pp. 275–278, December 2012	2012
37	Cooperative Relaying in Interference Limited Cog- nitive Radio Networks	Asaduzzaman, Hyung Yun Kong and Kim Ryum	2010 IEEE 6th International Conference on Wireless and Mobile Computing, Networking and Communications, held in Niagara Falls, Canada	2010
38	A Cooperative Transmission Scheme for Cluster BasedWireless Sensor Networks	Asaduzzaman, Hyung Yun Kong and Ha Nguyen Vu	16th Asia-Pacific Conference on Communications (APCC 2010) held in Auckland New Zealand	2010
39	Tran Thanh Truc and Park Jihwan, “Optimal Switching AdaptiveM-QAMfor Opportunistic Amplify-and-Forward Networks	Vo Nguyen Bao, Hyung Yun Kong, Asaduzzaman	25th Queen’s Biennial Symposium on Communications (QBSC 2010)”,Kingston, Canada	2010
40	On The Capacity of Opportunistic Cooperative Networks under Adaptive Transmission	V. N. Q. Bao, Hyung Yun Kong, Asaduzzaman, J.-H. Lee and J.-H. Park	in IEEE PIMRC 2009, Tokyo, Japan	2009
41	A Cooperative Transmission Scheme for Cluster Based Wireless Sensor Networks	Asaduzzaman, Hyung Yun Kong and Kim Ryum	International Conference on Intelligent Computing (ICIC 2009), held in Ulsan, Korea, September 16–19, 2009	2009
42	Physical Layer Wireless Network Security Through Channel Coding	Asaduzzaman, Hyung-Yun Kong, Gun-Seok Kim and Nae-Soo Kim	Proceedings of the KIPS 2009	2009
43	Design of A High Order Diversity Cooperative Transmission Scheme Over Rayleigh Fading Channels	Ho Van Khuong, Hyung Yun Kong, Yun Kyeong Hwang, Asaduzzaman, Gun Seok Kim, Dea Kyu Choi	Proceedings of the Sixth IASTED International Conferences on communication, internet and information technology, held on Banff, Alberta, Canada July 2–4, 2008	2008
44	Adaptive Channel Coding for Flat Fading Channel	Asaduzzaman and Hyung Yun Kong	in Pro- ceedings of the KIPS 2008	2008
45	Cooperative Communica- tions in A Novel HCOC-QAM OFDM Spread Spectrum System with MMSE Equalizer for High Speed Data Transmission	Hyung Yun Kong, Ho Van Khuong, Asaduzzaman, S. J. Park, N. S. Kim	Proceedings of the Seventh IASTED International Conferences on Wireless and Optical Communications, held in Montreal, Quebec, Canada, May 30–June 1, 2007	2007
46	An efficient punctured code combining based cooperative trans- mission scheme for wireless networks	Asaduzzaman and Hyung Yun Kong	Proceedings of the 11th International Conference on Mecha- tronics technology-2007, ICMT2007, held on November 5–9, Ulsan, Korea, 2007	2007
47	Code-combining Cooperative Diversity Protocol	Asaduzzaman and Hyung-Yun Kong	Proceedings of the Summer Workshop On Computer Communications 2007, held on August 23–25, Jejo Island, Korea, 2008	2007
    1	A Modified Key Sifting Scheme With Artificial Neural Network Based Key Reconciliation Analysis in Quantum Cryptography	Chitra Biswas, Md. Mokammel Haque and Udayan Das Gupta	IEEE Access, vol. 10, 72743-72757 (Q1, ISI Indexed), IEEE	2022
2	Driving maneuver classification from time series data: a rule based machine learning approach	Md. Mokammel Haque, Supriya Sarker and M. Ali Akber Dewan	Applied Intelligence (SCI indexed), Springer, DOI:https://doi.org/10.1007/s10489-022-03328-3	2022
3	Utilizing Off-Chain Storage Protocol for Solving the Trillemma Issue of Blockchain	Saha Reno and Md. Mokammel Haque	3rd International Conference on Emerging Technologies In Data Mining And Information Security, IEMIS 2022, Part of the Advances in Intelligent Systems and Computing book series (AISC, volume 1348), pp. 169-179	2022
4	TOS: A Relative Metric Approach for Model Selection in Machine Learning Solutions	Ricko Shaha, Dipon Talukder, Md. Asif Iqbal and Md. Mokammel Haque	IEEE International Conference on Robotics, Automation, Artificial-Intelligence and Internet-of-Things (RAAICON 2021), IEEE	2021
5	A Machine Learning Approach to Clinically Diagnose Human Pyrexia Cases	Dipon Talukder and Md Mokammmel Haque	Proceedings of the International Conference on Big Data, IoT, and Machine Learning.	2021
6	Development of an Efficient ETL Technique for Data Warehouses	Md Badiuzzaman Biplob and Md. Mokammel Haque	Proceedings of the International Conference on Big Data, IoT, and Machine Learning, 243-255. Part of the Lecture Notes on Data Engineering and Communications Technologies book series, vol 95. Springer, Singapore.	2021
7	OkkhorNama: BdSL Image Dataset For Real Time Object Detection Algorithms	Dipon Talukder, Fatima Jahara, Suvadra Barua and Md. Mokammel Haque	IEEE Region 10 Symposium (TENSYMP), pp. 1-6, IEEE, doi: 10.1109/TENSYMP52854.2021.9550907	2021
8	A Comparative Analysis of Semi-Supervised Learning in Detecting Burst Header Packet Flooding Attack in Optical Burst Switching Network	Md. Kamrul Hossain , Md. Mokammel Haque and M. Ali Akber Dewan	Computers, 10(8),95 (ESCI, Scopus Indexed), MDPI	2021
9	Driving Maneuver Classification Using Domain Specific Knowledge and Transfer Learning	Supriya Sarker , Md. Mokammel Haque and M. Ali Akber Dewan	IEEE Access, vol. 09, 86590 - 86606 (SCIE, Scopus Indexed), IEEE	2021
10	Database Security as a Gateway to Privacy Preserving Data Mining	Chinmoy Bhowmik, Mahibul Abdullah Ibne Momin, Fariha Jahan Shanta and Md. Mokammel Haque	2nd International Conference on Robotics, Electrical and Signal Processing Techniques (ICREST), 125-130, IEEE	2021
11	An Approach Towards Domain Knowledge-Based Classification of Driving Maneuvers with LSTM Network	Supriya Sarker and Md. Mokammel Haque	Proceedings of International Joint Conference on Advances in Computational Intelligence, 469-484, Part of the Algorithms for Intelligent Systems book series (AIS), Springer	2021
12	Semi-supervised learning approach using modified self-training algorithm to counter burst header packet flooding attack in optical burst switching network	Md. Kamrul Hossain and Md. Mokammel Haque	International Journal of Electrical and Computer Engineering (IJECE), 10(4), 4340-4351 (Scopus Indexed), IAES	2020
13	A Data Change Rule Based Empirical Framework for Labeling Unlabeled Time Series Driving Data	Supriya Sarker and Md. Mokammel Haque	2nd International Conference on Advanced Information and Communication Technology (ICAICT), 476-479, IEEE	2020
14	A Semi-supervised Approach to Detect Malicious Nodes in OBS Network Dataset Using Gaussian Mixture Model	Md. Kamrul Hossain and Md. Mokammel Haque	Inventive Communication and Computational Technologies, 707-719, Part of the Lecture Notes in Networks and Systems book series (LNNS, vol.89), Springer	2020
15	Analyzing Progressive-BKZ Lattice Reduction Algorithm	Md. Mokammel Haque and Mohammad Obaidur Rahman	International Journal of Computer Network and Information Security (IJCNIS), 11(1), 40-46, (Scopus Indexed), MECS Press	2019
16	A semi-supervised machine learning approach using K-means algorithm to prevent burst header packet flooding attack in optical burst switching network	Md. Kamrul Hossain and Md. Mokammel Haque	Baghdad Science Journal,16(3), 804–815 (Scopus Indexed), University of Baghdad	2019
17	Elliptic curve and pseudo-inverse matrix based cryptosystem for wireless sensor networks	Shomen Deb and Md. Mokammel Haque	International Journal of Electrical and Computer Engineering (IJECE), 9(5) 4479-4492 (Scopus Indexed), IAES	2019
18	An improved fitness function for automated cryptanalysis using genetic algorithm	Md. Shafiul Alam Forhad, Md. Sabir Hossain, Mohammad Obaidur Rahman, Md. Mostafizur Rahaman, Md. Mokammel Haque and Md. Kamrul Hossain	Indonesian Journal of Electrical Engineering and Computer Science,13(2), 643–648 (Scopus Indexed), IAES	2019
19	Solving Multiple Depot Vehicle Routing Problem (MDVRP) using Genetic Algorithm	Nafiz Mahmud and Md. Mokammel Haque	2nd International Conference on Electrical, Computer and Communication Engineering (ECCE), 8679429, IEEE	2019
20	An Efficient Algorithm for Confidentiality, Integrity and Authentication Using Hybrid Cryptography and Steganography	Chitra Biswas, Udayan Das Gupta and Md. Mokammel Haque	2nd International Conference on Electrical, Computer and Communication Engineering (ECCE), 8679136, IEEE	2019
21	Preprocessing optimisation: Revisiting recursive-BKZ lattice reduction algorithm	Md. Mokammel Haque and Josef Pieprzyk	IET Information Security, 12(6), 551-557 (SCIE, Scopus Indexed), IET	2018
22	Sensor Applications and Physiological Features in Drivers Drowsiness Detection: A Review	Anuva Chowdhury, Rajan Shankaran, Manolya Kavakli and Md. Mokammel Haque	IEEE Sensors Journal, 18(8), 3055 - 3067 (SCI, Scopus Indexed), IEEE	2018
23	Authentication of Diffie-Hellman Protocol Against Man-in-the-Middle Attack Using Cryptographically Secure CRC	Nazmun Naher, Asaduzzaman and Md. Mokammel Haque	Proceedings of International Ethical Hacking Conference, 139-150, Part of the Advances in Intelligent Systems and Computing book series (AISC, vol.811), Springer	2018
24	An Improved Asymmetric Key Based Security Architecture for WSN	Md. Abdul Quaum, Shajir Uddin Haider and Md. Mokammel Haque	International Conference on Computer, Communication, Chemical, Material and Electronic Engineering (IC4ME2), 8465602, IEEE	2018
25	Analysing recursive preprocessing of BKZ lattice reduction algorithm	Md. Mokammel Haque and Josef Pieprzyk	IET Information Security, 11(2), 114-120, (SCIE, Scopus Indexed), IET	2017
26	Reducing network overhead of IoTDTLS protocol employing ChaCha20 and Poly1305	Maliha Momtaz Islam, Sourav Paul and Md. Mokammel Haque	20th International Conference of Computer and Information Technology (ICCIT), 8281857, IEEE	2017
27	An improved steganographic technique based on diamond encoding method	Md. Mokammel Haque, Jobayer Sheikh and Md. Jihan Al Rashid	International Conference on Electrical, Computer and Communication Engineering (ECCE), 583-588, IEEE	2017
28	A Hierarchical Key Derivative Symmetric Key Algorithm using Digital Logic	Chitra Biswas, Udayan Das Gupta and Md. Mokammel Haque	International Conference on Electrical, Computer and Communication Engineering (ECCE), 604-609, IEEE	2017
29	An efficient security architecture for Wireless Sensor Networks using pseudo-inverse matrix	Anuva Chowdhury, Farzana Alam Tanzila, Shanta Chowdhury and Md. Mokammel Haque	18th International Conference on Computer and Information Technology (ICCIT), 7488103, IEEE	2015
30	A secret key-based security architecture for wireless sensor networks	Anuva Chowdhury, Farzana Alam Tanzila, Shanta Chowdhury and Md. Mokammel Haque	International Conference on Computer and Information Engineering (ICCIE), 7399322, IEEE	2015
31	Evaluating the performance of the practical lattice reduction algorithms	Md Mokammel Haque and Josef Pieprzyk	8th International Conference on Electrical and Computer Engineering (ICECE), 7026884, IEEE	2014
32	Predicting tours and probabilistic simulation for BKZ lattice reduction algorithm	Md Mokammel Haque, Josef Pieprzyk and Asaduzzaman	9th International Forum on Strategic Technology (IFOST), 6991058, IEEE	2014
33	An asymmetric key-based security architecture for wireless sensor networks	Md. Mokammel Haque, Al-Sakib Khan Pathan, Choong Seon Hong and Eui-Nam Huh	KSII Transactions on Internet and Information Systems, 2(5), 265-279 (SCIE, Scopus Indexed), KSII	2008
34	Securing U-healthcare sensor networks using public key based scheme	Md. Mokammel Haque, Al-Sakib Khan Pathan and Choong Seon Hong	10th International Conference on Advanced Communication Technology (ICACT), IEEE	2008
35	An efficient PKC-based security architecture for wireless sensor networks	Md. Mokammel Haque, Al-Sakib Khan Pathan, Byung Goo Choi and Choong Seon Hong	MILCOM - IEEE Military Communications Conference, 4455317, IEEE	2007
36	Security management in wireless sensor networks with a public key based scheme	Al-Sakib Khan Pathan, Jae Hyun Ryu, Md. Mokammel Haque and Choong Seon Hong	Asia-Pacific Network Operations and Management Symposium (APNOMS ), 503-506, Part of the Lecture Notes in Computer Science book series (LNCS, vol. 4773), Springer	2007
1	Zebra Crossing Detection Based on HSV Colour Model and Projective Invariant for Driver Assistance System	Muhammad Kamal Hossen, Mohammad Obaidur Rahman, Anika Sadia, Md. Shahnur Azad Chowdhury	Inderscience Publishers of distinguished academic, scientific and professional journals International Journal of Applied Pattern Recognition (IJAPR)	2018
2	An Impoved Fitness Function for Automated Cryptanalysis using Genetic Algorithm	Md. Shafiul Alam Forhad, Md. Sabir Hossain, Mohammad Obaidur Rahman, Md. Mostafizur Rahaman, Md. Mokammel Haque, Muhammad Kamrul Hossain Patwary	Indonesian Journal of Electrical l Engineering and Computer Science (IJEECS) (Scopus)	2018
3	An Approach for Enhancing Security of Cloud Data using Cryptography and Steganography with E-LSB Encoding Technique	Mohammad Obaidur Rahman, Muhammad Kamal Hossen, Golam Morsad, Animesh Chandra Roy, and Shahnur Azad Chowdhury	IJCSNS International Journal of Computer Science and Network Security Vol. 18 No. 9 pp. 85-93( ESCI)	2018
4	Optimal Power Allocations of Different Modulations for Multi Channel Cognitive Radio Systems Using Stackelberg Game	Mohammad Obaidur Rahman and Asaduzzaman	International Journal of Advanced Science and Technology (IJAST) Vol.107 (2017), pp.43-60 (Scopus)	2017
5	Design of an Efficient MAC Protocol for Opportunistic Cognitive Radio Networks	Mahfuzulhoq Chowdhury, , Asaduzzaman, Md. Fazlul Kader and Mohammad Obaidur Rahman	International Journal of Computer Science & Information Technology (IJCSIT) Vol 4, No 5. Australia	2012
6	Algorithm for Linear Number Partitioning into Maximum Number of Subsets	Hussain Md. Mehedul Islam and Mohammad Obaidur Rahman	International Journal of Computer Applications (0975–8887) IJCA) Volume54– No.10. Canada	2012
7	Semantic Analysis and Transfer: An Experience with the Bangla Natural Language Sentences	Md. Moshiul Hoque, Mohammad Shamsul Arefin and Mohammad Obaidur Rahman	Computer Science and Engineering Research Journal (CSERJ) Vol 3, No 4. Bangladesh	2005
8	An Empirical Framework for Spatial Diseases Analysis and Patient Care Recommendation	Mohammad Obaidur Rahman, Md. Shafiul Alam Forhad, Md. Sabir Hossain, Md. Habibur Rahman	5th International Conference on Natural Sciences and Technology (ICNST’18) Asian University for Women, Chittagong, Bangladesh	2018
9	Optimal Power Allocation for Multichannel Cognitive Radio Systems Using Stackelberg Game	Mohammad Obaidur Rahman and Asaduzzaman	International Conference on Advanced Information and Communication Technology (ICAICT) Bangladesh	2016
10	A Machine Translation Framework for Translating Bangla Assertive, Interrogative and Imperative Sentences into English	Mohammed Safayet Arefin, Mohammed Moshiul Hoque, Md. Obaidur Rahman, Md. Shamsul Arefin	International Conference on Electrical Engineering and Information Communication Technology (ICEEICT). , Bangladesh	2015
11	Design an efficient MAC Protocol for Cognitive Radio Systems using Game Theory	Debbrata Kumar Saha, Asaduzzaman, Mohammad Obaidur Rahman	National Conference on Intelligent Computing and Information Technology (NCICIT), Bangladesh	2013
1	An Agent Based Parallel and Secure Framework to Collect Feedbacks	Rahma Bintey Mufiz Mukta, and Mohammad Shamsul Arefin	Journal of Computers vol. 14, no. 6, pp. 404-425	2019
2	Detection of Malaria Parasite in Giemsa Blood Sample Using Image Processing	Kishor Roy, Shayla Sharmin, Rahma Bintey Mufiz Mukta, Anik Sen	International Journal of Computer Science & Information Technology (IJCSIT) Vol 10, No 1	2018
3	Performance Analysis of Node-Disjoint Multipath in MANET: A Modified Approach	Rahma Bintey Mufiz Mukta	International Journal of Computer Applications 162(6):16-22	2017
4	Agent Command Manipulation System using Two Keys Encryption Model	Rahma Bintey Mufiz Mukta & Sarah Sohana	5th International Conference on Informatics, Electronics & Vision(ICIEV)	2016
5	Agent-Based Privacy Aware Feedback System	Mohammad Shamsul Arefin,Rahma Bintey Mufiz Mukta,Yasuhiko Morimoto	Advanced Data Mining and Applications. ADMA 2014. Lecture Notes in Computer Science, vol 8933. Springer, Cham	2014
6	A Novel Approach to find the Complete Node Disjoint Multipath in MANET	Mr. Thomas Chowdhury & Rahma Bintey Mufiz Mukta	3rd International Conference on Informatics, Electronics & Vision(ICIEV)	2014
1	Shadow processing with color model adjustment and texture analysis	Md. Azhar Uddin, Tahmina Khanam, Muhammad Ibrahim Khan, Kaushik Deb and Kang-Hyun Jo	The International Workshop on Intelligent Systems, Ulsan, Republic of Kore, August 17-19	2022
2	SVD-Based Image Watermarking Using the Fast Walsh-Hadamard Transform, Key Mapping, and Coefficient Ordering for Ownership Protection	Tahmina Khanam, Pranab Kumar Dhar, Saki Kowsar and Jong-Myon Kim	Symmetry, vol. 12, no. 52, pp. 1-20	2020
3	A Comparative Study on Handwritten Bangla Character Recognition	Mohammad Atiqul Islam Rizvi, Kaushik Deb, Mohammad Ibrahim Khan, Mir Mohammad Saki Kowsar and Tahmina Khanam	Turkish Journal of Electrical Engineering & Computer Sciences, vol. 27, no. 4, pp. 3195-3207	2019
4	Illegally Parked Vehicle Detection Based on Haar-Cascade Classifier	Aapan Mutsuddy, Kaushik Deb, Tahmina Khanam, and Kang-Hyun Jo	Lecture Notes in Computer Science, vol. 11644, pp. 602–614	2019
5	Human Detection Based on HOG-LBP for Monitoring Sterile Zone	Farjana Bintay Kamal, Sangita Mitra, Tahmina Khanam, Uzzal K. Acharjee, Dipankar Das and Kaushik Deb	in Proceeding 2nd International Conference on Electrical, Computer and Communication Engineering, Cox’s Bazar, Bangladesh, February 7-9	2019
6	Baggage Recognition in Occluded Environment using Boosting Technique	Tahmina Khanam and Kaushik Deb	KSII Transactions on Internet and Information Systems, vol. 11, no. 11, pp. 5436-5458	2017
7	Baggage Detection and Classification using Human Body Parameter & Boosting Technique	Tahmina Khanam and Kaushik Deb	in Proceedings of the 10th IEEE International Conference on Human System Interactions, pp. 54-59 ,Ulsan, Republic of Korea, July 17-19	2017
8	A Tree-Based Arithmetic Coding by Estimating Exact Probability Distribution for Data Compression	Tahmina Khanam, Pranab Kumar Dhar and Golam Moktader Daiyan	in Proceedings of the International Conference on Mechanical Engineering and Renewable Energy, pp. 18 – 20, Chittagong, Bangladesh, December	2017
9	Human and Carried Baggage Detection & Classification based on RSD-HOG in Video Frame	Tahmina Khanam and Kaushik Deb	in Proceedings of the 9th IEEE International Conference on Electrical & Computer Engineering, pp. 415 - 418, BUET, Dhaka, Bangladesh, December 20-22	2016
10	An Efficient Framework for Detecting Face Region Based on Skin Color Modeling and SVM Classifier	Arpita Chowdhury, Tahmina Khhanm and Kaushik Deb	in Proceedings of the 1st International Conference on Mathematics and Its Applications, pp. 42-46, Khulna, Bangladesh, December 23	2015
11	Color Image Watermarking Based on LU Decomposition	Kazi Anika Hossain Naima, Tahmina Khanam and Kaushik Deb	in Proceedings of the 1st International Conference on Mathematics and Its Applications, pp. 47-52, Khulna, Bangladesh, December 23	2015
12	Detecting Anomalous Behavior of Credit Card Transaction using Statistical Approach	Kaushik Deb, Kazi Zakia Sultana and Tahmina Khanam	The Chittagong University Journal of Science, vol. 37, pp 62-75	2015
13	Video Watermarking Scheme using Second Level Discrete Wavelet Transformation (DWT) and Fast Fourier Transformation	Rahat Mahmud, Tahmina Khanam and Kaushik Deb	in Proceedings of the 3rd International Conference on Mechanical Engineering and Renewable Energy, Chittagong, Bangladesh, December 26-29	2015
1	Vision-Based Driver’s Attention Monitoring System for Smart Vehicles	Lamia Alam and Mohammed Moshiul Hoque	In: Vasant P., Zelinka I., Weber GW. (eds) Intelligent Computing & Optimization. ICO 2018. Advances in Intelligent Systems and Computing, vol 866. Springer, Cham, 2019	2018
1	Automatic Detection of Suspicious Bangla Text Using Logistic Regression	Omar Sharif and Mohammed Moshiul Hoque	In: Vasant P., Zelinka I., Weber GW. (eds) Intelligent Computing and Optimization. ICO 2019. Advances in Intelligent Systems and Computing, vol 1072. Springer, Cham. DOI https://doi.org/10.1007/978-3-030-33585-4_57	2019
2	Sentiment Analysis of Bengali Texts on Online Restaurant Reviews Using Multinomial Naive Bayes	Omar Sharif, Mohammed Moshiul Hoque, Eftekhar Hossain	1st International Conference on Advances in Science, Engineering and Robotics Technology (ICASERT-2019) DOI: 10.1109/ICASERT.2019.8934655	2019
1	A comparative study on handwritten Bangla character recognition	MD. ATIQUL ISLAM RIZVI, KAUSHIK DEB, MD. IBRAHIM KHAN, MIR MD. SAKI KOWSAR, TAHMINA KHANAM	TURKISH JOURNAL OF ELECTRICAL ENGINEERING & COMPUTER SCIENCES, Vol. 27, Issue. 4, pp. 3195-3207	2019
1	A Secured Electronic Voting System Using Blockchain	Md. Rashadur RahmanMd, Billal Hossain, Mohammad Shamsul Arefin, authorMohammad Ibrahim Khan	International Conference on Intelligent Computing & Optimization, Hua Hin, Thailand, Springer. DOI: https://doi.org/10.1007/978-3-030-68154-8_111	2021
2	Towards a Framework for Acquisition and Analysis of Speeches to Identify Suspicious Contents through Machine Learning	Md. Rashadur Rahman, Mohammad Shamsul Arefin , Md. Billal Hossain, Mohammad Ashfak Habib, and A. S. M. Kayes	Complexity, Wiley & Hindawi Limited (Q1, H Index: 52, Cite Score: 3.2, IF: 2.46, DBLP, Scopus, SCI, SCIE indexed) doi: https://doi.org/10.1155/2020/5639787 (available at: https://www.hindawi.com/journals/complexity/2020/5639787/)	2020
3	Aspect Based Sentiment Classification and Contradiction Analysis of Product Reviews	Md. Shahadat Hossain, Md. Rashadur Rahman, Mohammad Shamsul Arefin	International Conference on Computer Networks, Big Data and IoT (ICCBI - 2019) [Lecture Notes on Data Engineering and Communications Technologies, vol 49. Springer, Cham. https://doi.org/10.1007/978-3-030-43192-1_71]	2019
1	A Transfer Learning Approach to Recognize Pedestrian Attributes	Saadman Sakib, Anik Sen, Kaushik Deb	Siddique, N., Arefin, M.S., Kaiser, M.S., & Kayes, A. (Eds.). (2023). Applied Intelligence for Industry 4.0 (1st ed.). Chapman and Hall/CRC. https://doi.org/10.1201/9781003256083	2021
2	A Framework for Pedestrian Attribute Recognition Using Deep Learning.	Saadman Sakib, Kaushik Deb, Pranab K. Dhar, and Oh-Jin Kwon	Sakib, Saadman, Kaushik Deb, Pranab Kumar Dhar, and Oh-Jin Kwon. 2022.	2022
3	A Framework for Industrial Inspection System using Deep Learning	Monowar Wadud Hridoy, Mohammad Mizanur Rahman, and Saadman Sakib	Hridoy, Monowar Wadud, Mohammad Mizanur Rahman, and Saadman Sakib. “A Framework for Industrial Inspection System Using Deep Learning.” Annals of Data Science, 2022. https://doi.org/10.1007/s40745-022-00437-1.	2022
1	Attention-Based Human Age Estimation from Face Images to Enhance Public Security	Md. Ashiqur Rahman ,Shuhena Salam Aonty, Kaushik Deb, Iqbal H. Sarker Iqbal H. Sarker	Data 2023, 8(10), 145; Published by MDPI https://doi.org/10.3390/data8100145	2023
2	Human Pose Estimation Using Parallel Architecture	Shuhena Salam Aonty; Kaushik Deb; Dhrubajyoti Das; Kang-Hyun Jo	DOI: 10.1109/IWIS58789.2023.10284672; 2023 International Workshop on Intelligent Systems (IWIS), Ulsan, Republic of Korea	2023
3	Multi-Person Pose Estimation Using Group-Based Convolutional Neural Network Model	Shuhena Salam Aonty, Kaushik Deb, Moumita Sen Sarma, Pranab Kumar Dhar,Tetsuya Shimamura	IEEE Access DOI: 10.1109/ACCESS.2023.3271593 License CC BY-NC-ND 4.0	2023
4	Jointly Learning Structure for Human Pose Estimation using Convolutional Neural Network	Shuhena Salam Aonty, Moumita Sen Sarma, Dr. Kaushik Deb	4th International Conference on Electrical, Computer & Telecommunication Engineering (ICECTE 2022)	2022
5	Jointly Learning Structure for Human Pose Estimation using Convolutional Neural Network	Shuhena Salam Aonty, Moumita Sen Sarma, Dr. Kaushik Deb	4th International Conference on Electrical, Computer & Telecommunication Engineering (ICECTE) ISBN:979-8-3503-2055-8 DOI: 10.1109/ICECTE57896.2022.10114551 Publisher: IEEE	2022
1	Recursive independent component analysis (ICA)-decomposition of ictal EEG to select the best ictal component for EEG source imaging	Mohammad Ashfak Habib, Fatimah Ibrahim, Mas S Mohktar, Shahrul Bahyah Kamaruzzaman, Kheng Seang Lim	Clinical Neurophysiology (Elsevier), Vol. 131(3), pp. 642-654. (Q1, SCI). https://doi.org/10.1016/j.clinph.2019.11.058	2020
2	Ictal EEG source imaging for presurgical evaluation of refractory focal epilepsy	Mohammad Ashfak Habib, Fatimah Ibrahim, Mas S Mohktar, Shahrul Bahyah Kamaruzzaman, Kartini Rahmat, Kheng Seang Lim	World Neurosurgery (Elsevier), Vol. 88, pp. 576-585. (Q1, SCI). https://doi.org/10.1016/j.wneu.2015.10.096	2016
3	Recursive approach to the design of a parallel self-timed adder	Mohammed Ziaur Rahman, Lindsay Kleeman, Mohammad Ashfak Habib	IEEE transactions on very large scale integration (VLSI) systems, Vol. 23(1), pp. 213-217. (Q2, SCI). https://doi.org/10.1109/TVLSI.2014.2303809	2015
4	Smartphone-based solutions for fall detection and prevention: challenges and open issues	Mohammad Ashfak Habib, Mas S Mohktar, Shahrul Bahyah Kamaruzzaman, Kheng Seang Lim, Tan Maw Pin, Fatimah Ibrahim	Sensors (MDPI), Vol. 14(4), pp. 7181-7208. (Q1, SCI). https://doi.org/10.3390/s140407181	2014

"""  # Replace with the full text

# Split text into lines and parse data
lines = text.strip().split('\n')
data = []

for line in lines:
    # Split the line into parts by tab or space
    parts = line.split('\t')
    if len(parts) >= 3:
        title = parts[1].strip()
        authors = parts[2].strip()
        data.append((title, authors))

# Save to CSV
with open('research_titles_authors.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Title', 'Authors'])  # Write headers
    writer.writerows(data)

print("Data saved to research_titles_authors.csv")
